### ISSUE TITLE
Intermittant Failures from vstest on Hosted VS2017 agent queue

### ISSUE THREAD

**Issue by MattSFT** [Microsoft/vstest#1419] opened 2018-02-05 22:44 UTC
I have a build that fails intermittently. I have seen three variations of output from the vstest task. Here is the failed output:
![image](https://user-images.githubusercontent.com/29067893/35832491-5a3bbd18-0a82-11e8-96e4-c91038205e1d.png)

This is the YAML of the test step:
steps:
- task: VSTest@2
  inputs:
    testAssemblyVer2: |
          CardPreviewerService\**\*tests.dll
          !CardPreviewerService\**\obj\**
    vsTestVersion: '15.0'
    codeCoverageEnabled: 'true'

I've tried latest and vs 2017 for my test runner and both seem to fail randomly. It looks like there is a weird encoding in the build for the output not sure if that has anything to do with it.

**Comment by mayankbansal018** [comment] 2018-02-06 08:48
@MattSFT , we have recently seen failures with datacollection enabled on Hosted Machines with VS2017 update 5.
The issue is primarily because on slow machines there is a delay in testhost process launch. In addition CLR profiler is causing additional delay as testhost is launched under profiler.
Due to this delay in testhost process launch, it is sometimes unable to communicate with datacollector process, as datacollector process times out after 15 seconds.

Does your project also uses fakes apart from CodeCoverage?

Please [refer bug](https://github.com/Microsoft/vstest/issues/1410)

**Comment by MattSFT** [comment] 2018-02-06 18:35
Yes this seems to have popped up right after we added fakes to our tests.

**Comment by MattSFT** [comment] 2018-02-07 00:42
@mayankbansal018 Is there a proposed fix that I can apply to my build definition?

**Comment by mayankbansal018** [comment] 2018-02-07 07:28
@MattSFT , we are planning to roll out a fix, which will be available with out Testplatform package, on nuget.org. Once we have published it, you can use Nuget Installer Task in vsts, & use that to run tests. I'll share more details on it once I've published the package

**Comment by mayankbansal018** [comment] 2018-02-08 09:35
@MattSFT, We have published a fix for this issue in our latest Testplatform preview on nuget.org, can you please modify your build definition to use “VsTest platform Installer”, & then use it in VsTest task by setting “Test platform version” to “Installed by Tools Installer”.

Make sure you have “VsTest platform Installer” before “VsTest” task.

See attached images for more reference. This is would help us in dogfooding our platform bits as well, before we officially blog post this fix.
![vstest](https://user-images.githubusercontent.com/24792973/35965591-6a4eb9d8-0ce1-11e8-9e8f-fc4f1f0a1e7f.PNG)
![vstest platform installe](https://user-images.githubusercontent.com/24792973/35965596-6bff57ce-0ce1-11e8-81b2-9c51201c9e03.PNG)

**Comment by jean-paullizotte** [comment] 2018-02-14 02:37
New issues have now popped up. All kinds of behaviors including messages like: 

2018-02-14T02:03:14.3225911Z ##[error]Error connecting to Vstest Command Line
2018-02-14T02:03:14.3226790Z ##[error]DiscoverTests.PerformDiscovery : Could not locate rocksteady binaries

And in some cases

2018-02-14T02:19:07.2269991Z ##[error]RunMessage : An exception occurred while invoking executor 'executor://mstestadapter/v2': Constructor on type 'Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.UnitTestRunner' not found.

And when trying to use 2017 test:

2018-02-14T01:04:38.8308502Z ##[error]Error: D:\a\_tool\VsTest\15.6.0-preview-20180207-05\x64\tools\net451\Common7\IDE\Extensions\TestPlatform\vstest.console.exe failed with return code: 1
2

Our gated builds are now unusable because of tests failing!
I am at my wits end and am considering moving our builds to teamcity or jenkins!!


Our gated builds are now unusable because of tests failing!

**Comment by mayankbansal018** [comment] 2018-02-14 06:40
@jean-paullizotte , Given that you have mentioned your problem with this issue, I'm assuming you are using Hosted Agents to run your tests

In your build definition, can you please enable logs when you are running tests using VS 2017. You can enable logs via setting "system.debug=true" under variables in your build definition, & please share those logs with us.

See attached image.
![vs-test-diagnostics](https://user-images.githubusercontent.com/24792973/36190736-ead940ee-117f-11e8-9e86-bdf6dd4788ee.PNG)

**Comment by jean-paullizotte** [comment] 2018-02-14 17:02
I am aware how to do verbose logging in team build. Thank you.
I am sorry to inform you, though, that when we reproduce the error it breaks our workflow and that I have no **FREE** time to help you debug this issue.

All I can say is that this was working Monday and was broken on Tuesday **without doing any changes on our side**.

I was  billing the client over 100$/hour to fix, what I am presuming is, _your issue_ last night to get our production working again.

If the testing module in VSTS is unreliable (which you have already as much admitted, with a possible workaround) we would expect, as paying production users and suppliers of Microsoft solutions (we are Devops gold partners) a bit more rigor and respect for critical production systems.

Now, can you roll back to the VStest version of last Monday and restore our workflow? Or can we just forget about unit tests until you rollout a stable version?

Thank you.

**Comment by cltshivash** [comment] 2018-02-15 09:43
@jean-paullizotte Few clarifications. The test platform tools installer is a mechanism to acquire test platform on machines without VS and on machines with VS it provides an option to acquire critical fixes to keep CI/CD pipelines running instead of waiting for VS updates. It doesn't impact your VS installation in any manner and is not a *workaround* and is fully supported by the test tools team in VSTS

We are really sorry that you are running into this issue and unless we get the logs it is equally tough on our part to resolve the issue and unblock you. The testing module is reliable and in case of any issues it is our priority to fix and resolve issues. Let us know if there's any other mode through which we can resolve the problem you are running into.

**Comment by jean-paullizotte** [comment] 2018-02-15 14:37
@cltshivash I think I understand how the platform tools installer maintains hosted build machines. The problem I have with your statement, is that VSTEST 2015 and 2017 is broken on the hosted machines (as per this whole thread), and our only way "around" this to use the "platform tools installer". You state this is not a workaround, yet... we should be able to just use latest version if it wasn't broken... and live changes shouldn't break existing functionality.

Look at it from our point of view, it was working, then it stopped working. Something changed and we have no control over this change. Using VSTS, as it was, wasn't sufficient to continue our existing pipeline. And we had to make a change in our build process to continue functionally, to accommodate that _brokeneness_.

This was working fine until Monday. And now it doesn't. If it is a fully supported production release pipeline tool, I can only reiterate it's broken. In the Devops cycle, if you pushed a broken release, you must have a fallback and we are not seeing it. It is _concerning_, to say the least.

**Comment by cltshivash** [comment] 2018-02-23 11:16
@jean-paullizotte : Without logs we won't be able to make progress here.

**Closed by cltshivash** 2018-02-23 11:16 UTC
Labels: bug
