### ISSUE TITLE
updating to Microsoft.NET.Test.Sdk 16.9.1 causes ReflectionTypeLoadException 

### ISSUE THREAD

**Issue by SimonCropp** [microsoft/vstest#2791] opened 2021-03-02 23:54 UTC
* TFM: net48 and net5
 * Repro: https://github.com/SimonCropp/TestSdkRepro
```
    [Fact]
    public void Foo()
    {
        foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies())
        {
            foreach (var type in assembly.GetTypes())
            {
                Debug.WriteLine(type);
            }
        }
    }
```
 * run `dotnet test`
 * Result: `ReflectionTypeLoadException`
```
Test run for C:\Code\TestSdkRepro\bin\Debug\net5.0\TestSdkRepro.dll (.NETCoreApp,Version=v5.0)
Microsoft (R) Test Execution Command Line Tool Version 16.9.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:00.79]     UnitTest1.Foo [FAIL]
  Failed UnitTest1.Foo [96 ms]
  Error Message:
   System.Reflection.ReflectionTypeLoadException : Unable to load one or more of the requested types.
Could not load file or assembly 'Microsoft.VisualStudio.Coverage.CoreLib.Net, Version=16.9.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
  Stack Trace:
     at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at UnitTest1.Foo() in C:\Code\TestSdkRepro\UnitTest1.cs:line 12

```

Also seen in other projects. https://github.com/SwissLife-OSS/snapshooter/pull/126 note they worked around it by catching `ReflectionTypeLoadException` 

Environment:

 * .net sdk 5.0.103 and 5.0.200-preview2
 * Windows Server 2016

**Comment by SimonCropp** [comment] 2021-03-03 00:11
interestingly (random guess). adding a ref manual ref to `Microsoft.VisualStudio.Coverage.CoreLib.Net.dll` make the test pass 
```
  <ItemGroup>
    <Reference Include="Microsoft.VisualStudio.Coverage.CoreLib.Net">
      <HintPath>D:\nugetglobalpackages\microsoft.codecoverage\16.9.1\build\netstandard1.0\Microsoft.VisualStudio.Coverage.CoreLib.Net.dll</HintPath>
    </Reference>
  </ItemGroup>
```

not sure if that helps anyone debugging?

**Comment by joemey** [comment] 2021-03-05 09:59
The excepetion is raised by loading `Microsoft.TestPlatform.Utilities`.

I guess the problem is that in the `testhost.deps.json` file inside the nuget package `Microsoft.TestPlatform.Utilities` is referencing `Microsoft.VisualStudio.Coverage.CoreLib.Net/16.9.0-beta.21119.4`.

https://github.com/microsoft/vstest/blob/6a858a323caa439115e9e3cf1c958b04f4ff9993/scripts/build/TestPlatform.Dependencies.props#L35

**Comment by nohwnd** [comment] 2021-03-05 10:45
@Haplois probably connected to the other issue you are solving.

**Comment by Haplois** [comment] 2021-03-05 12:43
The issue here is, `Microsoft.CodeCoverage` package doesn't include all of its dependencies correctly thus `Microsoft.VisualStudio.Coverage.CoreLib.Net.dll` file is missing from the build output. 

/cc: @fhnaseer @jakubch1

**Comment by jakubch1** [comment] 2021-03-08 05:18
@fhnaseer could you please cherry pick change to load CoreLib.Net.dll dynamically to release branch 16.9?

**Comment by Haplois** [comment] 2021-03-08 10:28
> @fhnaseer could you please cherry pick change to load CoreLib.Net.dll dynamically to release branch 16.9?

Please let me know when it's done; I also have a hotfix to include. We can release a preview when both are done.

**Comment by Haplois** [comment] 2021-03-08 11:01
Also, I just created the branch [preview/16.9.2](https://github.com/microsoft/vstest/tree/preview/16.9.2) please use that, after all is done we can merge to `rel` branch. @fhnaseer

**Comment by SimonCropp** [comment] 2021-03-17 01:46
is there an eta on 16.9.2? can i help by smoke testing a preview nuget?

**Comment by Haplois** [comment] 2021-03-17 20:11
Version `16.9.2-preview-20210317-01` does include this fix, and available on our daily feed.

**Comment by SimonCropp** [comment] 2021-03-22 21:17
@Haplois can that version be deployed to nuget?

**Comment by Haplois** [comment] 2021-03-23 08:24
@SimonCropp, we'll be releasing a preview this week. Probably on Wednesday.

**Comment by white-label-development** [comment] 2021-03-29 09:45
Had same issue. Can confirm that upgrading to your fixed preview version solved the problem. Thanks for being so quick.

**Comment by Sanan07** [comment] 2021-06-03 12:18
Closing, as have confirmation that it worked after update.

**Closed by Sanan07** 2021-06-03 12:18 UTC
