### ISSUE TITLE
When running Tests if I use Test Category it is ignored when running Batch Mode

### ISSUE THREAD

**Issue by aaronportier** [microsoft/vstest#4910] opened 2024-02-26 21:20 UTC
IsValidServiceResponse: Received None command..Service Workflow is not active
Creating run for selected test assemblies with following parameters
SourceFilter: ThisWontBeUsed TestCaseFilter: TestCategory=UserSubscription
The above is the log and All my tests run not just the UserSubscription ones.

**Comment by nohwnd** [comment] 2024-07-08 10:30
duplicate of https://github.com/microsoft/vstest/issues/4782

**Closed by nohwnd** 2024-07-08 10:30 UTC
