### ISSUE TITLE
Regression in 3.1.200 for dotnet test -t

### ISSUE THREAD

**Issue by wli3** [microsoft/vstest#2392] opened 2020-04-08 20:36 UTC
_From @mareklinka on Friday, March 20, 2020 1:00:41 AM_

Hello all. I seem to have stumbled upon a rather weird possible regression after I migrated from SDK 3.1.102 to 3.1.200.

**Context**
A few days ago I forked the VSCode extension [formulahendry/vscode-dotnet-test-explorer](https://github.com/formulahendry/vscode-dotnet-test-explorer) and started playing around with bringing it up to speed for Core SDK 3.1 and doing some other changes. For testing my changes, I was using the solution I work on at my job.

The extension first discovers possible test projects in a VSCode workspace and then executes `dotnet test -t -v=q [project]` against one project at a time. It waits until the execution terminates and reads the stdout in order to retrieve the list of tests. This list is further processed and displayed etc.

While I was using the SDK 3.1.102, everything was working perfectly here. The command produced the list of tests every time without issues. However, after I updated to SDK 3.1.200, this started failing in more than 50% of executions (but not always).

**The issue**
In SDK 3.1.200, the `dotnet test -t -v=q [project path]` terminates but it looks like the stdout is not properly flushed. The extension reads the stdout and only  gets as far as
```
Test run for [pathToDll](.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.5.0
Copyright (c) Microsoft Corporation.  All rights reserved.

The following Tests are available:
```
And that's it. No tests are listed in the stdout (even though they are there, of course). If I run the same command from the command line, the output is complete (with tests), but there is an observable pause between outputting `The following Tests are available:` and the actual list of tests.

To verify the regression theory, I introduced a global.json and used it to fix a specific SDK version for the solution in question. The results are consistent - 3.1.102 works every time, 3.1.200 fails more often then not.

Since the problem does not manifest every time, it feels like a possible race condition to me. If the `dotnet` process terminates too quickly, the stdout isn't flushed completely and whatever is in the buffer gets lost. But it's really just a theory.

**The problematic code**
``` ts
function executeDotnetTest(testDirectoryPath: string, dotnetTestOptions: string): Promise<string> {
    return new Promise((resolve, reject) => {
        Logger.Log(`Executing dotnet test -t -v=q in ${testDirectoryPath}`);

        let buffer = "";

        const p = cp.spawn("dotnet", ["test", "-t", "-v=q" ], { cwd: testDirectoryPath });
        p.stdout.on("data", (data) => buffer += data.toString());
        p.on("close", (code) => {
            if (code !== 0) {
                Logger.LogError(`Error while executing dotnet test -t -v=q`, code);

                reject();
            }

            Logger.Log(buffer);

            resolve(buffer);
        });
    });
}
```
Now I'm not the greatest with Node.js but this should work and does work when using the older SDK. It spawns a new process with the necessary parameters, hooks to the stdout to build a buffer, then, when the process closes all its IO streams, logs the buffer and resolves the promise.

More details: the projects in question use xUnit for testing framework, but it also reproduces with MSTest.

**Question**
Can someone please try and clarify what's going on here? Or possibly offer a workaround?

_Copied from original issue: dotnet/sdk#10926_

**Comment by wli3** [comment] 2020-04-08 20:36
_From @mareklinka on Friday, March 20, 2020 5:56:08 AM_

Ok, after digging more deeply into what is happening here, I managed to dig up this. Each of the failed `dotnet` executions end up with the following error:

```
Error while executing dotnet test -t -v=q - Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Testhost process exited with error: Failed to load the dll from [c:\Users\marek\AppData\Roaming\Code\User\globalStorage\ms-vsliveshare.vsliveshare\dotnet-3.1.1\host\fxr\3.1.1\hostfxr.dll], HRESULT: 0x800700C1
The library hostfxr.dll was found, but loading it from c:\Users\marek\AppData\Roaming\Code\User\globalStorage\ms-vsliveshare.vsliveshare\dotnet-3.1.1\host\fxr\3.1.1\hostfxr.dll failed
  - Installing .NET Core prerequisites might help resolve this problem.
     http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
. Please check the diagnostic logs for more information.
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.ThrowExceptionOnConnectionFailure(Int32 connTimeout)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.DiscoverTests(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler)
```

This looks like VS Code's Live Share extension is getting in the way for some reason. It packs it's own runtime? And that runtime is still 3.1.1xx, which is causing issues. Would there be a way to bypass this interference?

**Comment by wli3** [comment] 2020-04-08 20:36
_From @franck-schmidlin on Monday, March 30, 2020 2:39:01 PM_

I've hit a similar issue which I was only able to resolve by removing the live share extension :-(

**Comment by nohwnd** [comment] 2020-04-09 15:57
@mareklinka this looks like the live share added something to your PATH, and possibly the installation in that path is broken. So now testhost / console is trying to find and run the dotnet in liveshare. 

Please post result of `dotnet --info`.

**Comment by mareklinka** [comment] 2020-04-09 16:17
I checked the path and live share doesn't seem to be affecting it. It would also be rather strange as the extension installs without admin privileges so it shouldn't be possible to modify the path from there.

`dotnet --info` looks normal:
```
OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.201\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  3.1.201 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

However, I managed to catch a glimpse of the culprit, I think. Under certain circumstances (I ahven't been able to repro this reliably so far), this is what VSCode's child process running the dotnet commands ends up with:

![image](https://user-images.githubusercontent.com/7479226/78916714-3157be00-7a8e-11ea-92f0-98279795667d.png)

The value in that variable points to the runtime that comes with Live Share.This environment variable is not system-wide so I assume this only gets injected sometimes by the live share extension.

**Comment by mareklinka** [comment] 2020-04-09 16:19
To clarify, the DOTNET_ROOT variable is not there most of the time and those times everything works without issues. If the variable is present, it points to the wrong runtime and causes the observed error.

**Comment by nohwnd** [comment] 2020-04-09 16:39
> . It would also be rather strange as the extension installs without admin privileges so it shouldn't be possible to modify the path from there.

This assumption is not correct. 🙂 PATH is set on system, user and process level. Non-elevated processes can set the path on the *user* and process level. But I don't think it matters much.

Additionally processes inherit env variables from their parent, so that is what you see. As for where the variable comes from is the question. Could you start a test that will wait for a while (say 20s) and then in Process Explorer find the process running the test, and walk up the tree of processes until you DON'T see the variable being defined.

**Comment by mareklinka** [comment] 2020-04-09 16:49
> 
> 
> > . It would also be rather strange as the extension installs without admin privileges so it shouldn't be possible to modify the path from there.
> 
> This assumption is not correct. 🙂 PATH is set on system, user and process level. Non-elevated processes can set the path on the _user_ and process level. But I don't think it matters much.

Right, of course, I assumed you originally meant the system-persisted PATH.

At any rate, I have a process tree like this:
![image](https://user-images.githubusercontent.com/7479226/78919657-8695ce80-7a92-11ea-9717-0100e08cfcf2.png)

The first process with the DOTNET_ROOT variable seems to be VSCode's extension host process:
![image](https://user-images.githubusercontent.com/7479226/78919716-98777180-7a92-11ea-948e-3ffc4f1bcc76.png)

And then of course all the processes launched from the extension host inherit the variable.

**Comment by nohwnd** [comment] 2020-04-09 16:58
Could you post the whole command line of this process and also the one above it (the one that does not have the dotnet_root) please?

**Comment by mareklinka** [comment] 2020-04-09 17:00
The extension host (with variable):
`"C:\Program Files\Microsoft VS Code\Code.exe" --inspect-port=0 "c:\Program Files\Microsoft VS Code\resources\app\out\bootstrap-fork" --type=extensionHost`

Parent:
`"C:\Program Files\Microsoft VS Code\Code.exe" --type=renderer --disable-color-correct-rendering --field-trial-handle=1700,11397253229512069791,10254540765277873455,131072 --disable-features=LayoutNG,PictureInPicture,SpareRendererForSitePerProcess --lang=en-US --standard-schemes --secure-schemes=vscode-resource --bypasscsp-schemes --cors-schemes=vscode-resource --fetch-schemes=vscode-resource --service-worker-schemes --app-user-model-id=Microsoft.VisualStudioCode --app-path="C:\Program Files\Microsoft VS Code\resources\app" --node-integration --webview-tag --no-sandbox --no-zygote --background-color=#1f2430 --device-scale-factor=1.25 --num-raster-threads=4 --enable-main-frame-before-activation --service-request-channel-token=15901080703558785554 --renderer-client-id=5 --no-v8-untrusted-code-mitigations --mojo-platform-channel-handle=2464 /prefetch:1`

**Comment by mareklinka** [comment] 2020-04-09 17:14
So it looks like the Live Share extension, when booting, is setting the DOTNET_ROOT variable on the extension host process. I guess this makes sense - it needs dotnet runtime to function and there is no guarantee that the local system has the runtime installed globally.

The unfortunate side-effect of this is that is affects all the down-stream processes.

The upside here is that I can work around this in my own extension - I'll just remove the variables before starting my `dotnet test`.

**Comment by nohwnd** [comment] 2020-04-09 18:59
Rather than removing it, I would copy it from the user context if defined and if possible. That way it stays set to the value the user defined.

**Comment by nohwnd** [comment] 2020-04-09 19:00
Imho this is work as designed and I can close this? 🙂

**Comment by mareklinka** [comment] 2020-04-09 19:01
Yeah, I'll need to explore the options available, worst case I'll expose this for the user to control.. Thanks for pointing me in the right direction with this.

**Closed** 2020-04-09 19:05 UTC

**Comment by nohwnd** [comment] 2020-04-09 19:06
Thanks for reaching out. And good luck :)
