### ISSUE TITLE
Assembly.GetEntryAssembly() returns null during integration tests when targeting net462

### ISSUE THREAD

**Issue by livarcocc** [Microsoft/vstest#649] opened 2017-03-22 15:35 UTC
_From @nphmuller on March 22, 2017 13:5_

I'm not sure which repository this belongs in, so apologies in advance if it's in the wrong one.

I use Microsoft.AspNetCore.TestHost in a dedicated project for integration tests, which has a reference to the to be tested project (an Mvc Core API).

The following problem occurred after migrating from project.json to MsBuild.

In my startup I have many dependencies that call `Assembly.GetEntryAssembly()`. 
For example: `AutoMapper`, `SeriLog` and  `Microsoft.Extensions.DependencyModel.DependencyContext.Default` all call it internally.

In the project.json structure GetEntryAssembly() returned a reference to the test runner assembly (for me dotnet-test-xunit.exe). Now with the msbuild project structure it returns null. This makes all above dependencies throw an exception.
This happens both with MsTest and xUnit.
This happens only when targeting the full framework (e.g. net462). When targeting netcoreapp, GetEntryAssemby() returns an actual (not null) value.

Am I doing something wrong? Because according to [the officical docs](https://docs.microsoft.com/en-us/aspnet/core/testing/integration-testing) this is the right way. And in the old project style this worked perfectly.

### Sample
The code described in these steps can be found [here](https://github.com/nphmuller/MsBuildGetCallingAssembly/tree/master).
[This branch](https://github.com/nphmuller/MsBuildGetCallingAssembly/tree/WorkAround) includes also includes the workaround.

### Full steps

We need 2 projects: The MVC API and the test project.

#### API:
1. Run `dotnet new webapi`
2. Edit the csproj file to target both netcoreapp1.1 net462 (`<TargetFrameworks>netcoreapp1.1;net462</TargetFrameworks>`)
2. Now add the following code to `Startup.cs` in any method (for example, the constructor):
``` c#
// This returns null during the test when targeting net462.
var entryAssembly = System.Reflection.Assembly.GetEntryAssembly();
// This line crashes.
// It can be replaced by any dependency that calls GetEntryAssembly() internally.
var depModel = Microsoft.Extensions.DependencyModel.DependencyContext.Default;
```
3. Verify that the api starts correctly:
`dotnet restore && dotnet run -f netcoreapp1.1`
`dotnet restore && dotnet run -f net462`

#### Test:
1.  Run `dotnet new xunit`
2. Replace the content of the csproj file with the following:
``` xml
<Project Sdk="Microsoft.NET.Sdk"><Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netcoreapp1.1;net462</TargetFrameworks>
  </PropertyGroup>
  
  <!-- Without this appsettings.json cannot be found by Startup.cs -->
  <ItemGroup>
    <Content Include="..\Api\appsettings.json">
      <Link>appsettings.json</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Api\Api.csproj" />
    
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
    <PackageReference Include="xunit" Version="2.2.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.2.0" />
    
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="1.1.1" />
  </ItemGroup>

</Project>
```
3. Open UnitTest1.cs and add the following code to Test1()
``` c#
var server = new Microsoft.AspNetCore.TestHost.TestServer(
    new Microsoft.AspNetCore.Hosting.WebHostBuilder().UseStartup<Api.Startup>());
```
4. Run the intergrations tests:
This one succeeds: `dotnet restore && dotnet test -f netcoreapp1.1`.
This one fails: `dotnet restore && dotnet test -f net462`.

## Expected  behavior
`dotnet restore && dotnet test -f netcoreapp1.1` should succeed and the test should pass.
`dotnet restore && dotnet test -f net462`  should succeed and the test should pass.

## Actual behavior
`dotnet restore && dotnet test -f netcoreapp1.1` succeeds and the test passes
`dotnet restore && dotnet test -f net462` fails with a NullReferenceException.

## Workaround
The work around is really ugly and involves reflection. I've taking it from [this](http://stackoverflow.com/a/21888521/5473409) StackOverflow answer.

Call SetEntryAssembly() before creating the TestServer object.
``` c#
        /// <summary>
        /// Use as first line in ad hoc tests (needed by XNA specifically)
        /// </summary>
        public static void SetEntryAssembly()
        {
#if NET462
            SetEntryAssembly(System.Reflection.Assembly.GetCallingAssembly());
#endif
        }

        /// <summary>
        /// Allows setting the Entry Assembly when needed.
        /// Use AssemblyUtilities.SetEntryAssembly() as first line in XNA ad hoc tests
        /// </summary>
        /// <param name="assembly">Assembly to set as entry assembly</param>
        public static void SetEntryAssembly(System.Reflection.Assembly assembly)
        {
#if NET462
            AppDomainManager manager = new AppDomainManager();
            FieldInfo entryAssemblyfield = manager.GetType().GetField("m_entryAssembly", BindingFlags.Instance | BindingFlags.NonPublic);
            entryAssemblyfield.SetValue(manager, assembly);

            AppDomain domain = AppDomain.CurrentDomain;
            FieldInfo domainManagerField = domain.GetType().GetField("_domainManager", BindingFlags.Instance | BindingFlags.NonPublic);
            domainManagerField.SetValue(domain, manager);
#endif
        }
```

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0)

Product Information:
 Version:            1.0.0
 Commit SHA-1 hash:  e53429feb4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0
```

_Copied from original issue: dotnet/cli#6108_

**Comment by codito** [comment] 2017-03-23 04:31
@nphmuller can you please try test run with appdomains disabled in [xunit.runner.json](https://xunit.github.io/docs/configuring-with-json.html) (`appDomain`: `denied`)?

For desktop targets, test projects are library (in the msbuild world). The test framework adapters create an appdomain for loading test projects, and since the test project is library, `AppDomain.SetExecuteAssembly` is not called. Hence `GetEntrypointAssembly()` returns null.

**Comment by nphmuller** [comment] 2017-03-23 11:29
Makes sense, because in the project.json structure the test runner was an executable (dotnet-test-xunit.exe).

Tried it and it works for this specific issue, but it also seems to have some side-effects.

After the line `var server = new Microsoft.AspNetCore.TestHost.TestServer(...)` I run `var client = server.CreateClient()`. 
This line runs fine without `appDomain: denied`, even breakpoints work in debugging etc. But after setting `appDomain: denied`, the code still compiles fine but I get a `MissingMethodException` for `CreateClient()`. Strange thing is that breakpoints completely stop working too, even for the lines before `CreateClient()`. After removing `var client = server.CreateClient()` the breakpoints start working again.

**Comment by codito** [comment] 2017-03-31 17:28
> But after setting appDomain: denied, the code still compiles fine but I get a MissingMethodException for CreateClient(). Strange thing is that breakpoints completely stop working too, even for the lines before CreateClient(). After removing var client = server.CreateClient() the breakpoints start working again.

@natemcmaster @NTaylorMullen any idea if `CreateClient` requires an appdomain?

**Comment by NTaylorMullen** [comment] 2017-03-31 17:34
> @natemcmaster @NTaylorMullen any idea if CreateClient requires an appdomain?

It shouldn't. It's more or less just a pas through to creating an http client: https://github.com/aspnet/Hosting/blob/120fec741d3a0f216bada8135ec73cc15f5dbcfb/src/Microsoft.AspNetCore.TestHost/TestServer.cs#L58-L67

**Comment by nphmuller** [comment] 2017-03-31 17:40
@NTaylorMullen That's what I though, plus the code worked fine in the project.json style project.

By the way, can you reproduce the issue? I can extend the code in my sample repo  with the CreateClient call if you'd like me to.

**Comment by natemcmaster** [comment] 2017-03-31 17:46
This looks like https://github.com/dotnet/core-setup/issues/1017

**Comment by DrSensor** [comment] 2018-03-07 09:37
I have a similar problem. However, when I check
```c#
Assembly.GetEntryAssembly().GetTypes()
```
It prints
```txt
Microsoft.VisualStudio.TestPlatform.TestExecutor.UnitTestClient
Microsoft.VisualStudio.TestPlatform.TestHost.Program
Microsoft.VisualStudio.TestPlatform.TestHost.DefaultEngineInvoker
Microsoft.VisualStudio.TestPlatform.TestHost.IEngineInvoker
Microsoft.VisualStudio.TestPlatform.TestExecutor.UnitTestClient+<>c__DisplayClass1_0
Microsoft.VisualStudio.TestPlatform.TestHost.DefaultEngineInvoker+<>c__DisplayClass8_0
Microsoft.VisualStudio.TestPlatform.TestHost.DefaultEngineInvoker+<>c__DisplayClass9_0
```

---
.NET Command Line Tools (2.1.4)
```
Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.4/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```

**Comment by mayankbansal018** [comment] 2018-08-07 08:10
@nphmuller , sorry for getting so late on this. Can you please summarize what is the current ask for this issue? 

From what I can see that it still exists for fullCLR,  as the test adapters load test assemblies in separate appdomain for which the EntryAssembly is not set. It seems the fix here needs to go in individual adapters, is that correct?

**Comment by mayankbansal018** [comment] 2018-08-07 08:31
@nphmuller 
> If I look at the amount of other projects that reference this issue there might be some improvements possible on this side.

I suppose by this you mean on the test adapter end, also what is the user's expectation for GetEntryAssembly() in this scenario. From the various other posts, it seems they need test assembly to be marked as EntryAssembly, which seems fair.

We'll forward this to other test framework owners, & based on the user feedback, they can provide the solution appropriately.

**Closed** 2018-08-08 05:30 UTC
Labels: question
