### ISSUE TITLE
Support test target for desktop msbuild

### ISSUE THREAD

**Issue by pvlakshm** [microsoft/vstest#326] opened 2017-01-09 12:54 UTC
## Description
User should be able to run tests specifying the test target with desktop msbuild. For example
```
> MSBuild testapp.csproj /t:VSTest
```

This target should first build the app and then run tests for all the outputs (similar to how `dotnet test` behaves today).

To get this target, user may need to add a package reference to `Microsoft.NET.Test.Sdk`. This package will include the target and the related task.

Related customer ask: https://github.com/dotnet/sdk/issues/546

**Comment by onovotny** [comment] 2017-01-20 03:56
Until this is done, some projects cannot successfully run tests this way. `dotnet test` cannot execute a test if the `csproj` contains targets that use a desktop based Task. There are many existing useful build tasks that can be used to generate a `netcoreapp` project but they must be run using desktop `msbuild`.

**Comment by tmat** [comment] 2017-02-14 18:15
I don't think ```MSBuild testapp.csproj /t:VSTest``` should force build on the project. If I wanted to build the project I would have used ```/t:Build;VSTest```.

**Comment by tmat** [comment] 2017-02-14 18:16
Also I'd consider calling the target ```Test``` instead of ```VSTest```, to be consistent with ```dotnet test```.

**Comment by onovotny** [comment] 2017-03-08 22:55
Is there a workaround for this? I have a multi-targeted test library that can only be built with desktop msbuild. I want to run tests!

**Comment by tmat** [comment] 2017-03-08 23:47
@onovotny Check this one out:
https://github.com/dotnet/roslyn-tools/blob/master/src/RepoToolset/Test.props
https://github.com/dotnet/roslyn-tools/blob/master/src/RepoToolset/Test.targets

You should be able to use these in your project.

**Comment by tmat** [comment] 2017-03-08 23:48
(the .props file might not be needed)

**Comment by onovotny** [comment] 2017-03-08 23:50
Thanks, will check it out. Do you use anything for Code Coverage? I was using opencover but that seems broken lately and def doesn't support ppdb's or embedded ppdb's yet.

**Comment by onovotny** [comment] 2017-03-08 23:55
@tmat your targets had something that might actually work for me -- after running the build normally with msbuild /t:build, I tried using `dotnet test --no-build`. I think that actually worked! The issue is that I'm using GitVersionTask in some of my projects and those tasks don't yet support coreclr. So once it's built, it doesn't matter.

**Comment by pchalamet** [comment] 2017-10-09 19:10
Looks similar to issue #1155 I raised. Is there any update when "msbuild /t:VSTest" will be able to test both dncore and regular desktop app ? Thanks!

**Comment by pvlakshm** [comment] 2017-11-30 17:43
I have removed the question tag. We will use this item as an input when we take up planning for Q2 of next year.

**Comment by onovotny** [comment] 2018-03-28 21:16
Bump. Using `dotnet test --no-build` no longer works for certain scenarios. Really need a way to invoke the targets via an MSBuild target.

**Comment by onovotny** [comment] 2018-03-28 21:19
I should add that as-of MSBuild 15.6. we can now have SDK's distributed via NuGet, so it should be a lot easier to support adding this as a test sdk out-of-band for both msbuild and dotnet.

**Comment by jnevins-gcm** [comment] 2018-06-06 13:45
Anyone planning to fix this? Building via dotnet msbuild CLI and MSBuild.exe is generally inconsistent.

**Comment by onovotny** [comment] 2018-06-23 18:40
Bump?

**Comment by smadala** [comment] 2018-06-26 08:43
@onovotny We haven't decided when to pick this yet. If you would like to contribute, Let me know I'm happy help you.

**Comment by ViktorHofer** [comment] 2018-11-10 20:38
Bump.

**Comment by shtratos** [comment] 2023-06-21 19:17
is there at least a workaround for this? e.g. can I somehow tell msbuild.exe to import the targets explicitly?

**Comment by MeikTranel** [comment] 2023-09-05 11:47
Y'all should probably close this issue if the future milestone gets removed without a replacement. As much as i'd like to have the feature i'd rather take a set answer on whether its something y'all want to take on.

**Comment by rainersigwald** [comment] 2023-09-06 14:55
@novacole, this is what you're looking at with https://github.com/dotnet/msbuild/pull/9193, right?

**Comment by novacole** [comment] 2023-09-11 17:37
> @novacole, this is what you're looking at with https://github.com/dotnet/msbuild/pull/9193, right?

Yes, that's correct!

**Comment by nohwnd** [comment] 2024-07-09 08:48
This is a new feature and won't be implemented, we are focusing on adding new features to Testing.Platform instead. https://aka.ms/testingplatform

**Closed by nohwnd** 2024-07-09 08:48 UTC
Labels: enhancement, exp: cli
