### ISSUE TITLE
No xunit tests discovered in netcoreapp1.0

### ISSUE THREAD

**Issue by JamesNK** [Microsoft/vstest#576] opened 2017-03-08 04:10 UTC
## Description
No xunit tests discovered in netcoreapp1.0 in VS

## Steps to reproduce
1. Clone https://github.com/JamesNK/Newtonsoft.Json
2. Open Newtonsoft.Json.Roslyn.sln
3. Edit Newtonsoft.Json.Tests.Roslyn.csproj so TargetFrameworks = netcoreapp1.0
4. Run all tests

## Expected behavior
Tests are discovered and run

## Actual behavior
No tests are discovered

## Environment
VS2017 RTM

**Comment by qmfrederik** [comment] 2017-03-08 10:59
I'm seeing a similar issue. No xunit tests are discovered in Visual Studio 2017 RTM. 

In my case:
- The Visual Studio Output window shows the following for Tests: "The given key was not present in the dictionary."
- dotnet test returns: No test discoverer is registered to perform discovery of test cases. Register a test discoverer and try again.
- dotnet test -f netcoreapp1.0 and dotnet test -f net462 (the configs I'm building for) do work.

Do you see something similar? If not, I'll open a separate isuse.

**Comment by smadala** [comment] 2017-03-08 18:51
@JamesNK Able to repo the issue, I can see `[xUnit.net 00:00:01.3004793] Skipping: Newtonsoft.Json.Tests (could not find dependent assembly 'Newtonsoft.Json, Version=10.0.0')` in VS test output panel. 

Looks like issue with `Newtonsoft.Json.Tests.deps.json`, the right version of Newtonsoft.Json not getting added because the csproj file name(`Newtonsoft.Json.Roslyn.csproj`) and assembly  name(`Newtonsoft.Json`) are not same. 

Additional data point, After adding `<PackageReference Include="Newtonsoft.Json" Version="10.0.1-beta1" />` for netcoreapp1.0, Tests are discovered.

**Comment by smadala** [comment] 2017-03-08 18:54
@qmfrederik  can you please provide project or csproj file?

**Comment by qmfrederik** [comment] 2017-03-08 18:55
@smadala Well, in my case the assembly name and project file name are different as well because I have VS2015 and VS2017 projects side-by-side. Is that the root case? In that case, I'm probably seeing the same issue.

**Comment by smadala** [comment] 2017-03-08 19:11
It can be different issue, In case of Newtonsoft.Json, Test platform depends on version 9.1.0, because of that 10.0.0 not getting loaded which we can see in VS test output panel, In your case the log message is different and `dotnet test -f <framework>` works but not `dotnet test`. Please provide csproj/project I can investigate more.

**Comment by JamesNK** [comment] 2017-03-09 10:33
> Additional data point, After adding <PackageReference Include="Newtonsoft.Json" Version="10.0.1-beta1" /> for netcoreapp1.0, Tests are discovered.

Are you sure it's referencing the project output and not download from https://www.nuget.org/packages/Newtonsoft.Json/10.0.1-beta1?

**Comment by smadala** [comment] 2017-03-09 11:02
@JamesNK Found root cause: https://github.com/NuGet/Home/issues/4586, it is fixed in VS 2017 RTM, I have verified it, all tests are running for netcoreapp1.0.
> Are you sure it's referencing the project output and not downloading from https://www.nuget.org/packages/Newtonsoft.Json/10.0.1-beta1?

Yes, it was downloaded from nuget.org, Mentioned it to indicate issue with ProjectReference.

**Comment by JamesNK** [comment] 2017-03-09 12:32
I'm using the RTM and it doesn't work

**Comment by qmfrederik** [comment] 2017-03-09 13:13
@smadala Here's an example of a .csproj and the test.props file we use:
[tests.zip](https://github.com/Microsoft/vstest/files/830900/tests.zip)

I've actually seen VS discover the tests briefly, but now once again, they are not discovered, I get the "The given key was not present in the dictionary." error in the Test output window and dotnet test doesn't discover any tests.

**Comment by smadala** [comment] 2017-03-09 14:22
@JamesNK can you please provide VS build number?

**Comment by JamesNK** [comment] 2017-03-10 02:33
> I'm using the RTM and it doesn't work

I retried and it is now working. My issue is fixed. Feel free to close when everything else is resolved.

**Comment by smadala** [comment] 2017-03-10 10:10
@qmfrederik I couldn't find any issue with package reference in test project. can you please share log files(`dotnet test --diag:log.txt`) log.txt and log.host.<timestamp>.txt.

**Comment by qmfrederik** [comment] 2017-03-10 13:28
@smadala Here are the logs, I've ran dotnet test with and without the -f netcoreapp1.1 argument.

* [log.host.17-03-10_14-26-23_57266_5.txt](https://github.com/Microsoft/vstest/files/834021/log.host.17-03-10_14-26-23_57266_5.txt)
* [log.txt](https://github.com/Microsoft/vstest/files/834023/log.txt)
* [log-netcoreapp11.txt](https://github.com/Microsoft/vstest/files/834024/log-netcoreapp11.txt)
* [log-netcoreapp11.host.17-03-10_14-26-45_44484_5.txt](https://github.com/Microsoft/vstest/files/834022/log-netcoreapp11.host.17-03-10_14-26-45_44484_5.txt)

**Comment by qmfrederik** [comment] 2017-03-10 13:28
@JamesNK Do you know what fixed the issue for you?

**Comment by qmfrederik** [comment] 2017-03-10 13:40
@smadala Quick update: my .csproj files did not specify the `RuntimeIdentifier` property, only `RuntimeIdentifiers`, because I target multiple runtimes.

I've added a `RuntimeIdentifier` property and it _looks_ like the tests are being discovered in Visual Studio. `dotnet test` still does not, though.

**Comment by JamesNK** [comment] 2017-03-11 10:12
> @JamesNK Do you know what fixed the issue for you?

Nope!

**Comment by ravisankar-krinik** [comment] 2017-03-24 23:01
Look at this 
http://www.michael-whelan.net/the-state-of-dotnet-core-testing-today/
x-unit runs in VS 2015

Install-Package xunit -Pre
Install-Package dotnet-test-xunit -Pre

**Comment by smadala** [comment] 2017-04-10 13:29
@qmfrederik can you please share sample project which repro the issue?

**Comment by smadala** [comment] 2017-05-29 05:02
Closing this because no repro.

**Closed by smadala** 2017-05-29 05:02 UTC
Labels: bug, external
