### ISSUE TITLE
Pass a variable into Azure pipeline

### ISSUE THREAD

**Issue by marcosadeghi** [Microsoft/vstest#1857] opened 2018-12-04 19:59 UTC
As part of a test I'm logging in a user into Live & retrieving a bearer token. The work flow to retrieve this token is not 100 reliable so I don't want each test that runs as part of a pipeline to need to make this call.

What I'd like to do is in my first test make this call, retrieve the token & then save it to a parameter in the pipeline that other test can read from. Looking at the vstest task item it's not apparent to me if this scenario is supported or how to do this. Any pointers are appreciated. 

Cheers

**Comment by singhsarab** [comment] 2018-12-05 11:17
There is such support in the VSTest task.

I have a bunch of concerns.
1) If the workflow to retrieve the token in not reliable, how do you guarantee that it will work the first time?
2) If you really want to try this, can't you do this retrieving in the ClassInitialize of the TestClass and save this token as one of the TestContext properties or static variable in the testclass, where testclass contains all these tests that need this token?

**Comment by marcosadeghi** [comment] 2018-12-05 15:24
Thanks for the quick response 

1) It’s reliable enough. I simply want to reduce the number of times we need to call this method.
2) For now, I’m running one test per VStest task in the pipeline/release & want the pipeline to be the ‘container’ holding the global variable (making it available to the other vstest tasks in the release/pipeline) not the test class. If I was running all tests inside a dll I could source the token & make it available in the class init but that’s not my use case at the moment.

**Comment by marcosadeghi** [comment] 2018-12-05 18:44
So, if making the variable available class wide is the only option I have, that means I need to have all my tests in the same class. My tests need to follow a particular sequence. How do I enforce a sequence?

I don't see how I can pass in a reference to a playlist to the vstest task.

**Comment by prawalagarwal** [comment] 2018-12-06 06:37
@marcosadeghi There is one more option. If you are comfortable writing your token to a file during the duration of the build, then you can use the Env var Agent.TempDirectory to write to. This directory is cleared at the end of each build and resides inside the agent folder (_work\_temp).
In case you don't like this approach, to run your tests sequentially, use ordered testing. [https://damsteen.nl/blog/2016/06/05/ordered-tests-with-nunit-mstest-xunit-pt1](url)

**Comment by marcosadeghi** [comment] 2018-12-06 19:49
Thanks Prawal. Creating a new ordered test though I get a warning: MSTest V2 based tests cannot be used in an ordered test. 

I just did a quick test & was not able to launch my tests in a playlist via command line. Is that supported or is my command line wrong?
vstest.console.exe "C:\source\repos\Azure\<removed>\<removed>\PostDeploymentTests.playlist" /Settings:"C:\source\repos\Azure\<removed>\<removed>\test.runsettings" /TestAdapterPath:"."

**Comment by nigurr** [comment] 2018-12-17 06:43
@marcosadeghi playlist is not supported from command line. There are multiple ways to solve this problem
1. If your tests are using MsTest v1 framework, Use ordered tests as mentioned above 
2. If your tests are using MsTest v2 framework, Use [AssemblyInitialize] method to read the token once and use it through out the execution.
3. Alternatively you can dynamically pass this parameter using "runsettings" and access the token in your tests via TestContext - https://blogs.msdn.microsoft.com/devops/2015/09/04/supplying-run-time-parameters-to-tests/

This is specific problem to test infra is setup and leveraging these functionalities. Closing this issue as it's not a bug/gap in the platform.

**Closed by nigurr** 2018-12-17 06:43 UTC
