### ISSUE TITLE
Test invoking UI thread, fail with "System.InvalidOperationException: The calling thread must be STA, because many UI components require this."

### ISSUE THREAD

**Issue by mayankbansal018** [Microsoft/vstest#390] opened 2017-01-27 09:15 UTC
## Description
> Test methods cannot invoke UI

## Steps to reproduce
run test method, that is supposed to invoke UI

## Expected behavior
The test should pass

## Actual behavior
The test fails with above mentioned error

**Comment by saikrishnav** [comment] 2017-01-31 07:57
FYI - .Net Core does not have “ApartmentState” API to set it on the thread (Netstandard 1.5). Therefore, MTA setting is by design for .Net core at this point. For desktop, I am fixing it using #ifdef

**Comment by saikrishnav** [comment] 2017-01-31 15:04
Fixed in commit: https://github.com/Microsoft/vstest/commit/f4cd6dccbc332500c1986eedf3c9d491f1e98cf4

**Closed by saikrishnav** 2017-01-31 15:04 UTC
Labels: bug, exp: testimpact

**Comment by smadala** [comment] 2017-08-08 12:54
[Doc](https://github.com/Microsoft/vstest-docs/blob/master/docs/configure.md#execution-thread-apartment-state). ExecutionThreadApartmentState can be used for .NET Framework. Best way to run UI tests is use adapter customer attributes specified in above doc.
