### ISSUE TITLE
Unable to profile any unit tests

### ISSUE THREAD

**Issue by niemyjski** [Microsoft/vstest#461] opened 2017-02-08 19:00 UTC
I'm seeing lots of issues with the following project https://github.com/exceptionless/foundatio

I'm unable to discover most unit tests but even more importantly trying to profile any unit tests fails quick with some cryptic errors (Right click specific test and select profile in the test runner). I shut down my vm, but if you need specific errors let me know.

**Comment by codito** [comment] 2017-02-11 02:55
@niemyjski profile tests is not implemented for netcore projects yet. This support requires datacollectors infrastructure (#309). It will come post RTW.

/cc @pvlakshm

**Comment by codito** [comment] 2017-03-17 02:13
Closing as duplicate of #617.

**Closed by codito** 2017-03-17 02:13 UTC
Labels: enhancement, exp: ide, question
