### ISSUE TITLE
Enum in DataRow

### ISSUE THREAD

**Issue by nvineeth** [Microsoft/vstest#1683] opened 2018-07-11 06:01 UTC
## Description
If an Enum is passed in DataRow, then the following error is thrown:
`Message: Error in executing test. No result returned by extension. If using extension of TestMethodAttribute then please contact vendor.`

This error is seen in Release but not in Debug.

## Steps to reproduce
* Create a C# Unit Test csproj for Universal Windows.
* Add a test case which accepts an enum as one of the arguments.
* Add several DataRow attributes with enum.

## Expected behavior
* Should run the test case fine

## Actual behavior
Test case fails with `Message: Error in executing test. No result returned by extension. If using extension of TestMethodAttribute then please contact vendor.` 

## Diagnostic logs
> Please share test platform diagnostics logs. Instructions to collect logs are [here](https://github.com/Microsoft/vstest-docs/blob/master/docs/diagnose.md#test-platform-diagnostics).  
> The logs may contain test assembly paths, kindly review and mask those before sharing.

## Environment
VS 15.7.4 
The csproj file has the following test references:

```
    <PackageReference Include="Microsoft.NETCore.UniversalWindowsPlatform">
      <Version>6.1.5</Version>
    </PackageReference>
    <PackageReference Include="MSTest.TestAdapter">
      <Version>1.2.1</Version>
    </PackageReference>
    <PackageReference Include="MSTest.TestFramework">
      <Version>1.2.1</Version>
    </PackageReference>
```

Related Issues : https://github.com/Microsoft/vstest/issues/471

## Workaround
Typecast the enum to int in DataRow, and accept the int in the TestMethod.

**Comment by abhishkk** [comment] 2018-07-18 11:00
@nvineeth 
With above environment details, we are not able to repro the issue. For both debug and release mode, tests are running fine.

Sample code tried:
```
        [TestMethod]
        [DataRow(TraceLevel.Info)]
        [DataRow(TraceLevel.Verbose)]
        public void TestMethod1(TraceLevel traceLevel)
        {
            Assert.AreEqual(traceLevel, TraceLevel.Info);
        }
```

Can you please share a sample repro project where you are able to reproduce the issue?

**Comment by nvineeth** [comment] 2018-07-19 10:08
Hi, 
Here is the code,
```

**Comment by nvineeth** [comment] 2018-07-19 10:11
@abhishkk , the unit test code is as follows:
```C#
        [TestMethod]
        [DataRow("appID", "1.0", "", InvocationStatus.InvalidAppPathParam)]
        public void Test_NullPath(string appID, string appVer, string profileScope,InvocationStatus status)
        {
            var inst = GetInstance();
            Assert.IsNotNull(inst);
            InvocationStatus _status = inst.InvokeClient("appID", "1.0", "", "").AsTask().Result;
            Assert.AreEqual(status, _status);
        }
```

**Comment by mayankbansal018** [comment] 2018-07-23 11:32
@nvineeth We tried reproducing this locally, but failed. Can you try moving to latest mstest adapter/framework. Also can you run these tests via CLI, & enable diag logs https://github.com/Microsoft/vstest-docs/blob/master/docs/diagnose.md#collect-traces-using-command-line

CLI command : vstest.console <path_to_appxrecipe>
If possible can you also share sample repro project?

**Comment by mayankbansal018** [comment] 2018-07-25 10:11
@nvineeth for UWP project the Microsoft.Net.Test.SDK doesn't bring any dependency apart from those of NewtonSoft.Json. Hence you don't need to update this SDK nuget.

Since the error doesn't happen from CLI, it means that Enum is not the issue here.
Can you enable diagnostics logs for vstest.console via "https://github.com/Microsoft/vstest-docs/blob/master/docs/diagnose.md#collect-trace-using-config-file", at path "_<vs_install\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe.config_>", & restart VS

Please share the log files for both vstest.console, & UWP Test App.

**Comment by nvineeth** [comment] 2018-07-25 12:09
hi @mayankbansal018 , wanted to share further information before sharing the diagnostic info, may the follow will give clues to you:
- From the CLI, the Debug|x64 build of appx runs all cases however, for the Release|x64 build vstest.console.exe shows the message that no unit tests could be discovered.
- From VS 2017 , the build of Debug|x64 does not give any warning, however Release|x64 throws a lot of warnings like this :
```
1>C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\microsoft.net.native.compiler\1.7.3\tools\Microsoft.NetNative.targets(697,5): warning : ILTransform : warning ILT0010: Could not find assembly 'System.Xml.XPath, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' referenced by 'Microsoft.VisualStudio.TestPlatform.ObjectModel'.
1>C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\microsoft.net.native.compiler\1.7.3\tools\Microsoft.NetNative.targets(697,5): warning : ILTransform : warning ILT0010: Could not find assembly 'System.Xml.XPath.XmlDocument, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' referenced by 'Microsoft.VisualStudio.TestPlatform.ObjectModel'.
1>C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\microsoft.net.native.compiler\1.7.3\tools\Microsoft.NetNative.targets(697,5): warning : ILTransform : warning ILT0010: Could not find assembly 'System.Xml.XPath.XmlDocument, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' referenced by 'Microsoft.VisualStudio.TestPlatform.Common'.
1>C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\microsoft.net.native.compiler\1.7.3\tools\Microsoft.NetNative.targets(697,5): warning : ILTransform : warning ILT0010: Could not find assembly 'System.Xml.XPath, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' referenced by 'Microsoft.VisualStudio.TestPlatform.Common'.
1>C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\microsoft.net.native.compiler\1.7.3\tools\Microsoft.NetNative.targets(697,5): warning : ILTransform : warning ILT0010: Could not find assembly 'System.Console, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' referenced by 'Microsoft.TestPlatform.CoreUtilities'.
1>C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\microsoft.net.native.compiler\1.7.3\tools\Microsoft.NetNative.targets(697,5): warning : ILTransform : warning ILT0010: Could not find assembly 'System.Diagnostics.FileVersionInfo, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' referenced by 'Microsoft.TestPlatform.CoreUtilities'.

....

1>C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\microsoft.net.native.compiler\1.7.3\tools\Microsoft.NetNative.targets(697,5): warning : ILTransform : warning ILT0010: Could not find assembly 'System.Xml.XPath, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' referenced by 'Microsoft.VisualStudio.TestPlatform.ObjectModel'.
1>C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\microsoft.net.native.compiler\1.7.3\tools\Microsoft.NetNative.targets(697,5): warning : ILTransform : warning ILT0010: Could not find assembly 'System.Xml.XPath.XmlDocument, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' referenced by 'Microsoft.VisualStudio.TestPlatform.ObjectModel'.
1>C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\microsoft.net.native.compiler\1.7.3\tools\Microsoft.NetNative.targets(697,5): warning : ILTransform : warning ILT0010: Could not find assembly 'System.Xml.XPath.XmlDocument, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' referenced by 'Microsoft.VisualStudio.TestPlatform.Common'.
1>C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\microsoft.net.native.compiler\1.7.3\tools\Microsoft.NetNative.targets(697,5): warning : ILTransform : warning ILT0010: Could not find assembly 'System.Xml.XPath, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' referenced by 'Microsoft.VisualStudio.TestPlatform.Common'.
1>C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\microsoft.net.native.compiler\1.7.3\tools\Microsoft.NetNative.targets(697,5): warning : ILTransform : warning ILT0010: Could not find assembly 'System.Console, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' referenced by 'Microsoft.TestPlatform.CoreUtilities'.
1>C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\microsoft.net.native.compiler\1.7.3\tools\Microsoft.NetNative.targets(697,5): warning : ILTransform : warning ILT0010: Could not find assembly 'System.Diagnostics.FileVersionInfo, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' referenced by 'Microsoft.TestPlatform.CoreUtilities'.
1>C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\microsoft.net.native.compiler\1.7.3\tools\Microsoft.NetNative.targets(697,5): warning : ILTransform : warning ILT0010: Could not find assembly 'System.Xml.XPath.XmlDocument, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' referenced by 'Microsoft.TestPlatform.Utilities'.
...(lots of similar warnings)
```

I think this is the reason for failure, how can I fix the `Could not find assembly 'System.Xml.XPath, Version=4.0.1.0, ` Issue? Addressing this will probably eliminate this error.

**Comment by mayankbansal018** [comment] 2018-07-25 12:17
Hi @nvineeth , the warnings you are getting are known, which come in release mode, when ".netnative tool chain" compilation option is enabled. This however should not cause test failure.

For CLI "release" can you please use ".appxrecipe" as input, before doing so, please make sure that you have uninstalled the TestApp

**Comment by nvineeth** [comment] 2018-07-25 14:01
the msbuild is not generating appxrecipe, I am using the following command `msbuild /p:configuration=Release;platform=x64 /verbosity:minimal Solution.sln`

If I can at least run the Release unit tests via CLI it will be helpful.
Can you pls help me with it?

**Comment by mayankbansal018** [comment] 2018-07-30 15:16
Please comment if the issue still repros'

**Closed by mayankbansal018** 2018-07-30 15:16 UTC
Labels: need-repro, question

**Comment by SGmuwa** [comment] 2019-09-29 18:43
https://github.com/SGmuwa/Information-Security-7-semester/blob/github.com/Microsoft/vstest/issues/1683/UnitTestProject1/UnitTest1.cs#L12
My tests work weird...
## Release
![image](https://user-images.githubusercontent.com/6484464/65837558-75a91b00-e301-11e9-84c1-526e8eef1454.png)
## Debug
![image](https://user-images.githubusercontent.com/6484464/65837594-0253d900-e302-11e9-8336-bbb8944ba252.png)
## Tests
![image](https://user-images.githubusercontent.com/6484464/65837604-1e577a80-e302-11e9-9bc4-9bc8244714d8.png)
