### ISSUE TITLE
Illegal character in Path error.

### ISSUE THREAD

**Issue by harshjain2** [Microsoft/vstest#1132] opened 2017-09-26 11:30 UTC
## Description
Getting "Illegal character in Path error".

Command :
>C:\Users\user\Desktop>"C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe"  "C:\Users\User\source\repos\UnitTestProject3\UnitTestProject3\bin\Debug\net46\UnitTestProject3.dll" /testadapterpath:"C:\Users\harjain\source\repos\UnitTestProject3\UnitTestProject3\bin\Debug\net46\" /settings:RS.runsettings /inisolation

Output :
>	Microsoft (R) Test Execution Command Line Tool Version 15.5.0-preview-20170923-02
>	Copyright (c) Microsoft Corporation.  All rights reserved.
>	
>	The path 'C:\Users\user\source\repos\UnitTestProject3\UnitTestProject3\bin\Debug\net46\" /settings:RS.runsettings /inisolation' specified in the 'TestAdapterPath' is invalid. Error: Illegal characters in path.

Expected Output :
Tests should execute successfully.

**Comment by singhsarab** [comment] 2017-10-25 09:45
This seems to be fixed in the latest bits as I am not able to reproduce. Closing.

**Closed by singhsarab** 2017-10-25 09:45 UTC
Labels: bug, exp: cli
