### ISSUE TITLE
Add support for dotnet test --collect:"Code Coverage" for non VS-Enterprise users

### ISSUE THREAD

**Issue by suryagh** [Microsoft/vstest#1312] opened 2017-12-01 00:04 UTC
## Description
Can we have code coverage for non-enterprise Visual Studio Users?

`dotnet test --collect:"Code Coverage"` only works if Visual Studio Enterprise is installed.

Ability to check code coverage is important for any application development. So, can we please have this prioritized?

Thanks!

**Comment by AdrienneCohea** [comment] 2018-01-12 17:44
I'm trying to make the argument at my company to migrate to .NET Core. I can't in good conscience make this argument though because we would be losing code coverage in our CI/CD pipeline.

In my opinion, the enhancement label should be removed for this issue. Code coverage is an integral part of tooling. It is not an enhancement. Build tooling is not feature-complete without code coverage.

**Comment by pvlakshm** [comment] 2018-04-13 12:44
We are starting on enabling code coverage via `dotnet test` as described in this [RFC](https://github.com/Microsoft/vstest-docs/blob/master/RFCs/0021-CodeCoverageForNetCore.md).

**Comment by smadala** [comment] 2018-08-09 13:11
Dupe of https://github.com/Microsoft/vstest/issues/981 . Installing VS 15.8(non-enterprise also) should fix this issue.

**Closed by smadala** 2018-08-09 13:11 UTC
Labels: backlog, enhancement, exp: coverage, exp: dotnet-cli, pri: 1
