### ISSUE TITLE
`dotnet test` fails to find .NET Core 3.0 SDK when installed from script to custom location 

### ISSUE THREAD

**Issue by martincostello** [microsoft/vstest#2189] opened 2019-09-21 16:16 UTC
## Description

`dotnet test` fails to find .NET Core SDK 3.0 when installed from `https://dot.net/v1/dotnet-install.ps1` into a custom install location with `-NoPath` in Azure DevOps on Windows.

This does not appear to be an issue with AppVeyor, Travis CI or Azure DevOps on Linux and macOS.

This worked with various versions of the .NET Core SDK up to and including 3.0.0 RC1, but appears to have been broken in 3.0.0 with 16.3.0.

Looking at the diff between `16.3.0` and `16.3.0-preview-20190828-03`, this might be a regression caused by the changes in https://github.com/microsoft/vstest/pull/2161.

## Steps to reproduce

Issue can be observed in this Pull Request from commit `612e825179e4b3435613926b513a7b9a07132753`: https://github.com/justeat/httpclient-interception/pull/127

## Expected behavior

Tests run.

## Actual behavior

`dotnet test` fails with:

```ps
Test run for d:\a\1\a\JustEat.HttpClientInterception.Tests.dll(.NETCoreApp,Version=v3.0)
Microsoft (R) Test Execution Command Line Tool Version 16.3.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
Testhost process exited with error: It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '3.0.0' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet
  - Installing .NET Core prerequisites might help resolve this problem:
      https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
  - The following versions are installed:
      1.0.4 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      1.0.5 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      1.0.7 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      1.0.8 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      1.0.9 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      1.0.10 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      1.0.11 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      1.0.12 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      1.0.13 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      1.0.14 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      1.0.15 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      1.0.16 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      1.1.1 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      1.1.2 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      1.1.4 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      1.1.5 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      1.1.6 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      1.1.7 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      1.1.8 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      1.1.9 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      1.1.10 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      1.1.11 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      1.1.12 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      1.1.13 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.0.0 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.0.3 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.0.5 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.0.6 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.0.7 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.0.9 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.0 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.1 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.2 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.3 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.4 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.5 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.6 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.7 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.8 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.9 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.12 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.2.0 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.2.1 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.2.2 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.2.3 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
. Please check the diagnostic logs for more information.
Results File: D:\a\1\s\tests\HttpClientInterception.Tests\TestResults\VssAdministrator_fv-az635_2019-09-21_15_13_42.trx
Test Run Aborted.
```

## Diagnostic logs

See [here](https://dev.azure.com/justeatoss/httpclient-interception/_build/results?buildId=163&view=logs&jobId=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&taskId=ebb4541d-067d-557a-31a9-bfa53beb4d16&lineStart=115&lineEnd=116&colStart=1&colEnd=1).

## Environment

Azure DevOps Visual Studio 2019 image.

**Comment by martincostello** [comment] 2019-09-23 09:32
Looks like this issue is related to x86 vs. x64, as it seems that a 32-bit PowerShell script will install the x64 version of .NET (because it looks at the machine's architecture), then the SDK will try and use 32-bit version of the SDK (which isn't installed) and then fail.

**Comment by vagisha-nidhi** [comment] 2019-09-25 10:02
@martincostello Can you please provide more information on what is the exact scenario and how to repro this?
1. Install latest dotnet sdk 3.0.100 from `https://dot.net/v1/dotnet-install.ps1` into a custom location with `-NoPath`:  `.\dotnet-install.ps1 -InstallDir e:\custom_dotnet -NoPath -Version 3.0.100`
2. Is this happening when the sdk installed is x86? (Install the x86 sdk by specifying `-Architecture x86` as @tannergooding suggested)
3. What is the target platform of the unit test project(AnyCPU, x86, x64)? 
4. Update the Microsoft.NET.Test.Sdk to 16.3.0 stable

Let me know if I am missing anything.

**Comment by tannergooding** [comment] 2019-09-27 12:14
@vagisha-nidhi, I've simplified a repro to:
1. Ensure you have a clean machine without .NET Core already installed
  A. the Azure DevOps 'Microsoft-hosted' agents available for OSS seem to fit the bill
2. Download the 32-bit .NET Core SDK for 3.0.100
  A. This could be downloaded manually from get.dot.net
  B. This could be downloaded using the `dotnet-install.ps1` script and explicitly specifying `-Architecture x86`
3. Create a unit test project targeting `netcoreapp3.0` with a simple test
  A. This defaults to AnyCPU. I did not check if explicit x86 reproduces, as I need `AnyCPU`
4. Reference the `Microsoft.NET.Test.Sdk, Version=16.3.0`
5. Run `dotnet test`

You can optionally change the `Microsoft.NET.Test.Sdk` version to the last public preview (`16.3.0-preview-20190828-03`) and see that running `dotnet test` works as expected.

**Comment by jabberhams** [comment] 2019-09-27 23:29
I have also encountered this error but through Azure Devops Server (actually, TFS on-prem).  I used [.NET Core Installer Tool Task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer?view=azure-devops) which downloads dotnet-sdk-3.0.100-win-x64.zip and installs (sets PATH) to the build agent folder (\_work\_tool\dncs\3.0.100\x64).  The subsequent `dotnet build` task builds all projects - including the test projects - and completes successfully, but the `dotnet test` task produces the same error at the top of this thread.  No other special configuration of the tests projects themselves but my projects all build to x64.

**Comment by sfalik** [comment] 2019-10-02 23:26
@jabberhams I have the exact same issue

**Comment by shaynevanasperen** [comment] 2019-10-03 10:12
@tannergooding I'm having the same issue. But even when I downgrade to `16.3.0-preview-20190828-03` it fails. This only happens when I run it on TeamCity. When I run the exact same build script on my developer machine, it works fine.

**Comment by unaizorrilla** [comment] 2019-10-09 18:32
I have the same issue on AppVeyor

**Comment by unaizorrilla** [comment] 2019-10-09 19:33
I fix the issue downgrading Microsoft.Net.Test.Sdk 16.3.0 to 16.2.0, if this can help!

**Comment by FeodorFitsner** [comment] 2019-10-10 00:36
Would it be reproducible if .NET Core 3.0 installed with MSI?

**Comment by colotiline** [comment] 2019-11-21 12:00
I've got same issue when run tests for an asp.net core app.

**Error**
```
Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
Testhost process exited with error: It was not possible to find any compatible framework version
The specified framework 'Microsoft.AspNetCore.App', version '3.0.0' was not found.
  - No frameworks were found.
You can resolve the problem by installing the specified framework and/or SDK.
The .NET Core frameworks can be found at:
  - https://aka.ms/dotnet-download
. Please check the diagnostic logs for more information.

Test Run Aborted.
```

**OS**
CentOS 7.

**dotnet --info**
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.101
 Commit:    bc5f8df0f5

Runtime Environment:
 OS Name:     centos
 OS Version:  7
 OS Platform: Linux
 RID:         centos.7-x64
 Base Path:   /usr/share/dotnet/sdk/3.0.101/

Host (useful for support):
  Version: 3.0.1
  Commit:  19942e7199

.NET Core SDKs installed:
  3.0.101 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.NETCore.App 3.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

```

**Test csproj**
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <Nullable>enable</Nullable>
    <WarningsAsErrors>CS8600;CS8602;CS8603;CS8625;CS8604</WarningsAsErrors> 
    <ProjectGuid>{645134b4-30b1-48b1-a82a-c3925bae3bca}</ProjectGuid>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoFixture" Version="4.11.0" />
    <PackageReference Include="coverlet.msbuild" Version="2.7.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.DotNet.Watcher.Tools" Version="2.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="3.0.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.4.0" />
    <PackageReference Include="Moq" Version="4.13.1" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.1">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\app\app.csproj" />
  </ItemGroup>

</Project>
```

**yum list installed | grep dotnet**
```
dotnet-apphost-pack-3.0.x86_64        3.0.1-1                        @packages-microsoft-com-prod
dotnet-host.x86_64                    3.0.1-1                        @packages-microsoft-com-prod
dotnet-hostfxr-3.0.x86_64             3.0.1-1                        @packages-microsoft-com-prod
dotnet-runtime-3.0.x86_64             3.0.1-1                        @packages-microsoft-com-prod
dotnet-runtime-deps-3.0.x86_64        3.0.1-1                        @packages-microsoft-com-prod
dotnet-sdk-3.0.x86_64                 3.0.101-1                      @packages-microsoft-com-prod
dotnet-targeting-pack-3.0.x86_64      3.0.1-1                        @packages-microsoft-com-prod
```

**Comment by snavarropino** [comment] 2019-12-10 08:52
> 
> 
> I fix the issue downgrading Microsoft.Net.Test.Sdk 16.3.0 to 16.2.0, if this can help!

Same issue here after installing visual studio 16.4 (that comes with .Net core 3.1). Downgrading Microsoft.Net.Test.Sdk solved the issue

**Comment by rockfordlhotka** [comment] 2019-12-12 21:52
This SO answer might be relevant

https://stackoverflow.com/questions/59246822/after-updated-visual-studio-2019-to-16-4-0-i-cant-run-tests-with-target-framewo/59282608#59282608

**Comment by drognanar** [comment] 2020-01-23 17:19
Tagging @cvpoienaru

**Comment by nohwnd** [comment] 2020-03-23 11:18
I think we are talking about multiple different issues. First is the inability to find dotnet because it is not in path. And the other is inability to find dotnet of another bitness than the executor because we don't have it installed. 

Both seem to be broken for 16.4.0 but partially fixed in 16.5.0
---

The original issue fails to locate the dotnet 3.0 because it was installed with -noPath, and then likely run as this `C:\dotnet3.0\dotnet.exe test`. This would run the vstestconsole.exe which is netcoreapp2.1 and so it would run just fine. Console would testhost.exe passing on runtime config to use netcoreapp3.0. The test host would try to execute and would run the standard dotnet resolve to find the host -> look into DOTNET_ROOT (probably not defined), look into PATH, look into ProgramFiles. This ended up finding the dotnet in ProgramFiles where only versions up to 2.2 are installed and failed to run. 

--- 

The other issue (the simple repro above), uses one bitness of the console to execute a different bitness of the test host. 

I tried this on the latest and I think it was "fixed" in the meantime by taking the path to dotnet.exe from the parent process if it is dotnet.exe as well. This runs nicely, but does not do what is advertised because the test host ends up running as 32-bitwhile it should run as 64-bit. Or the other way around (64bit console and 32-bit host).

**Comment by tannergooding** [comment] 2020-03-23 14:37
> This runs nicely, but does not do what is advertised because the test host ends up running as 32-bitwhile it should run as 64-bit. Or the other way around (64bit console and 32-bit host).

By console do you mean `cmd.exe` or `vstestconsole.exe`? In the case of the latter, does that matter? The intent is for the unit tests to be run under .NET as the targeted architecture, regardless of what the test host (which manages launching the tests and collecting metrics) runs as.

The following should all be valid/invalid:
| OS Bitness | Test Host Bitness | Unit Test Bitness | Valid |
| ---------- | ----------------- | ----------------- | ----- |
| 32-bit     | 32-bit            | 32-bit            | Yes   |
| 32-bit     | 32-bit            | 64-bit            | No    |
| 32-bit     | 64-bit            | 32-bit            | No    |
| 32-bit     | 64-bit            | 64-bit            | No    |
| 64-bit     | 32-bit            | 32-bit            | Yes   |
| 64-bit     | 32-bit            | 64-bit            | Yes   |
| 64-bit     | 64-bit            | 32-bit            | Yes   |
| 64-bit     | 64-bit            | 64-bit            | Yes   |

Running 64-bits from a 32-bit OS, even if the underlying hardware could support 64-bit is invalid (hardware will be in 32-bit mode, etc).

Running a 32-bit app from a 64-bit OS is supported; largely via `SysWOW64` (Windows on Windows).

Having a 64-bit unit tests launched from a 32-bit host on a 64-bit OS is also fine. The unit tests would still be running in 64-bit mode and a 32-bit and 64-bit app can communicate with eachother over IPC or similar. Many of the Visual Studio Out of Process components work this way because VS itself is 32-bits, but compilers and other tools may need to be 64-bits.

**Comment by nohwnd** [comment] 2020-03-23 14:59
> By console do you mean cmd.exe or vstestconsole.exe?

I meant bitness of the vstest.console / dotnet test. Invoking a 64-bit test project should start a 64-bit test host even if we start it via 32-bit dotnet test. I am not 100% sure what is happening in this case, because I did not analyze it deeper. But it should be pretty easy to see. 

> Having a 64-bit unit tests launched from a 32-bit host on a 64-bit OS is also fine. The unit tests would still be running in 64-bit mode and a 32-bit and 64-bit app can communicate with eachother over IPC or similar. Many of the Visual Studio Out of Process components work this way because VS itself is 32-bits, but compilers and other tools may need to be 64-bits.

Yup that is exactly how it works for vstest console as well. A 32-bit VS runs 64-bit TestWindowStoreHost that runs 32-bit vstest.console that then runs 32-bit or 64-bit test host and they all communicate via sockets 🙂

**Comment by Evangelink** [comment] 2022-08-03 14:00
The issue is for a relatively old version of Test Platform. Are you still experiencing issues? @tannergooding @martincostello @rockfordlhotka @unaizorrilla @shaynevanasperen

**Comment by unaizorrilla** [comment] 2022-08-03 14:07
Hi @Evangelink 

nope!

**Comment by Evangelink** [comment] 2022-08-03 14:09
Thank you for the prompt reply @unaizorrilla! For the others, please feel free to let us know if you are still having some issue.

**Closed by Evangelink** 2022-08-03 14:09 UTC

**Comment by rockfordlhotka** [comment] 2022-08-03 14:13
I am not.
