### ISSUE TITLE
Program does not contain a static 'Main' method suitable for an entry point

### ISSUE THREAD

**Issue by Grauenwolf** [microsoft/vstest#2214] opened 2019-10-05 01:33 UTC
## Description

When I upgrade to Microsoft.NET.Test.Sdk v16.3.0 and rebuild, I get the below error message:

>Program does not contain a static 'Main' method suitable for an entry point

Switching back to Microsoft.NET.Test.Sdk v16.2.0 clears the error.

This has been consistent for both .NET Core 2.1 and 3.0 test projects. It affects both MSTest and xUnit projects.

**Comment by singhsarab** [comment] 2019-10-07 12:47
@Grauenwolf Can you please add some more details. What is the version of dotnet cli and VS on the machine? I am assuming you are able to reproduce the issue using a simple unit test project.

**Comment by singhsarab** [comment] 2019-10-10 10:48
@Grauenwolf Are you still facing this issue ?

**Comment by Grauenwolf** [comment] 2019-10-11 17:16
I just retested with a clean project and it is still happening. 

[UnitTestProject2.zip](https://github.com/microsoft/vstest/files/3718815/UnitTestProject2.zip)

VS: 16.3.2
Core: 3.0.100

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.3.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="2.0.0" />
    <PackageReference Include="MSTest.TestFramework" Version="2.0.0" />
    <PackageReference Include="coverlet.collector" Version="1.1.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

**Comment by singhsarab** [comment] 2019-10-21 10:07
@Grauenwolf I am sorry, not able to reproduce the issue.
I tried on VS 16.3.5 using the project that you shared.

**Comment by singhsarab** [comment] 2019-10-22 11:22
Closing this issue for now. Please share more details so we can help diagnose this.

**Closed by singhsarab** 2019-10-22 11:22 UTC

**Comment by MarkBrainfire** [comment] 2022-07-10 06:26
I have the same issue.

**Comment by Evangelink** [comment] 2022-07-11 06:18
@MarkBrainfire Could you please give us more details? Which version is working and which version isn't? Do you have any repro you could share with us? Thanks

**Comment by MarkBrainfire** [comment] 2022-07-23 05:51
I solved the problem by updating Microsoft.NET.Test.Sdk from 17.1.0 to 17.2.0 (or above)

DETAILS:
I'm using .NET 6 / VS 17.3.0 Preview 4
The current XUnit project template imports:
Microsoft.NET.Test.Sdk (17.1.0)
xunit (2.4.1)
xunit.runner.visualstudio (2.4.3)

The error message "Program does not contain a static 'Main" method suitable for an entry point" goes away when the Microsoft.NET.Test.Sdk is updated to either 17.2.0 (or the preview 17.4.0).  Updating xunit and xunit.runner.visualstudio doesn't have any impact on this problem.

**Comment by MoaidHathot** [comment] 2024-02-04 22:31
I started getting this issue suddenly in `17.8.0`. Reverting to `17.7.2` solves it...
It is important to mention that the issue did not reproduce immediately, but that it started showing up without any apparent reason or relevant code changes.

**Comment by nohwnd** [comment] 2024-02-05 13:32
@MoaidHathot Do you have a repro please?

**Comment by talhashoaib** [comment] 2025-02-26 15:00
I am facing the same issue with version 17.13.0 and downgrading to 17.12.0 solves it. Actual reason unknown.
