### ISSUE TITLE
TestAdapterPath argument is ignored when Settings file is passed.

### ISSUE THREAD

**Issue by navin22** [Microsoft/vstest#1148] opened 2017-09-28 13:53 UTC
## Description
> When you run the tests as `vstest.console E:\temp\proj\bin\debug\test.dll --TestAdapterPath:"E:\package\adapterfix"`
The adapter is picked from `E:\package\adapterfix`. But when you execute the following command
`vstest.console E:\temp\proj\bin\debug\test.dll --TestAdapterPath:"E:\package\adapterfix" --Settings:"E:\settings\dasettings.runsettings"` 
The adapter is picked from `E:\temp\proj\bin\debug\`

## Note
> When the first command is executed vstest.console.exe is loading the adapter.
> When the second command is run testhost.x86.exe is loading the adapter.

## Environment
> 
> latest vstest.console.

**Comment by singhsarab** [comment] 2017-10-24 12:40
From TestPlatform side, adapter that gets loaded inside the main appdomain is decided based on the testadapterpath, if testadapterpath is not shared by the user, then we look in the output directory of the test assembly.

In this particular case, while debugging I figured that the child app domain that is created by the adapter for running the test is loading the adapter from the output directory of the test assembly.
For example,
We have E:\package\adapter folder that contains the adapter A(v2.0), and output directory of test dll Test1.dll contains adapter A(v1.0). In this case, if user specifies `/testadapterpath:E:\package\adapter` TestPlatform will load A(v2.0) in main AppDomain, then this adapter creates another AppDomain where it will load A(v1.0).

@pvlakshm is this design fine ?

**Comment by codito** [comment] 2017-10-25 04:27
It is unnatural to build with a different version and use a different version at runtime.

**Comment by pvlakshm** [comment] 2017-11-03 13:22
This could be problematic if there are compat issues between the versions. Shouldn't the command line argument trump .runsettings?

**Comment by singhsarab** [comment] 2017-11-30 10:09
This is not a bug on the Test Platform side as per my initial comment.
This gets covered in https://github.com/Microsoft/testfx/issues/194.
Closing this one.

**Closed by singhsarab** 2017-11-30 10:09 UTC
Labels: bug, exp: cli
