### ISSUE TITLE
Add Attributes to the TestDefinition in the trx file.

### ISSUE THREAD

**Issue by kendrahavens** [microsoft/vstest#2480] opened 2020-07-10 21:06 UTC
[Original developer community feedback copied here](https://developercommunity.visualstudio.com/content/idea/1100667/add-attributes-to-the-testdefinition-in-the-trx-fi.html)

I’d like suggest adding the attributes of a TestMethod to the TestDefinition in the test result file.

There is several attributes in the Microsoft.VisualStudio.TestTools.UnitTesting namespace that would make sense to add.

Here is an example of what it could loook like for
Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute
Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute
Microsoft.VisualStudio.TestTools.UnitTesting.OwnerAttribute

```csharp
[TestMethod]
[TestProperty("Key1", "Value1")]
[TestProperty("Key2", "Value2")]
[Description("Test Description Data")]
[Owner("Owner Name")]
public void TestCaseName()
{

}
```

```xml
<TestDefinitions>
<UnitTest name="TestCaseName" storage="unittests.dll" priority="4" id="40b0cd91-e3c2-d2c7-c9de-8d3b3d7e3bd1">
  <Description>Test Description Data</Description>
  <Execution id="49d87ce0-a1b6-4497-a848-9df61cd0d438" />
  <Owner>Owner Name</Owner>
  <Properties>
    <Property>
      <Key>Key1</Key>
      <Value>Value1</Value>
    </Property>
    <Property>
      <Key>Key2</Key>
      <Value>Value2</Value>
    </Property>
  </Properties>
  <TestMethod codeBase="UnitTests.dll" adapterTypeName="executor://mstestadapter/v2" className="UnitTests.Tests" name="TestWithProperties" />
</UnitTest>
</TestDefinitions>
```

**Comment by nullimpex** [comment] 2020-12-21 09:22
It would be great to add grouping option by "traits" (akin to _VS Test Explorer_ Traits grouping) to trx output, with xml nodes nesting in trx/html output ofc

The "traits" in _VS Test Explorer_ are based on [TestCategoryAttribute] and [CategoryAttribute] applied to classes marked with [TestAttribute] and [TestFixtureAttribute]. 

There are 4 categories defined in our tests at present: "FileAttachments", "QuickFilter", "redacted" and "AddRows"

To better explain my suggestion, here is a view from _VS Test Explorer_ of our tests runs:
![VS_Test_Explorer_Grouping_View_failed](https://user-images.githubusercontent.com/11330012/102760199-75b59080-4375-11eb-9f7c-009e1f2a5f8c.PNG) ![VS_Test_Explorer_Grouping_View_passed](https://user-images.githubusercontent.com/11330012/102760213-7b12db00-4375-11eb-9262-9424b0f7a262.PNG)

And here is expected output from trx file (rendered in _AzureDevOps_ test run view)
(there is one level of nesting visible already, resulting from separate test runs for two sets of parameters P1, P2, P3 values)
![AzureDevOps_Test_Report_Expected_Look](https://user-images.githubusercontent.com/11330012/102757472-ad223e00-4371-11eb-862d-118611655252.PNG)
I would like the "traits" to be displayed as another nest level within a test run.

And why not go one step further and add all grouping options available in _VS Test Explorer_ in vstest trx/html output?

**Comment by ratok-mk** [comment] 2021-08-12 14:30
How is the status of this feature?
Our team changed to Azure Devops and we are really missing this feature, since we used the Description ([Description("Test Description Data")]) properties for matching Unit Tests with our documented testplans.

**Comment by JustusStorm** [comment] 2021-09-28 17:48
I actually have been adding descriptions to my tests in a pretty extensive Selenium regression testing framework for my companies web app. But now I'm trying to extract those descriptions to throw into a database along with the test results. 

I'm having the same issue with not being able to figure out how to exact the description from each test.

**Comment by nohwnd** [comment] 2024-07-09 08:51
This is a new feature and won't be implemented, we are focusing on adding new features to Testing.Platform instead. https://aka.ms/testingplatform

**Closed by nohwnd** 2024-07-09 08:51 UTC
Labels: enhancement
