### ISSUE TITLE
Version variable for Microsoft.NET.Test.Sdk

### ISSUE THREAD

**Issue by Tasteful** [Microsoft/vstest#1285] opened 2017-11-09 17:32 UTC
Installed the update of VS 15.4.3 from 15.4.2 and that was breaking the test explorer inside VS and updating this package was not the first that I was trying out.

Does it exists any msbuild variable that can be used for the `<PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.3.0" />` version attribute to always have a reference to the `Microsoft.NET.Test.Sdk` that is compatible with the current version of Visual Studio? 

Or can a message that telling that referenced version is to old and need to be updated with the exception?

**Comment by smadala** [comment] 2017-11-11 05:46
@Tasteful `Microsoft.NET.Test.Sdk` brings `testhost.dll`(which host the tests discovery/execution) and few targets and properties to run .NET Core tests. Which need not to be sync with VS version.
Can you please give the more details about `breaking the test explorer`, What was earlier version you were using? Share sample repro project.

**Comment by Tasteful** [comment] 2017-11-11 08:21
@smadala 
I have the csproj file that was referencing the version `15.3.0` and after upgraded VS from `15.4.2` to `15.4.3` release and when opened the solution I got an error in the test output window and no tests was found into test explorer. Today when I tested again with the Sdk `15.3.0` version everything was working. 

Project file was like this.
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.3.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.3.1" />
    <PackageReference Include="xunit" Version="2.3.1" />
  </ItemGroup>
  
</Project>
```

**Comment by smadala** [comment] 2017-11-15 09:27
@Tasteful Thanks for update, Issue might be related to upgrade scenario. Please collect diagnostic logs([here](https://github.com/Microsoft/vstest-docs/blob/master/docs/diagnose.md#collect-trace-using-config-file)) as mentioned in `New Issue template` If you encounter issue again that will help to find root cause. Closing it as there is no repro.

**Closed by smadala** 2017-11-15 09:27 UTC
Labels: exp: sdk
