### ISSUE TITLE
Tests hang from dotnet test

### ISSUE THREAD

**Issue by JamesNK** [microsoft/vstest#2080] opened 2019-06-30 11:27 UTC
## Steps to reproduce
Tests run on travis CI via `dotnet test` now intermittently fail. Failures started after updating to a newer .NET Core SDK. It appears that the test tool increased from 16.0.1 to 16.1.1 with the new SDK.

Source code: https://github.com/grpc/grpc-dotnet/commits/master

## Expected behavior
Tests run and exit

## Actual behavior
Tests hang and the build is terminated

## Diagnostic logs
Failure: https://travis-ci.org/grpc/grpc-dotnet/builds/551562232?utm_source=github_status&utm_medium=notification
`Microsoft (R) Test Execution Command Line Tool Version 16.1.1`

Success: https://travis-ci.org/grpc/grpc-dotnet/builds/551058627?utm_source=github_status&utm_medium=notification
`Microsoft (R) Test Execution Command Line Tool Version 16.0.1`

**Comment by mayankbansal018** [comment] 2019-07-01 08:45
@JamesNK , if this is an intermediate issue, can you please enable diagnostics logs for testplatform & share those with us https://github.com/Microsoft/vstest-docs/blob/master/docs/diagnose.md

**Comment by JamesNK** [comment] 2019-07-02 02:37
I can't easily get logs off the build server but I can repo freezing on my dev machine with this. It freezes all the time within a couple of iterations:

`while($true) { dotnet test --diag:log.txt }`

[testlogs.zip](https://github.com/microsoft/vstest/files/3348043/testlogs.zip)

**Comment by JamesNK** [comment] 2019-07-04 20:22
This is an ongoing problem. I'd like to make some progress on fixing it.

Do you need anymore information from me?

**Comment by mayankbansal018** [comment] 2019-07-05 06:42
@JamesNK I went through the logs & from the logs I didn't see any hang state. The only interesting thing I observed was that it seemed we start 10 different testhost processes in sequence, but you have shared logs for 30 testhost process. Can you please share how many test dlls are you running ?

**Comment by JamesNK** [comment] 2019-07-06 00:27
Because I'm doing it in a loop: `while($true) { dotnet test --diag:log.txt }`

In the example of the logs I attached it freezes are 3 runs.

Have you tried reproing it?

**Comment by mayankbansal018** [comment] 2019-07-08 14:26
I'm looking into it, I've cloned the repo, & all I need to do is run dotnet on sln right?

**Comment by mayankbansal018** [comment] 2019-07-08 14:49
I tried it locally multiple times, but it did not repro for me.

**Comment by tasadar2** [comment] 2019-07-11 23:08
We are currently experiencing the same issue. We have been using `mcr.microsoft.com/dotnet/core/sdk:2.2.204` to avoid the performance degradation issue which is now resolved. But when attempting the latest `mcr.microsoft.com/dotnet/core/sdk`, currently `b4c25c26dc73f498073fcdb4aefe167793eb3a8c79effa76df768006b5c345b8`, only a couple test runs finish while the rest seem to hang.
As with the performance issue, it seems to be related to non-interactive hosts.

**Situation**
- Our solution contains 10 test projects, each one has `<IsTestProject>true</IsTestProject>` set, and we are running `dotnet test` against the solution in a CircleCI environment.
- When each test is run individually, everything works as intended.
- When run locally, i see only 4 tests run at any time. And the local system only has 4 cpu cores.

**Replication**
I condensed our project to share an example. Each test project has a single test that sleeps for 5sec.
Repo: [https://github.com/tasadar2/vstest-issue-2080](https://github.com/tasadar2/vstest-issue-2080)
CircleCI: [https://circleci.com/gh/tasadar2/vstest-issue-2080/3](https://circleci.com/gh/tasadar2/vstest-issue-2080/3)

It doesn't always replicate the issue, but often does.

**Comment by JamesNK** [comment] 2019-07-13 23:15
Running test projects individually has fixed this problem for us - https://github.com/grpc/grpc-dotnet/commit/152255ec5419c1360819788d7911f4957c8e4e2c

**Comment by singhsarab** [comment] 2019-07-23 15:37
@tasadar2 @JamesNK sdk:2.2.301 has a fix, can you please check if you are still hitting the issue ?

**Comment by tasadar2** [comment] 2019-07-24 01:45
Still appears to be an issue.
image: `mcr.microsoft.com/dotnet/core/sdk@sha256:a50e175acd618c3e90bc91dceb5194e6c3764c5b4d179390cef874a887476ba9`
example: [https://circleci.com/gh/tasadar2/vstest-issue-2080/7](https://circleci.com/gh/tasadar2/vstest-issue-2080/7)

**Comment by JamesNK** [comment] 2019-07-30 09:51
I've narrowed down my hanging issue to with how vstest writes to the console. If no tests fail then vstest completes without any problems. If a test fails then it hangs until the CI build times out (this is in Travis CI)

The workaround I am using is to write the test output to a text file, and the write the text file to console.

**Comment by singhsarab** [comment] 2019-07-30 10:20
@JamesNK What is the dotnet sdk version you are using ? Can you share the link to the CI ?

**Comment by JamesNK** [comment] 2019-07-30 10:39
3.0.100-preview8-013532

https://travis-ci.org/grpc/grpc-dotnet/builds/565363470?utm_source=github_status&utm_medium=notification

**Comment by davidruhmann** [comment] 2019-08-08 18:05
Here is a repro for this issue on CircleCI
https://github.com/davidruhmann/vstest2080

https://circleci.com/gh/davidruhmann/vstest2080/3

Each line of `Test run in progress.` output takes several seconds making the tests take a long time on big projects.

**Comment by tasadar2** [comment] 2019-09-25 19:41
Looks like this is still an issue on the recent 3.0.
image: `mcr.microsoft.com/dotnet/core/sdk@sha256:3afea8958440231a77b3daea267951cc8ba9026fc1015bcbccc206d6f1d031f7`
example: [https://app.circleci.com/jobs/github/tasadar2/vstest-issue-2080/10](https://app.circleci.com/jobs/github/tasadar2/vstest-issue-2080/10)

**Comment by singhsarab** [comment] 2019-09-26 11:08
@tasadar2 Can you please try to use --logger:console;noprogress=true argument and check the issue reproduces for you ?

**Comment by tasadar2** [comment] 2019-09-26 19:45
That arg produces the same results, [https://app.circleci.com/jobs/github/tasadar2/vstest-issue-2080/11](https://app.circleci.com/jobs/github/tasadar2/vstest-issue-2080/11)

**Comment by tasadar2** [comment] 2019-09-26 19:55
Though, when quoting the argument value, that seems to work `--logger:"console;noprogress=true"`
[https://app.circleci.com/jobs/github/tasadar2/vstest-issue-2080/14](https://app.circleci.com/jobs/github/tasadar2/vstest-issue-2080/14)

**Comment by NicolasDorier** [comment] 2019-10-09 07:39
I had the same problem, two workaround worked:

Adding `--logger:"console;noprogress=true"` like @tasadar2 

However, I did not like it because I could not see the progress, so instead added `< /dev/null`

```
dotnet test .... < /dev/null
```

This allow me to see the progress of tests, without hanging.

**Comment by NicolasDorier** [comment] 2019-10-09 07:43
Full logs of a successful build with feedback https://circleci.com/gh/dgarage/NBXplorer/430 before the hack you can see things stalling https://circleci.com/gh/dgarage/NBXplorer/409

**Comment by lukebakken** [comment] 2020-03-04 16:46
@NicolasDorier thank you for finding [your workaround](https://github.com/microsoft/vstest/issues/2080#issuecomment-539879345). I can confirm it works, please see rabbitmq/rabbitmq-dotnet-client#750

**Comment by erick-thompson** [comment] 2020-03-26 00:50
Is there a longer term fix for this? I'm running into the same issue with a set of web integration tests.

**Comment by NicolasDorier** [comment] 2020-03-26 05:36
Ping @mayankbansal018  please remove the tag, there is enough information and this issue and workaround have been tested by numerous people. This is a bug that need to be fixed and well identified.

**Comment by nohwnd** [comment] 2020-03-31 15:25
@JamesNK So far it looks like it is caused by setting color at the same time as setting cursor position. https://github.com/microsoft/vstest/issues/2282 Exploring strategies how to avoid that. Probably the best is to write the progress in a way similar to @NicolasDorier comment [above](https://github.com/microsoft/vstest/issues/2080#issuecomment-539879345).  But ideally write dots at the end of the line, so the output is not affected that much.

Experimenting with it here, and also trying to get it to lock up by moving cursor on the vstest-like branch. See the other thread for some more info. 

https://travis-ci.org/github/nohwnd/ProgressToy/branches

**Comment by tremblaysimon** [comment] 2020-06-05 01:55
Only to confirm that we get that problem in Concourse if and only if `dotnet test` executed on a solution file.

**Comment by keshavkaul** [comment] 2020-07-10 06:41
@NicolasDorier Any suggestions for windows powershell?

**Comment by NicolasDorier** [comment] 2020-07-17 09:10
I don't remember having the issue on powershell.

**Comment by dhilst** [comment] 2021-03-19 17:30
I had this problem with a small vm (2 cores, 2GB ram), increasing to 8cores and 8gb ram make it work. I read at some place that this was thread related so I came up with the more cores idea

**Comment by diegosasw** [comment] 2021-03-29 13:30
Not sure if it's related. I'm also a GitLab user and found a very similar problem so I suspect it's probably related to the SDK image, but in my case happens with `Microsoft (R) Test Execution Command Line Tool Version 16.9.1`
https://forum.gitlab.com/t/dotnet-test-hangs-in-gitlab-gitlab-runner-13-9-0-rc2/50977

**Comment by diegosasw** [comment] 2021-03-30 09:27
Out of curiosity, is anybody experiencing this only when using `IHostedService`? [In my case](https://github.com/dotnet/sdk/issues/9452#issuecomment-810065702) it seems that's what causing the tests to freeze within a linux image

**Comment by tremblaysimon** [comment] 2021-03-30 13:38
@diegosasw, for me it's happening when using dotnet test on a solution file even if there is no IHostedService usage.

**Comment by victor-fialkin-deltatre** [comment] 2021-12-09 22:07
> --logger:"console;noprogress=true"
This helped us in case of IHostedService:
https://www.strathweb.com/2021/05/the-curious-case-of-asp-net-core-integration-test-deadlock/

**Comment by gdoron** [comment] 2022-08-16 08:52
@Evangelink @davidfowl Even on our very powerful Macbook pros, when we are running one of our integration test projects that has hundreds of tests, many of which use `WebApplicationFactory` we often get into deadlocks.

We set xunit to use unlimited amount of threads (-1), we have overridden a bunch of xunit stuff to implement a semaphore to limit the number of concurrent tests.
And yet, often we get into deadlocks after the ~600 tests completed mark.
After verifying we have no sync-over-async, we found this beauty in asp.net core code itself...
<img width="783" alt="image" src="https://user-images.githubusercontent.com/6141009/184838634-924c32cc-c92e-437e-bd2a-881fb11f0ecb.png">

https://github.com/dotnet/aspnetcore/blob/main/src/Hosting/TestHost/src/TestServer.cs#L101

Can this be the root cause for all our deadlocks **only in Unit tests** problems?

**Comment by gdoron** [comment] 2022-08-16 13:22
**Finally!** I managed to reproduce it in a small test project, where I can do dotnet-dump and attach to process without everything crashing.

I found this fella in one of the threads' callstack. 
<img width="751" alt="image" src="https://user-images.githubusercontent.com/6141009/184886952-3a0f677b-cf02-49fb-9ef7-bbae1726275d.png">

And going up the callstack we can see it's inside (**or trying to get inside and the debugger is misleading**) a lock block of NLog.
<img width="1043" alt="image" src="https://user-images.githubusercontent.com/6141009/184889888-46e20f60-9bdc-4fd0-b0da-333bd90b23b3.png">

**Comment by davidfowl** [comment] 2022-08-16 23:33
Can you file [this issue](https://github.com/microsoft/vstest/issues/2080#issuecomment-1216336468) on dotnet/aspnet

**Comment by gdoron** [comment] 2022-08-17 22:05
Your request is my command: https://github.com/dotnet/aspnetcore/issues/43353

**Comment by JBoothUA** [comment] 2022-10-14 14:22
just in case this helps someone, at a **random** time this line started **randomly** hanging our tests

_task = Task.Factory.StartNew(async () =>
      {
        await Task.Delay((int)cleanInterval.TotalMilliseconds, _cancellationTokenSource.Token);
-->     while (!_cancellationTokenSource.Token.IsCancellationRequested)

**Comment by Evangelink** [comment] 2022-11-30 09:37
@cvpoienaru Please investigate this issue.

**Comment by Piedone** [comment] 2022-12-14 00:29
Did anything happen in the investigation by chance?

**Comment by diegosasw** [comment] 2023-01-20 08:33
I am experiencing the same when using TestServer.
It works well locally, when running in GitLab runner, it hangs.
I've noticed it gets frozen when trying to dispose TestServer because the disposing of `IWebHost` hangs.
No exceptions thrown.

I've tried to stop all the `IHostedService` in case that's the problem, but still unable to dispose `TestServer` to see if that solves the problem.

Could I know how are you troubleshooting this? The only workaround i have is to set 
```
#if DEBUG
[assembly: CollectionBehavior(CollectionBehavior.CollectionPerClass, DisableTestParallelization = false)]
#else
[assembly: CollectionBehavior(CollectionBehavior.CollectionPerClass, DisableTestParallelization = true)]
#endif
```
in the test assembly, so that it runs sequentially in CI/CD pipeline.

**Comment by nohwnd** [comment] 2023-01-23 13:55
@cvpoienaru Please investigate this issue.

**Comment by github-cicd** [comment] 2023-07-06 23:48
This is still an issue

**Comment by psoladoye** [comment] 2023-07-06 23:49
This issue is still unresolved.

**Comment by nohwnd** [comment] 2024-07-11 09:54
This issue is a mix of different problems, some related to other products, but I did not find a clear repro. If someone is still experiencing this problem and has a simple repro, please file a new issue.

**Closed by nohwnd** 2024-07-11 09:54 UTC
Labels: bug
