### ISSUE TITLE
TestWillNotBuildTheProjectIfNoBuildArgsIsGiven is failing CLI update stage 0

### ISSUE THREAD

**Issue by wli3** [microsoft/vstest#2202] opened 2019-09-29 23:26 UTC
When [updating to the latest stage 0]( https://github.com/dotnet/cli/pull/12733), [TestWillNotBuildTheProjectIfNoBuildArgsIsGiven](https://github.com/dotnet/cli/blob/release/3.1.1xx/test/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestfromCsproj.cs#L199) fails. This test is maintained by VSTest. It only fails in Linux.

```
Expected string \"The argument /Users/vsts/agent/2.155.1/work/1/s/artifacts/tmp/Release/test/dotnet-test.Tests/5/VSTestCore/bin/Release/netcoreapp3.0/VSTestCore.dll is invalid. Please use the /help option to check the list of valid arguments.\" to contain \"The test source file \\\"/Users/vsts/agent/2.155.1/work/1/s/artifacts/tmp/Release/test/dotnet-test.Tests/5/VSTestCore/bin/Release/netcoreapp3.0/VSTestCore.dll\\\" provided was not found.\".
```

However, once you fix the issue in vstest. We need an insertion to toolset. And we need to wait for toolset->core-sdk->CLI to unblock. I am wondering if you could move this test to vstest repo. I don't think SDK is required to test argument validation.

**Comment by wli3** [comment] 2019-09-30 00:40
We SKIPPED the test to unblock ourselves

**Comment by singhsarab** [comment] 2019-10-10 13:19
@wli3 @nguerrera I don't understand the reason we think this is an issue on the VSTest side.

If this is a regression, it would be in the dotnet test verb, which has the code for parsing the arguments.
Taking a look at the test, it seems it tries validate the error scenario where if --no-build args are passed, since the dll would not have been built, it would not be able to test it.

Is this test failing in the latest bits? when did it start breaking? Is it because of a recent change in the test platform?

**Comment by nguerrera** [comment] 2019-10-10 14:53
It failed with the testplatform updated between these:

```
    "dotnet": "3.0.100-preview8-013422",
    "dotnet": "3.0.100",
```

Some change inserted into 3.0 after preview8 (or after that build of preview 8) broke it.

Unfortunately, the tests in dotnet/cli do not see the latest testplaform, they test with what is in the lkg version specified in global.json. This is something that will be fixed with repo consolidation.

**Comment by wli3** [comment] 2019-10-10 17:52
and I believe dotnet test verb is also maintained by vstests team. cc @livarcocc

**Comment by singhsarab** [comment] 2019-10-11 06:41
@wli3 Yes, it is maintained by my team. But then, I was surprised to see the insertion succeed with failing tests in PR.

**Comment by singhsarab** [comment] 2019-10-11 06:41
@nguerrera Thanks, let me take a look

**Comment by michsco** [comment] 2020-03-19 22:15
We ran into this same thing in Minecraft Services and had to remove `--no-build` argument to make this work.

Is there any timeline for when this will be fixed?

**Comment by nohwnd** [comment] 2020-03-20 09:15
Adding for consideration to 16.7.0

**Comment by Sanan07** [comment] 2020-06-22 14:03
@wli3 I was able to reproduce the issue and pass test in Linux. After dotnet `3.0.100-preview 8` there was a change in TestPlatform, which added new exception message, when user send incorrect arguments in console. You need to change your error message in your test to pass the build. Please look at this draft PR, which I created to reproduce the issue : https://github.com/dotnet/cli/pull/13401

**Comment by Sanan07** [comment] 2020-07-17 10:20
Closing the issue, as there is nothing to do on our side. Look at the comment above to fix it.

**Closed by Sanan07** 2020-07-17 10:20 UTC
Labels: bug

**Comment by emmenlau** [comment] 2021-06-04 08:55
@Sanan07 I've ran into this same issue but I do not understand how above comment helps, can you please explain?
Here is my problem: A test used to work for the better part of a year, but suddenly fails to work. The only part that was changed in our CI was the continuous update of dotnet. So I assume something must have changed on dotnet side?

The test is called on Linux as
```
/usr/bin/dotnet "test" "Thrift.sln" "--nologo" "--no-build" "--no-restore" "--configuration" "Debug" \
    "--output" "/data/Debug/thrift/lib/netstd/Thrift/bin" \
    "--results-directory" "/data/Debug/thrift/lib/netstd/Tests/Thrift.Tests/results"
```
and now suddenly returns:
```
402: Test timeout computed to be: 1500
402: Test run for /data/Debug/thrift/lib/netstd/Thrift/bin/Thrift.IntegrationTests.dll(.NETCoreApp,Version=v3.1)
402: Test run for /data/Debug/thrift/lib/netstd/Thrift/bin/Thrift.Tests.dll(.NETCoreApp,Version=v3.1)
402: The argument /data/Debug/thrift/lib/netstd/Thrift/bin/Thrift.IntegrationTests.dll is invalid. Please use the /help option to check the list of valid arguments.
402: The argument /data/Debug/thrift/lib/netstd/Thrift/bin/Thrift.Tests.dll is invalid. Please use the /help option to check the list of valid arguments.
```
If my error is indeed the same as above, can you please help how to resolve this?

**Comment by Sanan07** [comment] 2021-06-04 09:09
Which dotnet version do you use? You can run `dotnet --info` for it. And also please add `--diag` argument for your test and look at diagnostic logs. Refer documentation [here](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test#arguments).

If you do not solve it, share diagnostic logs here, so we will look at it.

**Comment by emmenlau** [comment] 2021-06-04 11:05
Thanks a lot @Sanan07 !

I've added `--diag` and it does show something that may be related, but I'm not sure it makes sense, at least not to me. It says something about the path being absolute, albeit I'm not sure this is an error(?). Here is the output:
```
TpTrace Information: 0 : 999021, 1, 2021/06/04, 12:07:48.460, 254465373888146, vstest.console.dll, Using .Net Framework version:.NETCoreApp,Version=v3.1
TpTrace Information: 0 : 999020, 1, 2021/06/04, 12:07:48.466, 254465375936847, vstest.console.dll, FilePatternParser: The given file /data/Debug/thrift/lib/netstd/Thrift/bin/Thrift.Tests.dll is a full path.
TpTrace Error: 0 : 999020, 1, 2021/06/04, 12:07:48.473, 254465383300780, vstest.console.dll, ArgumentProcessorFactory.WrapLazyProcessorToInitializeOnInstantiation: Exception initializing argument processor: Microsoft.VisualStudio.TestPlatform.CommandLine.TestSourceException: The argument /data/Debug/thrift/lib/netstd/Thrift/bin/Thrift.Tests.dll is invalid. Please use the /help option to check the list of valid arguments.
   at Microsoft.VisualStudio.TestPlatform.CommandLine.CommandLineOptions.AddSource(String source)
   at Microsoft.VisualStudio.TestPlatform.CommandLine.Processors.TestSourceArgumentExecutor.Initialize(String argument)
   at Microsoft.VisualStudio.TestPlatform.CommandLine.Processors.ArgumentProcessorFactory.<>c__DisplayClass20_0.<WrapLazyProcessorToInitializeOnInstantiation>b__0()
nInstantiation>b__0()
```

And here is the output of `dotnet --info`:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.409
 Commit:    217439b5ae

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.409/

Host (useful for support):
  Version: 3.1.15
  Commit:  dc339bd0fb

.NET Core SDKs installed:
  3.1.409 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.15 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.15 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
