### ISSUE TITLE
Setting ServerGC for the test runner

### ISSUE THREAD

**Issue by ivonin** [microsoft/vstest#1967] opened 2019-03-22 22:25 UTC
## Description
VSTest.console.exe is currently configured to run in workstation GC (also concurrent). There is currently no way to change this behavior other than patching the `vstest.console.exe.config` file in the VS installation folder. This solution is obviously not pleasant.

We have a big test assembly (11.5k tests) and it makes a *big* difference: the tests take 9 minutes to run with `ServerGC=off` and 4.5 minutes with `ServerGC=on`.

## Expected behavior
1. It's probably not a bad thing to make `ServerGC=on` by default (MSTest v1 was using server GC, see `QTAgent32.exe.Config`)
2. If not, it would be nice to set the behavior via the `.runsettings` file.

**Comment by ShreyasRmsft** [comment] 2019-03-25 12:16
Consider taking a look at https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/clr-configuration-knobs.md#host-configuration-knobs

If it can be achieved by env vars then you can author a script that sets this assuming you are running in a pipeline

**Comment by ShreyasRmsft** [comment] 2019-03-25 12:17
As for a in-house solution we are open to contributions for making this configurable via runsetttings.

**Comment by ivonin** [comment] 2019-03-25 13:58
@ShreyasRmsft `vstest.console.exe` is not a .NET Core app, am I wrong? I'm not sure if the Core-CLR configuration knobs are applicable in this case.

Do you know of a similar way of providing GC settings for the desktop .NET Framework app? Nothing comes to my mind.

**Comment by ShreyasRmsft** [comment] 2019-03-26 07:01
Will have to read-up on this. Lemme know if you find anything. I'll also try seeing if there's anything we can do for full .Net

**Comment by ivonin** [comment] 2019-04-09 09:05
@ShreyasRmsft any update on this?

Could you help me understand which downsides you see in just setting `ServerGC=on` by default? It seems reasonable considering that the MSTest v1 runner worked that way.

**Comment by ShreyasRmsft** [comment] 2019-04-09 09:30
@ivonin looping in @singhsarab and @mayankbansal018 to help with this

**Comment by mayankbansal018** [comment] 2019-04-10 10:22
@ivonin The servergc can be enabled for testhost.exe, testhost.x86.exe, do you think you can raise a PR for this?

**Comment by ivonin** [comment] 2019-04-10 15:45
@mayankbansal018 I created a PR, see above.

From what I can see `vstest.console.exe` runs some tests directly, at least in some scenarios, and changing the GC mode for `vstest.console.exe` fixes the problem. I ended up setting the GC options for all three of the executables.

**Comment by Evangelink** [comment] 2022-02-11 10:25
@nohwnd I see this ticket is still open but related PR was closed and not merge whereas from discussions it seems there was no downside. Is it worth reopening and moving forward with the merge?

**Comment by JoshKeegan** [comment] 2022-05-18 11:30
Any reason this never got merged?

While looking at why a large test project runs much faster in Resharper's unit test runner than the Visual Studio or console runners I've found that Resharper is running them with server GC and I believe this to be the cause of the issue. It'd be great to have this be the default for vstest, or at least the ability to opt-in to it.

**Comment by ivonin** [comment] 2022-05-18 16:15
@JoshKeegan some checks failed in my PR and to be honest I just didn't have time to properly deal with it back then.

You can try again and see if maybe things have changed since.

**Comment by JoshKeegan** [comment] 2022-05-20 16:38
I've opened a new PR, let's see 👍

**Comment by JoshKeegan** [comment] 2022-09-05 09:56
@ivonin my PR got merged, so this should be included in a future release & this can be closed 👍

**Comment by Evangelink** [comment] 2022-09-05 09:59
Thanks for the ping @JoshKeegan.

**Closed by Evangelink** 2022-09-05 09:59 UTC
Labels: enhancement, up-for-grabs
