### ISSUE TITLE
Analyzing Code Coverage a CPS project never completes the test run

### ISSUE THREAD

**Issue by davkean** [Microsoft/vstest#625] opened 2017-03-17 05:51 UTC
1. Enlist in https://github.com/dotnet/roslyn-project-system
2. Checkout a9e5252cb89e45bc9c5202789bc7effc61b7531c
3. From a VS command-prompt run build.cmd
4. Open src\ProjectSystem.sln
5. Build once
6. Wait until Text Explorer has found all the tests (> 1 minute!)
7. Choose Test -> Analyze Code Coverage

Expected: Tests to run with code coverage
Actual:

Tests never finish:

```
------ Discover test started ------
[xUnit.net 00:00:00.1177630]   Discovering: Microsoft.VisualStudio.ProjectSystem.CSharp.UnitTests
[xUnit.net 00:00:00.1266380]   Discovered:  Microsoft.VisualStudio.ProjectSystem.CSharp.UnitTests
[xUnit.net 00:00:00.2524349]   Discovering: Microsoft.VisualStudio.ProjectSystem.CSharp.VS.UnitTests
[xUnit.net 00:00:01.2904001]   Discovered:  Microsoft.VisualStudio.ProjectSystem.CSharp.VS.UnitTests
[xUnit.net 00:00:01.4046489]   Discovering: Microsoft.VisualStudio.ProjectSystem.Managed.TestServices.UnitTests
[xUnit.net 00:00:03.1492999]   Discovered:  Microsoft.VisualStudio.ProjectSystem.Managed.TestServices.UnitTests
[xUnit.net 00:00:03.3389787]   Discovering: Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests
[xUnit.net 00:00:07.1827827]   Discovered:  Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests
[xUnit.net 00:00:07.3734671]   Discovering: Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests
[xUnit.net 00:00:12.9868695]   Discovered:  Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests
[xUnit.net 00:00:13.0990597]   Discovering: Microsoft.VisualStudio.ProjectSystem.VisualBasic.UnitTests
[xUnit.net 00:00:13.1068395]   Discovered:  Microsoft.VisualStudio.ProjectSystem.VisualBasic.UnitTests
[xUnit.net 00:00:13.2240274]   Discovering: Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS.UnitTests
[xUnit.net 00:00:13.4796240]   Discovered:  Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS.UnitTests
========== Discover test finished: 1261 found (0:00:14.2913989) ==========
------ Run test started ------
[xUnit.net 00:00:00.4425972]   Discovering: Microsoft.VisualStudio.ProjectSystem.CSharp.VS.UnitTests
[xUnit.net 00:00:01.6038225]   Discovered:  Microsoft.VisualStudio.ProjectSystem.CSharp.VS.UnitTests
[xUnit.net 00:00:01.7766984]   Discovering: Microsoft.VisualStudio.ProjectSystem.Managed.TestServices.UnitTests
[xUnit.net 00:00:03.8097446]   Discovered:  Microsoft.VisualStudio.ProjectSystem.Managed.TestServices.UnitTests
[xUnit.net 00:00:04.6241994]   Discovering: Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests
[xUnit.net 00:00:09.3009123]   Discovered:  Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests
[xUnit.net 00:00:11.1449305]   Discovering: Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests
```

**Comment by davkean** [comment] 2017-03-30 09:01
@codito this seems likes a fairly big regression moving to CPS, because we're starting enabling more projects to do this, I'd like to get to the bottom of this - this has somewhat broken my workflow for writing tests.

**Comment by codito** [comment] 2017-04-03 08:47
@harshjain2 can you please look into it?

**Comment by mayankbansal018** [comment] 2017-04-06 13:37
The issue lies in IntelliTrace, & is being tracked internally at https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems?id=404725&triage=true&fullScreen=true&_a=edit

**Comment by mayankbansal018** [comment] 2017-05-18 06:25
The issue is fixed by IntelliTrace tream, please verify in latest d15prerel builds

**Comment by wiktork** [comment] 2017-05-25 15:09
Issue is now being tracked by https://devdiv.visualstudio.com/DevDiv/_workitems?id=440463.

**Closed** 2017-11-10 11:56 UTC
Labels: blocking-partner, bug, exp: ide, pri: 1
