### ISSUE TITLE
Avoid guid at the end of outputDirectory

### ISSUE THREAD

**Issue by MarcoRossignoli** [microsoft/vstest#2378] opened 2020-03-28 08:25 UTC
On Coverlet we have some users complain about the dynamic folder name generated for reports file.
I did some check on code and seem that guid is "mandatory" and not removable.

https://github.com/microsoft/vstest/blob/master/src/Microsoft.TestPlatform.Common/DataCollection/DataCollectionAttachmentManager.cs#L101-L125

Could be useful add a parameter, maybe in runsetting like `<DeterministicOutputdirectory>true/false</DeterministicOutputdirectory>` and in that case avoid to concat guid.ToString().

Dynamic folder makes CI more complex.

Issues refs https://github.com/tonerdo/coverlet/issues/500 https://github.com/tonerdo/coverlet/issues/767

cc: @DaleyKD

**Comment by nohwnd** [comment] 2020-03-30 12:42
I don't know the reasons for the guid but I would rather avoid yet another option. I see the coverage file described in the TRX output, but even thought there is a href to it, it does not contain the guid. I also don't see the guid anywhere else in the repo. Imho the best course of action is to provide a way that will allow the test result to be programatically processed. 

When you run with CC in azure pipeline, do you see the coverage file automatically uploaded? maybe they have this already figured out.

**Comment by nohwnd** [comment] 2020-03-30 12:43
Admittedly the trx, and xml in general is not the easiest to process, but it's a start, and it is generic format that we don't have to re-invent.

**Comment by MarcoRossignoli** [comment] 2020-03-31 07:21
> When you run with CC in azure pipeline, do you see the coverage file automatically uploaded? maybe they have this already figured out.

Looking at publish result task https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=yaml seem that a globbing filter is used 
```yaml
- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
    failTaskOnFailedTests: true
```

**Comment by MarcoRossignoli** [comment] 2020-03-31 07:24
> Admittedly the trx, and xml in general is not the easiest to process, but it's a start, and it is generic format that we don't have to re-invent.

I'm ok with file format, but non deterministic path add some work to do in some scenario, tipical "find right file and move to".

**Comment by nohwnd** [comment] 2020-04-01 13:10
I meant it more in the direction of returning a simple object that can be programatically processed to get to the info, instead of forcing the naming conventions to be deterministic. For example in Pester I simply return a result object that the caller can process. Here we could do something similar. Say you'd want to upload your CC file: 
 
```powershell
$result = dotnet test --collect="Code Coverage" ....params.... --json-result 
($result | ConvertFrom-Json).Attachements | where Type -eq "Code Coverage" | Invoke-RestMethod -Method PUSH
```

This would be the end product where we would have to come up with the result etc... So a more achievable goal would be to hookup the trx file and read the info from there if it was correct.

**Comment by MarcoRossignoli** [comment] 2020-04-01 18:05
> $result = dotnet test --collect="Code Coverage" ....params.... --json-result

Are you forcing powershell usage?If I don't use powershell what does `--json-result` produce?Is it a json on standard output?

**Comment by nohwnd** [comment] 2020-04-01 18:56
Yes, it was just an exam

________________________________
Od: Marco Rossignoli <notifications@github.com>
Odesláno: Wednesday, April 1, 2020 8:05:48 PM
Komu: microsoft/vstest <vstest@noreply.github.com>
Kopie: Jakub Jareš <me@jakubjares.com>; Comment <comment@noreply.github.com>
Předmět: Re: [microsoft/vstest] Avoid guid at the end of outputDirectory (#2378)


$result = dotnet test --collect="Code Coverage" ....params.... --json-result

Are you forcing powershell usage?If I don't use powershell what does --json-result produce?Is it a json on standard output?

**Comment by nohwnd** [comment] 2020-04-01 18:57
Yes json, it was just an example to show a concept. I am not forcing powershell on anyone.

________________________________
Od: Marco Rossignoli <notifications@github.com>
Odesláno: Wednesday, April 1, 2020 8:05:48 PM
Komu: microsoft/vstest <vstest@noreply.github.com>
Kopie: Jakub Jareš <me@jakubjares.com>; Comment <comment@noreply.github.com>
Předmět: Re: [microsoft/vstest] Avoid guid at the end of outputDirectory (#2378)


$result = dotnet test --collect="Code Coverage" ....params.... --json-result

Are you forcing powershell usage?If I don't use powershell what does --json-result produce?Is it a json on standard output?

**Comment by MarcoRossignoli** [comment] 2020-04-01 19:14
What if we have more than one collector https://github.com/Microsoft/vstest-docs/blob/master/docs/analyze.md#enabledisable-a-datacollector?
A json array with different "Type"?

**Comment by ViktorHofer** [comment] 2020-04-22 04:57
Just stumbled upon this.

> I don't know the reasons for the guid but I would rather avoid yet another option.

I disagree. VSTest should respect the specified `ResultsDirectory` and `CoverageFileName` for data collectors. I can do that for loggers already so I would argue DataCollectors to behave the same:

```
<RunSettings>
  <RunConfiguration>
     <!-- Directory for test run reports. E.g. trx, coverage etc. -->
    <ResultsDirectory>.\</ResultsDirectory>
  </RunConfiguration>
  <LoggerRunSettings>
    <Loggers>
      <Logger uri="logger://Microsoft/TestPlatform/TrxLogger/v1">
        <Configuration>
          <LogFileName>testResults.trx</LogFileName>
        </Configuration>
      </Logger>
      <Logger uri="logger://Microsoft/TestPlatform/HtmlLogger/v1">
        <Configuration>
          <LogFileName>testResults.html</LogFileName>
        </Configuration>
      </Logger>
    </Loggers>
  </LoggerRunSettings>
```

I would expect the following behavior:
- LogFileName inside a DataCollector configuration node is respected:
```
<DataCollectionRunSettings>
    <DataCollectors>
      <DataCollector friendlyName="XPlat code coverage">
        <Configuration>
          <CoverageFileName>coverage.xml</CoverageFileName>
        </Configuration>
      </DataCollector>
    </DataCollectors>
  </DataCollectionRunSettings>
```
- The specified `ResultsDirectory` is respected without any intermediate folders in it.
```
  <RunConfiguration>
     <!-- Directory for test run reports. E.g. trx, coverage etc. -->
    <ResultsDirectory>.\</ResultsDirectory>
  </RunConfiguration>
```
In this example you can even see that coverage is explicitly listed in the comment (which I took from the docs). Specifying the log file name seems to have worked in the past with the pre-coverlet code coverage collector: https://github.com/microsoft/vstest/issues/1957.

**Comment by ViktorHofer** [comment] 2020-04-22 05:03
I just observed another misbehavior:
![image](https://user-images.githubusercontent.com/7412651/79942479-37bf4000-8467-11ea-874b-6a6923156b41.png)

The coverage report is created twice:
- vihofer_DESKTOP-803H9R0_2020-04-22_06_59_42\In\DESKTOP-803H9R0\coverage.opencover.xml
- 4a408eed-656b-435d-a540-30c285d1c57a\coverage.opencover.xml

**Comment by MarcoRossignoli** [comment] 2020-04-25 18:02
> The coverage report is created twice:

@ViktorHofer  I think it's a dup of https://github.com/microsoft/vstest/issues/2334

**Comment by ViktorHofer** [comment] 2020-04-27 13:52
You are right :)

**Comment by ViktorHofer** [comment] 2020-05-05 09:06
FWIW I currently need to clean the TestResults directory manually to make sure that ReportGenerator picks the right coverage results file. Ideally we would not need to do this.

**Comment by paulomorgado** [comment] 2020-06-04 10:02
The directory where the coverage results will be published is required to exist. Otherwise it throws:

    Data collector 'Code Coverage' message: Data collector caught an exception of type 'Microsoft.VisualStudio.Coverage.VanguardException': 'Running event not received from CodeCoverage.exe. Check eventlogs for failure reason.'. More details: ..

That's also bad.

**Comment by ps2goat** [comment] 2020-06-17 21:05
I think I see the purpose for the dynamic folder that is appended-- if you run it at the root level against a solution with multiple test projects, each project is in its own dynamic GUID folder.

A better solution would be to at least use the project name in this scenario. These names are predictable and should be unique:
`TestResults/ProjectA/<coveragefile>.xml`
`TestResults/Projectb/<coveragefile>.xml`

...unless there's some weird nesting in folders that would allow duplicate project names. That sounds like an edge case that the user would have to fix, though, and in that case you could use GUID folders per duplicated project or something.

**Comment by ArchieCoder** [comment] 2020-12-10 03:57
Spent the evening doing tests here and there trying to understand why I was getting random folders. Glad that I finally found this, but sad this is not implemented. This is definitively not CI/CL friendly.

**Comment by hauntingEcho** [comment] 2021-01-13 17:32
This is also not IDE friendly, as there is no deterministic way to find the most recent result folder.  Coverage highlighting tools (VSCode Coverage Gutters, in my case) can't be effectively configured to work with this behavior.

**Comment by tonyhallett** [comment] 2021-02-21 15:16
dotnet test standard output provides the generated folder name

"Starting test execution, please wait...\r\nLogging Vstest Diagnostics in file: C:\\Users\\tonyh\\Source\\Repos\\DataCollectorXUnit\\XUnitTestProject1\\bin\\Debug\\netcoreapp3.1\\fine-code-coverage\\coverage-tool-output\\diagnostics.log\r\nA total of 1 test files matched the specified pattern.\r\n\r\n
**Attachments**:\r\n  C:\\Users\\tonyh\\Source\\Repos\\DataCollectorXUnit\\XUnitTestProject1\\bin\\Debug\\netcoreapp3.1\\fine-code-coverage\\coverage-tool-output\\**7ba6447d-a89f-4836-bffc-aeb4799e48ab\\coverage.cobertura.xml\**r\nPassed!  - Failed:     0, Passed:     1, Skipped:     0, Total:     1, Duration: 7 ms - XUnitTestProject1.dll (netcoreapp3.1)"

The diagnostic log also has the generated folder name

TpTrace Verbose: 0 : 4712, 10, 2021/02/21, 14:58:38.317, 1073211811845, vstest.console.dll, DataCollectionRequestSender.SendAfterTestRunStartAndGetResult : Received message: (DataCollection.AfterTestRunEndResult) -> [
  {
    "Uri": "datacollector://Microsoft/CoverletCodeCoverage/1.0",
    "DisplayName": "XPlat code coverage",
    "Attachments": [
      {
        "Description": "",
        "Uri": "file://C:/Users/tonyh/Source/Repos/DataCollectorXUnit/XUnitTestProject1/bin/Debug/netcoreapp3.1/fine-code-coverage/coverage-tool-output/7ba6447d-a89f-4836-bffc-aeb4799e48ab/coverage.cobertura.xml"
      }
    ]
  }
]

Agree that should avoid the guid though.

**Comment by psvaiter** [comment] 2021-04-10 06:48
Is there any solution found for this issue?
I'm suffering from the same problem, while msbuild integration allows a specification of ouput dir. Why not vstest?

**Comment by ArchieCoder** [comment] 2021-04-10 10:42
@psvaiter Here is my solution. I call this executable before using the coverage file. The tool search for the coverage file and copy at the specified file path.

`using System;
using System.IO;

namespace CopyCoverageFile
{
    class Program
    {
        static void Main(string[] args)
        {
            if (args.Length == 2)
            {
                var files = Directory.GetFiles(args[0], "*.coverage", SearchOption.AllDirectories);

                var path = Path.Combine(args[1], "YOUR_TEST.coverage");

                Directory.CreateDirectory(args[1]);

                File.Copy(files[0], path);

                Console.WriteLine("Is coverage created? " + File.Exists(path));
            }
            else if (args.Length == 1)
            {
                Console.WriteLine($"Is new {args[0]} exist? " + File.Exists(args[0]));
            }
        }
    }
}`

**Comment by Cobster** [comment] 2021-04-27 15:55
Hoping this may help a few people out there, I use the following snippet of PowerShell in my development scripts to extract the unit test results paths and feed them to report generator.  

```ps1
$TestOutput = dotnet test --collect "XPlat Code Coverage"
$TestReports = $TestOutput | Select-String coverage.cobertura.xml | ForEach-Object { $_.Line.Trim() } | Join-String -Separator ';'
dotnet reportgenerator "-reports:$TestReports" "-targetdir:./CoverageReport" "-reporttype:Html"
```

**Comment by psvaiter** [comment] 2021-04-27 19:01
@ArchieCoder I tried to use MSBuild integration and that worked as expected. Besides that I could use the Fine Code Coverage extension for Visual Studio that seems to depend on coverlet.msbuild package.

Here's the command I run:
```
dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=TestResults\
```

This way I stopped using the vstest.

**Comment by keegandent** [comment] 2021-05-23 07:22
> This is also not IDE friendly, as there is no deterministic way to find the most recent result folder. Coverage highlighting tools (VSCode Coverage Gutters, in my case) can't be effectively configured to work with this behavior.

I am right there with you. I'm not sure what genius though an artifact directory's name should be non-deterministic, but it's completely ludicrous to me. Nobody has, from my reading, presented a single good argument s to why you'd want a GUID for this. I could see the argument for a timestamp, but honestly, if somebody wants their artifacts in a GUID-named folder, **make them do it themselves** as its a lot easier to go deterministic->random than vice-versa. I'm not sure why those who want consistency are the ones being punished.

**Comment by jasonterando** [comment] 2021-11-11 14:37
FWIW, I'm using dotnet and Visual Studio for .NET Core applications.  I wanted to execute my unit tests and generate a coverage report, with log files going into `.results/log` and the coverage report in `.results/report`.  I ended up going the "shell script" route (hey, we're all *nix users with WSL now, right?).  Here's what works for me:

Step #1:  Install Report Generator as a local tool:
```shell
dotnet new tool-manifest
dotnet tool install dotnet-reportgenerator-globaltool
```

Step #2:  Make sure your project has coverlet collector:
```shell
dotnet add package coverlet.collector
```

Step #3:  Create a Bash script file with below contents, tweak to your liking.  Don't forget to **chmod +x** it.  The script creates the .results folder if it does not exist, cleans up any previous files in .results, and then executes unit tests and report generation.  It exits with the exit code from the unit tests, so if you are running this in a CI/CD pipeline, you can continue (or not) if the unit tests pass.

```shell
#!/bin/sh
mkdir -p .results
rm -r -f .results/*
dotnet test --collect:"XPlat Code Coverage" -r .results/log -l trx
result=$?
dotnet reportgenerator -reports:`find .results -name coverage.cobertura.xml` -targetdir:.results/reports
if [ $result = 0 ]; then
    echo "All tests passed!"
else
    echo "Some tests failed :("
fi
exit $result
```

You could get beef this up if you wanted to only exit successfully (exit code of not zero) based upon code coverage, successful report generation, etc. but I have messed with this enough this morning ;)

**Comment by gix** [comment] 2022-01-06 13:47
> A better solution would be to at least use the project name in this scenario.

This is not enough since you can have a test project with multiple target frameworks.

**Comment by f00-beard** [comment] 2022-01-22 07:15
I ran into same issue.
This may help in some cases:
You can deterministically generate a trx log file which contains a partial path and name of the .coverage file using:
`dotnet test --collect:"Code Coverage" --logger "trx;LogFileName=TestResults.trx"`
and you can parse the XML to get the file path using:
```
static string? GetAttachmentPath(string trxPath)
{
    var doc = new XmlDocument();
    doc.Load(trxPath);

    var namespaceManager = new XmlNamespaceManager(doc.NameTable);
    namespaceManager.AddNamespace("vs", "http://microsoft.com/schemas/VisualStudio/TeamTest/2010");

    XmlNode? firstCoverageAttachment = doc.DocumentElement?.SelectSingleNode(
        xpath: @"/vs:TestRun/vs:ResultSummary/vs:CollectorDataEntries/vs:Collector[@uri=""datacollector://microsoft/CodeCoverage/2.0""]/vs:UriAttachments/vs:UriAttachment[1]/vs:A",
        nsmgr: namespaceManager);

    return firstCoverageAttachment?.Attributes?["href"]?.Value;
}
```

**Comment by MarcoRossignoli** [comment] 2022-06-16 13:12
Related issue https://github.com/microsoft/vstest/issues/2334#issuecomment-1156634841

**Comment by ViktorHofer** [comment] 2022-08-03 12:44
@MarcoRossignoli @nohwnd is someone actively working on this? It's still causing unreasonable pain and the issue is upvoted quite a lot. Also, the milestone seems to be incorrect as 17.1 already shipped.

**Comment by Evangelink** [comment] 2022-08-03 13:33
@ViktorHofer We are not working on this. I will bring it up at tomorrow's standup.

**Comment by crojewsk** [comment] 2022-08-20 14:14
Any progress? Everything that needed to be said was said in this topic. User should have an option to set static output directory and given the feedback, pretty sure this should be the default behavior.

Remember that you can always work incrementally on the final solution. First integrate the proposal found here (or anything similar) and then follow up with something neater if an additional option is not something you guys are aiming for.

If this issue is gone, please ignore. Using VS 2022 17.3.1 and the problem is still reproducing with `dotnet test`.

**Comment by crojewsk** [comment] 2022-08-21 14:43
Provided (another?) example of [run script](https://gist.github.com/crojewsk/652a2a1a650d95c1cdf38c1c53deacc9) workarounding this issue. Tested on my Win10 with msys2 and Debian9.

**Comment by ArchieCoder** [comment] 2022-08-21 16:11
I believe the pseudo code for the solution that Microsoft could do is the following code. I have an hard time thinking it would be more complex than this.

var fixedDirectory = String.Empty;

if (args.Contains(“/fixed_directory”))
   fixedDirectory = GetValue(“/fixed_directory”);

// Regular code

if (!string.IsNullOrEmpty(fixedDirectory))
   File.Copy(guidDirectoryFileName, Path.Combine(fixedDirectory, Path.GetFileName(guidDirectoryFileName));

**Comment by bhehe** [comment] 2022-10-10 17:36
Well, I've stumbled into this & the related issues as I'm encountering the same problems. I kept seeing duplicate files in the differing folder names (guid -vs- generated name).  A bit saddened to see this has been an ongoing issue for what looks to be **2+** years now. 

So far, I've seen the suggestion of parsing the TRX file to get the associated coverage file may be an avenue (but definitely not preferred) and then it seems like the other option is that if we know the folder-naming convention for the UserName + HostName prefix variant we could possibly just ignore/purge those as known dupes.

What I wanted to report & share (and maybe get an answer for) is that I have observed some very odd behavior along these lines; In my case I have 6 test projects and I use the **_--results-directory_** argument to point to my desired output path at the repo root (**TestResults**) along with the **_--logger "trx;LogFileName=MyProject.trx"_** argument and that **does** yield the correct/expected behavior.  

But what I've noticed in regard to the code coverage result files is that the GUID-based directory is always present, and the file is always there, **-but-** I have seen the other User/Host name prefixed folders **NOT** get emitted reliably.  And it's random it seems as I've not identified any pattern as to when it fails to emit that variant.

So, add me as **+1** anxiously awaiting a **_good_** solution to this problem space. I'd very much prefer to have more control over both the location where the coverage file is output and the name of it without the need to detect & handle dupes. I realize this may require an effort by both the msft/vstest team and the coverlet team as they're just build atop the provided plumbing.

**Comment by bhehe** [comment] 2022-10-10 18:12
After investigating if parsing the TRX file was something I wanted to pursue using, it looks like that is going to prove to be inadequate as well. In my case the path being mentioned in the 'attachments' is using the host-name - not the GUID-based folders.  So, it's still ambiguous and as I was sharing in my case, I've seen those UserName+HostName folders not getting created reliably.  Seems like I'm basically stuck with the 1 option of just ignoring/purging the folders that follow the UserName+HostName convention.

One question I do have: One of my key concerns is that when you process/analyze the code coverage files there is the notion of a 'hit count' and these dupes would be incrementing that count when they are merged - yielding misleading metrics potentially. Is that a correct assumption?

**Comment by stan-sz** [comment] 2023-02-03 15:25
Sharing the below workaround. Note the single `/*/` glob that will resolve to a direct child folder where the test attachment exists. The other xml files (from other test projects) exist in deeper folders.

```yaml
 - task: PublishCodeCoverageResults@1
   displayName: Publish code coverage from $(Agent.TempDirectory)/*/*.cobertura.xml
   inputs:
     codeCoverageTool: Cobertura
     summaryFileLocation: $(Agent.TempDirectory)/*/*.cobertura.xml
```

**Comment by th3oth3rjak3** [comment] 2023-03-13 01:22
> Hoping this may help a few people out there, I use the following snippet of PowerShell in my development scripts to extract the unit test results paths and feed them to report generator.
> 
> ```powershell
> $TestOutput = dotnet test --collect "XPlat Code Coverage"
> $TestReports = $TestOutput | Select-String coverage.cobertura.xml | ForEach-Object { $_.Line.Trim() } | Join-String -Separator ';'
> dotnet reportgenerator "-reports:$TestReports" "-targetdir:./CoverageReport" "-reporttype:Html"
> ```

I was absolutely struggling with this and I'm so glad that you pasted this in here. Thanks for an easy fix!

**Comment by jachstet-sea** [comment] 2023-04-25 12:46
Instead of using a PowerShell snippet to do the operation "find the file in a random directory and copy it to someplace known", one can simply use a tool that can copy with "wildcard source paths". However, neither `copy`, `xcopy` nor `robocopy` seem to support that. Funnily, `scp` does. And it should be part of any modern Windows installation.

So, make sure you give a known output file name and use scp:
```
vstest.console.exe --logger:trx;LogFileName=%WORKSPACE%\UnitTestResults.trx;verbosity=detailed ^
--collect:"Code Coverage;Format=Xml;CoverageFileName=vstest.coveragexml" /EnableCodeCoverage ^
<YOUR UNIT TEST FILES HERE>

REM Copy the code coverage file to where it is expected
scp TestResults\*\vstest.xml vstest.coveragexml
```

Note, how the Code Coverage collector doesn't even respect the CoverageFileName since it simply changes the file extension... Way to go!

**Comment by Evangelink** [comment] 2023-04-27 08:59
Hi @jachstet-sea,

We discussed these issues and we cannot do much because any change will have consequences on a lot of people. We will keep this issue open in case we can plan some breaking changes in some version.

**Comment by jachstet-sea** [comment] 2023-04-27 09:07
> We discussed these issues and we cannot do much because any change will have consequences on a lot of people. We will keep this issue open in case we can plan some breaking changes in some version.

Thanks for the update :)

**Comment by Evangelink** [comment] 2023-04-27 09:20
Sorry we cannot offer anything better at the moment

**Comment by ArchieCoder** [comment] 2023-04-27 12:50
@Evangelink If adding a parameter would cause the command line tool to break (which I doubt really), did your team consider fork this project and remove the guid creation?

**Comment by 0xced** [comment] 2023-04-29 12:11
Too bad this has not been addressed. In an attempt to workaround this issue and get deterministic output paths I wrote a an MSBuild target that moves files and deletes the directory with the guid. And of course I shot myself in the feet, deleted the wrong directory and now I'm running recovery software. I'm crossing fingers that I can recover my git repository where I had a lot of local branches (and stashes).

**Comment by johnthagen** [comment] 2023-09-06 20:04
After a long amount of searching around, what I had to do to solve this problem (alluded to in previous comments) is to add the following to my `.Tests` `.csproj`:

```xml
<PackageReference Include="coverlet.msbuild" Version="6.0.0"/>
```

And then I had to switch from the following command:

```
dotnet test --collect:"Code Coverage;Format=Cobertura;CoverageFileName=coverage.xml"
```

To:

```
dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput="coverage.xml"
```

**Comment by Bitfiddler** [comment] 2023-09-08 17:40
> After a long amount of searching around, what I had to do to solve this problem (alluded to in previous comments) is to add the following to my `.Tests` `.csproj`:
> 
> ```
> <PackageReference Include="coverlet.msbuild" Version="6.0.0"/>
> ```
> 
> And then I had to switch from the [following command](https://learn.microsoft.com/en-us/visualstudio/test/customizing-code-coverage-analysis?view=vs-2022):
> 
> ```
> dotnet test --collect:"Code Coverage;Format=Cobertura;CoverageFileName=coverage.xml"
> ```
> 
> To:
> 
> ```
> dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput="coverage.xml"
> ```

As long as you don't mind this hanging over your head:
https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/KnownIssues.md

If your use the coverlet.msbuild way of solving this problem, be aware that you may run into this and have to revert to using coverlet.collector and have to deal with the non-deterministic nonsense in the end anyway (like I did).

**Comment by jakubch1** [comment] 2023-09-11 08:58
You can also use [dotnet-coverage](https://aka.ms/dotnet-coverage) tool to resolve this issue:

```
dotnet-coverage collect -f cobertura -o "D:\coverage\report.cobertura.xml" "dotnet test"
```

**Comment by jakubch1** [comment] 2024-01-02 14:35
Check how to use `dotnet-coverage` tool in this scenario:
https://github.com/microsoft/codecoverage/blob/main/samples/Calculator/scenarios/scenario25/README.md

**Comment by nohwnd** [comment] 2024-07-09 08:47
This is a new feature and won't be implemented, we are focusing on adding new features to Testing.Platform instead. https://aka.ms/testingplatform

**Closed by nohwnd** 2024-07-09 08:47 UTC
Labels: In-PR
