### ISSUE TITLE
Error discovering xUnit tests

### ISSUE THREAD

**Issue by lyolikaa** [Microsoft/vstest#896] opened 2017-06-27 07:05 UTC
https://github.com/xunit/xunit/issues/1334

**Comment by codito** [comment] 2017-06-27 10:03
@lyolikaa please share your VS version? Are these netcore tests or net46 tests? Do you have .NET 4.7 installed on machine?

**Comment by codito** [comment] 2017-07-07 12:41
Closing this issue since there isn't enough information to triage or reproduce.

**Closed by codito** 2017-07-07 12:41 UTC
