### ISSUE TITLE
Profile Test is not working in .net core unit test.

### ISSUE THREAD

**Issue by navin22** [Microsoft/vstest#554] opened 2017-03-01 13:22 UTC
## Description
> Profile Test on the unit test method in .Net core unit test project failed with an exception.

## Steps to reproduce
> 1. Create .Net Core Unit Test Project
    2. Build the project
    3. Attach a test explorer.
    4. Right click on the discovered test method and Click on Profile Test.

## Expected behavior
> The test execute smoothly and show the profiled data like CPU time and other details in a graph, like  other desktop unit test project. 

## Actual behavior
> Fails with an exception 
> Exception Details : 
An exception occurred while invoking executor 'executor://mstestadapter/v2': Could not load file or assembly 'Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

## Environment
> VS latest build (d15rel\26228.00)

**Comment by AbhitejJohn** [comment] 2017-03-01 14:59
@navin22 :  Isn't this a bug in the MSTest adapter?

**Comment by codito** [comment] 2017-03-02 04:22
Related to #461 (test explorer doesn't support profiling netcore tests)
Error message is related to https://github.com/Microsoft/vstest/issues/543.

**Comment by codito** [comment] 2017-03-17 02:12
Closing as duplicate of #461.

**Closed by codito** 2017-03-17 02:12 UTC
Labels: bug, exp: ide

**Comment by codito** [comment] 2017-03-17 02:13
See #617.
