### ISSUE TITLE
AppDomain.CreateDomain cannot dynamically load test assembly

### ISSUE THREAD

**Issue by NTaylorMullen** [Microsoft/vstest#419] opened 2017-01-31 22:41 UTC
## Description
Creating an app domain and then having it perform a callback that requires the test assembly to be loaded results in a load failure. This used to work in project.json land.

## Steps to reproduce
- git clone git@github.com:aspnet/Mvc.git
- cd Mvc
- git fetch
- git checkout nimullen/migration.createdomain
- cd test/Microsoft.AspNetCore.Mvc.Core.Test
- dotnet restore
- dotnet test -f net451 --filter "FullyQualifiedName=Microsoft.AspNetCore.Mvc.Infrastructure.ActionContextAccessorTests.ChangingAppDomainsDoesNotBreak_ActionContextAccessor"

## Expected behavior
Test Passes

## Actual behavior
Test fails

## Environment
```
.NET Command Line Tools (1.0.0-rc4-004616)

Product Information:
 Version:            1.0.0-rc4-004616
 Commit SHA-1 hash:  56d8071361

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\nimullen\AppData\Local\Microsoft\dotnet\sdk\1.0.0-rc4-004616
```

**Comment by natemcmaster** [comment] 2017-02-02 01:03
This might be a duplicate of microsoft/vstest#311. I've generally found that errors with AppComain.CreateDomain are solved by using the overload that accepts AppDomainSetup as:
```c#
var setupInfo = new AppDomainSetup
{
   ApplicationBase = AppDomain.CurrentDomain.BaseDirectory
};
var newDomain = AppDomain.CreateDomain("new", null, setupInfo);
```

**Comment by mayankbansal018** [comment] 2018-08-08 07:41
@NTaylorMullen is this bug still relevant, did the work around mentioned above not work for you?

**Comment by NTaylorMullen** [comment] 2018-08-08 18:59
No clue, this was opened ages ago

**Closed** 2018-08-09 09:05 UTC
Labels: bug
