### ISSUE TITLE
Suggest using /Blame when testhost crashes

### ISSUE THREAD

**Issue by kendrahavens** [microsoft/vstest#2396] opened 2020-04-10 00:43 UTC
## Description
We've added a Blame DataCollector that can help identify what test is crashing the testhost, but few users discover it or remember it when they need it. It'd be helpful to suggest running with /Blame in the testhost crash output.

Related to https://github.com/microsoft/vstest/issues/1125
User feedback twitter thread: https://twitter.com/archiecoder/status/1248405123929276420

[AB#1587368](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1587368)

**Comment by dotMorten** [comment] 2020-04-10 15:45
TBH I'm finding the `/Blame` feature by itself rather useless. Knowing which test ran last isn't really that helpful - especially if the crash occurs, it's usually off-thread coming from a finalizer or background thread, so it really could be any previously running test causing it. It doesn't seem to me it gives much more information than the standard output window.

The only Blame command I find useful is `/Blame:CollectDump;CollectAlways=true;DumpType=full`.
However this will fail once a crash occurs, telling that you need to set a `PROCDUMP_PATH` to the folder where procdump.exe resides, and not I have to re-run again and hope that this time I got it right. This is rather poorly documented and the tool doesn't appear to be a part of Visual Studio.
I'd prefer this tool came as part of Visual Studio and vstest.console.exe would by default pick it up.

Also when running for instance UWP unit tests, if UWP crashes all we get is information that the socket communication with the test running was severed - I'd rather by default the process was monitored and we were told a lot more info about why the process exited. In general troubleshooting crashing test runs could use some documentation and tooling love to make it easier for people to find what the problem is.

**Comment by Evangelink** [comment] 2022-08-02 12:51
Note: upon testhost crash (or failure to launch), we want to display a message suggesting to use the blame command.

**Comment by nohwnd** [comment] 2024-07-09 10:18
This is a new feature and won't be implemented, we are focusing on adding new features to Testing.Platform instead. https://aka.ms/testingplatform

**Closed by nohwnd** 2024-07-09 10:18 UTC
Labels: triaged, blame
