### ISSUE TITLE
 VS2017 RC3, tests from one assembly do not show up in TestExplorer

### ISSUE THREAD

**Issue by karolz-ms** [Microsoft/vstest#442] opened 2017-02-04 00:31 UTC
## Description
I am working on converting some ApplicationInsights libraries to VS2017 tooling and on getting them to be built as netstandard1.3 libraries, so that we can target both full framework as well as .NET Core using single binary. As part of that effort I also need to convert relevant test assemblies (since they use project references to project with code that is subject to these tests).

I did that for one recently introduced assembly (EventSourceListener) and its respective test assembly, but even though everything seems to be building fine, the tests from the converted assembly do not show up in TestExplorer. 

## Steps to reproduce
1. Install VS 2017 RC3 d15rel build 26130.00 or later
2. Clone repo https://github.com/karolz-ms/ApplicationInsights-dotnet-logging/tree/msbuild15
3. Do 'buildDebug.cmd' in the root of the repo--this will restore all the NuGet packages
4. Open Logging.sln in VS, build solution again, look at the Test Explorer

## Expected behavior
See tests from EventSource.Net46.Tests project (https://github.com/karolz-ms/ApplicationInsights-dotnet-logging/blob/msbuild15/src/Adapters.Tests/EventSource.Net46.Tests/EventSource.Net46.Tests.csproj)

## Actual behavior
No tests from EventSource.Net46.Tests project are visible

## Environment
I only tried this on Windows 10 64bit.

**Comment by karolz-ms** [comment] 2017-02-04 00:31
I also tried 'dotnet test'. I had to do some hacking to run it (several projects in my solution are using a code-based task (CodeTaskFactory), which is not supported with .NET Core, so I had to disable it in Global.targets). After that “dotnet test” fails with the following error:

C:\code\ApplicationInsights-dotnet-logging-karolz\src\Adapters.Tests\EventSource.Net46.Tests>dotnet test -d:log.txt
Build started, please wait...
Build completed.

Test run for C:\code\bin\Debug\src\Adapters.Tests\EventSource.Net46.Tests\netcoreapp1.0\Microsoft.ApplicationInsights.EventSource.Net46.Tests.dll(.NETCoreApp,Version=v1.0)
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Error: Could not find testhost.dll for source 'C:\code\bin\Debug\src\Adapters.Tests\EventSource.Net46.Tests\netcoreapp1.0\Microsoft.ApplicationInsights.EventSource.Net46.Tests.dll'. Make sure test project has a nuget reference of package "microsoft.testplatform.testhost".

**Comment by karolz-ms** [comment] 2017-02-07 16:30
After changing the <OutputType> setting in the test project to "Exe" (thanks @singhsarab) I can run dotnet tests without an error, but no tests are discovered in the resulting assembly. Same issue remains with VS TestExplorer window.

I have upgraded to VS RC3 26205.00 drop, still no luck.

**Comment by codito** [comment] 2017-02-08 07:17
*Update from @singhsarab in email thread*

RCA :
The test runner is not able to find the testadapter. The test runner looks for testadapter in the same location as the test dll.
For some reason(Karol is looking into it), the testadapter dll is not getting copied to the output directory although the test adapter package is included (and ideally it should get copied via props file).

Copying the testadapter and running the tests worked, I am not sure if that is a good workaround.

Karol will be looking into further and update us.

**Comment by tmat** [comment] 2017-02-09 02:07
Any progress? I'm hitting this issue as well

**Comment by karolz-ms** [comment] 2017-02-09 17:24
Will take a look today, stay tuned

**Comment by karolz-ms** [comment] 2017-02-09 22:31
I have narrowed it down to redefinition of BaseIntermediateOutputPath in project properties. If that variable is not redefined, the test adapter is copied to the output directory as expected and tests are visible in VS.

AI environment redefines BaseIntermediateOutputPath as follows:
`<BaseIntermediateOutputPath>$(EnlistmentRoot)\..\obj\$(MSBuildProjectName)</BaseIntermediateOutputPath>
<BaseIntermediateOutputPath>$([System.IO.Path]::GetFullPath( $(BaseIntermediateOutputPath) ))</BaseIntermediateOutputPath>
`
Something places `<project-name>.csproj.nuget.g.props` and `<project-name>csproj.nuget.g.targets` in this folder. The props file loads MSTest.TestAdapter.props:
`<Import Project="$(NuGetPackageRoot)mstest.testadapter\1.1.10-rc2\build\netstandard1.0\MSTest.TestAdapter.props" Condition="Exists('$(NuGetPackageRoot)mstest.testadapter\1.1.10-rc2\build\netstandard1.0\MSTest.TestAdapter.props')" />`

MSTest.TestAdapter.props is the file that instructs the test adapter DLLs to be copied to the output folder.

If BaseIntermediateOutputPath is not set, there will be an obj folder created under the project folder. It will contain project.assets.json as well as nuget.g.props and nuget.g.targets files.
If the BaseIntermediateOutputPath is set, the obj folder will be created where BaseIntermediateOutputPath points to. It will have the project.assets.json, nuget.g.props and nuget.g.targets files, but for some reason the nuget.g.props file does not seem to be picked up.

This is the second time I am having trouble with a project that has BaseIntermediateOutputPath redefined, see https://github.com/dotnet/sdk/issues/760 I am starting to think it is just a bad idea in general--our default targets seem to be very fragile to any changes to this variable.

**Comment by tmat** [comment] 2017-02-09 22:51
@karolz-ms Yes, one needs to be careful about setting this variable. Incidentally, we are currently trying to figure out rules that everyone who changes it (and other msbuild output variables) and wants VS features like Live Unit Testing to work should follow. We will post some blog post at some point. Long term we are thinking about a "strict" mode in msbuild that would enforce these rules (if the user opts into them).

That said, there might be bugs in the SDK. Will look into this.

**Comment by karolz-ms** [comment] 2017-02-09 23:00
@tmat Thanks! Makes sense. Do you want me to open an SDK issue for this?

Otherwise I am inclined to close this issue because it does not seem to be specific to MSTest

**Comment by tmat** [comment] 2017-02-09 23:56
@karolz-ms 
When I create a new .NET Core xUnit Test project I see this in the generated .props file:
```
    <Import Project="$(NuGetPackageRoot)xunit.runner.visualstudio\2.2.0-beta5-build1225\build\netcoreapp1.0\xunit.runner.visualstudio.props" Condition="Exists('$(NuGetPackageRoot)xunit.runner.visualstudio\2.2.0-beta5-build1225\build\netcoreapp1.0\xunit.runner.visualstudio.props')" />
    <Import Project="$(NuGetPackageRoot)microsoft.net.test.sdk\15.0.0-preview-20170125-04\build\netcoreapp1.0\Microsoft.Net.Test.Sdk.props" Condition="Exists('$(NuGetPackageRoot)microsoft.net.test.sdk\15.0.0-preview-20170125-04\build\netcoreapp1.0\Microsoft.Net.Test.Sdk.props')" />
```

I don't see mstest.testadapter.

**Comment by tmat** [comment] 2017-02-09 23:59
OK, i'm using xUnit in my repo. So It's not just MSTest.

**Comment by tmat** [comment] 2017-02-10 01:05
OK, I have figured it out. In my case it was a missing trailing ```\``` in NuGetPackageRoot, which I defined in my props file and it overrode the one the SDK is using. :(

**Comment by codito** [comment] 2017-02-14 15:00
Closing this issue since the root causes are external to test platform. Tracking diagnosability in #488.

**Closed by codito** 2017-02-14 15:00 UTC
Labels: blocking partner, exp: ide

**Comment by caleblloyd** [comment] 2017-02-22 21:49
@karolz-ms @codito was an SDK issue ever opened for this?  I am also getting this error if `BaseIntermediateOutputPath` is set

**Comment by karolz-ms** [comment] 2017-02-23 18:54
@caleblloyd Yes, https://github.com/dotnet/sdk/issues/760
