### ISSUE TITLE
Show meaningful error message in `Main` for test projects

### ISSUE THREAD

**Issue by TheRealPiotrP** [Microsoft/vstest#367] opened 2017-01-20 07:59 UTC
This is a digest of https://github.com/dotnet/cli/issues/3505 opened by @chrisboh

----

If a user runs `dotnet run` on a test project we should guide them to run `dotnet test` instead. We can do this by having the `Main` method in the auto-generated `Program.cs` print a useful message e.g.

```
  public void Main(string [] args)
  {
      Console.WriteLine("Test projects like this one are not intended to be executed directly. Instead, run the tests in this project by invoking `dotnet {appropriate instructions}`");
  }
```

/cc @blackdwarf

**Comment by smadala** [comment] 2018-08-09 12:43
Dupe of https://github.com/Microsoft/vstest/issues/946

**Closed by smadala** 2018-08-09 12:43 UTC
Labels: enhancement, exp: cli
