### ISSUE TITLE
dotnet test on a multi-target projects logs only the last target

### ISSUE THREAD

**Issue by SidShetye** [microsoft/vstest#1603] opened 2018-05-17 03:30 UTC
## Description
`dotnet test "--logger:trx;LogFileName=results.trx"` on a multi-target project (e.g. `<TargetFrameworks>netcoreapp2.0;net45</TargetFrameworks>` in the `.csproj`) causes the logger to only log the last target. Possibly because the previous targets' logger output file is overwritten by subsequent targets. FYI, this also happens with the [nunit logger extension](https://github.com/Faizan2304/LoggerExtensions).

## Steps to reproduce

`dotnet test "--logger:trx;LogFileName=results.trx"`

## Expected behavior
Either generate as many .trx files as there are targets (e.g. `results.net45.trx`, `results.netcoreapp2.0.trx`) OR assemble the results into the single .trx (if file format allows for it). Perhaps the user can pick a behavior.

## Actual behavior
Only a single `results.trx` is created and it's contents only hold the results of the last target framework in the `.csproj`.

## Environment
In case it matters, our multi-target project uses nunit 3.9 with the the following inside it's `.csproj`
```
<PackageReference Include="NUnit" Version="3.9.0" />
<PackageReference Include="NUnit3TestAdapter" Version="3.9.0" />
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.3.0" />
<PackageReference Include="NunitXml.TestLogger" Version="1.1.0" />
``` 
that last bit is so we can also do `dotnet test --logger:"nunit;LogFilePath=results.xml"` since our CI can use either trx or nunit xml - but that also fails similarly.

OS: Windows 10 v1803
.NET SDK: `dotnet --version` shows `2.1.0`
Not sure if/how dotnet test wraps over vstest but this is `vstest.console.exe`
```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow>vstest.console.exe
Microsoft (R) Test Execution Command Line Tool Version 15.7.1
Copyright (c) Microsoft Corporation.  All rights reserved.
```

**Comment by sidshetye** [comment] 2018-05-24 23:27
Any news?

**Comment by sidshetye** [comment] 2018-05-24 23:28
Any news? Seems awfully similar to this https://github.com/Microsoft/vstest/issues/243

**Comment by sidshetye** [comment] 2018-05-25 00:02
Note that running just `dotnet test "--logger:trx"` causes it to generate unique filenames in a pattern like `<username>_<machine>_YYYY-MM-DD_HH_MM_SS.trx` but that's distinct from the reported problem.

**Comment by singhsarab** [comment] 2018-05-28 08:11
@sidshetye Thanks for the feedback. This does not seem to be a regression.

@pvlakshm What do you think the spec should be for this one?

**Comment by abhishkk** [comment] 2018-12-28 11:40
Merged: https://github.com/Microsoft/vstest/pull/1877

**Comment by StephenCleary** [comment] 2019-05-08 19:33
Please reopen, since the fix for this has been reverted.

**Comment by vagisha-nidhi** [comment] 2019-08-14 10:59
@SidShetye @StephenCleary We are revisiting the scenario and would appreciate your inputs on the spec. Here is the [RFC](https://github.com/vagisha-nidhi/vstest-docs/blob/multiTargetTrxRFC/RFCs/0028-Dotnet-Test-MultiTarget-Project-Trx-Logger.md) I have posted. Let me know if there are any concerns.

**Comment by singhsarab** [comment] 2019-09-16 09:16
The fix for this has been released. https://www.nuget.org/packages/Microsoft.TestPlatform/16.3.0-preview-20190828-03

We advice folks to use LogFilePrefix argument instead.

**Closed by singhsarab** 2019-09-16 09:16 UTC
Labels: bug
