### ISSUE TITLE
vstest.console is very slow with xunit tests in large numbers.

### ISSUE THREAD

**Issue by navin22** [Microsoft/vstest#246] opened 2016-11-24 12:29 UTC
## Description
> vstest.console.exe takes around 31 Minutes to execute 9K xunit tests. Where as xunit.console.exe takes around 2 Seconds to execute.

## Steps to reproduce
> Open \\navbdevenv\share\Xunit9Ktests\XunitTests9K.sln. And build the project.
> Figure out the extension folder of TP V2.
> Execute the XunitTests9K.dll from VsTest.Console.exe.

## Expected behavior
> Should be as fast as possible.

## Actual behavior
> Takes around 31 Minutes in Average.

## Environment
> d15rel\15.0.25914.0

##Note
> Execute the XUnitTests9K.dll using Xunit.Console.exe. It takes just 2 seconds.

**Comment by onovotny** [comment] 2017-01-20 04:00
One significant issue we've seen is that the console output is slow. VSTest.Console currently outputs `Passed`, `Failed`, or `Skipped` for each item. 

This is semi-related to a separate issue where I want to fully control everything that the console outputs and in what format, color, etc. I want the `vstest.console.exe` output to look the same as `xunit.console.exe`.

**Comment by codito** [comment] 2017-03-20 12:14
Duplicate of #349

**Closed by codito** 2017-03-20 12:14 UTC
Labels: bug, perf
