### ISSUE TITLE
 Azure Dev-ops Pipeline VsTest Task  taking longer time and failing

### ISSUE THREAD

**Issue by SuryaPractise** [microsoft/vstest#2449] opened 2020-06-03 08:42 UTC
[CIsnapshots.docx](https://github.com/microsoft/vstest/files/4723150/CIsnapshots.docx)
Hi Team,

## Description
When CI pipeline runs and execute Vs-test task it taking longer time to execute.In our setup task used to run within 2 minutes but from yesterday evening(06/02/2020) we are observing it taking longer time and fails.

## Steps to reproduce
Azure Devops Pipeline with Vs-test task

## Expected behavior
Vs-test task supposed to finish execution within 2 minutes.

## Actual behavior
When logs analysed found below errors

##[error]vstest.console process failed to connect to testhost process after 90 seconds. This may occur due to machine slowness, please set environment variable VSTEST_CONNECTION_TIMEOUT to increase timeout.
##[debug]Processed: ##vso[task.logissue type=error;]vstest.console process failed to connect to testhost process after 90 seconds. This may occur due to machine slowness, please set environment variable VSTEST_CONNECTION_TIMEOUT to increase timeout.
Microsoft (R) Coverage Collection Tool Version 15.0.30319.200

## Diagnostic logs
Please feel free for any logs to verify issue

## Environment
Windows server,Development environment

**Comment by SuryaPractise** [comment] 2020-06-05 04:15
Hi Team any luck?

**Comment by nohwnd** [comment] 2020-06-05 12:55
Which version of Test Platform are you on? You should see line similar to this in your output: 

Microsoft (R) Test Execution Command Line Tool Version 16.xxx

**Comment by SuryaPractise** [comment] 2020-06-08 03:46
Hi nohwnd,

Its  Microsoft (R) Test Execution Command Line Tool Version 15.9.0

**Comment by SuryaPractise** [comment] 2020-06-09 06:41
Team,Any luck?

**Comment by nohwnd** [comment] 2020-06-09 14:06
This is unlikely to be caused by an update in test platform, because your version is quite old. The current stable version is 16.6.1. 15.9.0 is from October 2018. Is is it possible that your infrastructure changed in any other way than updating test platform?

**Comment by SuryaPractise** [comment] 2020-06-09 14:17
I am not sure on upgrade,can you let me know how to upgrade VsTest?

**Comment by nohwnd** [comment] 2020-06-09 14:20
That depends on what you are using to build your projects, if you are using .net framework projects then you would need to update the version of Visual Studio you use to build them. If you are using .net core you would update the .net core version you use to build them and Microsoft.NET.Test.SDK nuget package.

**Comment by SuryaPractise** [comment] 2020-06-09 14:28
.net MVC based project

**Comment by nohwnd** [comment] 2020-06-09 14:36
I think those can be both .NET Framework and dotnet core based.

**Comment by Evangelink** [comment] 2022-08-01 10:12
@SuryaPractise Have you managed to update to newer version of the Test Platform? If so, is the issue fixed?

**Comment by Evangelink** [comment] 2022-08-22 11:35
Closing this issue. Feel free to ping us if you are still experiencing any issue.

**Closed by Evangelink** 2022-08-22 11:35 UTC
