### ISSUE TITLE
Solution Explorer glyph should change for unit test projects

### ISSUE THREAD

**Issue by sharwell** [Microsoft/vstest#908] opened 2017-06-30 21:17 UTC
### Description

Solution Explorer should reflect unit test projects with a unique glyph.

:link: Originally found in dotnet/roslyn#18363
:link: Related to dotnet/roslyn#20571

### Steps to reproduce

Create a unit test project with the new project system. Add the `UnitTestContainer` capability (e.g. by installing [xunit.runner.visualstudio 2.3.0-beta2-build1317](https://www.nuget.org/packages/xunit.runner.visualstudio/2.3.0-beta2-build1317) or newer).

### Expected behavior

Solution Explorer should show a different glyph for the unit test project.

### Actual behavior

Solution Explorer shows the unit test project as a normal project.

This is a regression against unit test cases written using the old project system, where the `ProjectTypeGuids` could include `{3AC096D0-A1C2-E12C-1390-A8335801FDAB}`.

**Comment by Faizan2304** [comment] 2017-07-04 12:27
It seems dupe of bug https://devdiv.visualstudio.com/DevDiv/_workitems?id=457621&_a=edit

**Comment by sharwell** [comment] 2017-07-05 03:48
@Faizan2304 If this feature will be implemented in this repository (or another open source repository), the feedback item can be closed as a duplicate of this issue. Otherwise, if the feature will be implemented in closed source code, this issue can be closed as a duplicate of the tracking issue for that closed-source code base.

:memo: For non-Microsoft employees, the above link is just the internal tracking issue automatically created for [this feedback item](https://developercommunity.visualstudio.com/content/problem/73650/net-core-unit-test-projects-dont-get-the-unit-test.html).

**Comment by Faizan2304** [comment] 2017-07-06 05:38
@sharwell This feature will be implemented in visual studio code base which is a closed source code. 
You are right, I should close it as a dupe of above bug.

**Closed by Faizan2304** 2017-07-06 05:38 UTC
