### ISSUE TITLE
Service added to ItemGroup

### ISSUE THREAD

**Issue by rm2k** [Microsoft/vstest#668] opened 2017-03-28 07:38 UTC
## Description
> Describe the issue you've observed

Running tests in visual studio 2017 add the following in test project `*.csproj`. Is this normal? what is Service?

      <ItemGroup>
          <Service Include="{82a7f48d-3b50-4b1e-b82e-3ada8210c358}" />
     </ItemGroup>

## Steps to reproduce
> What steps can reproduce the defect?

Create a new console project, and create a new test project, either `mstest` or `xunit` project.

Build the solution to discover the tests. Run all the tests, and the snipped is added to the project file.

> Please share the setup, commandline for vstest.console, sample project, target

Test `*.csproj`

    <Project Sdk="Microsoft.NET.Sdk">

        <PropertyGroup>    
            <TargetFramework>netcoreapp1.1</TargetFramework>
        </PropertyGroup>

       <ItemGroup>
           <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
          <PackageReference Include="MSTest.TestAdapter" Version="1.1.11" />
          <PackageReference Include="MSTest.TestFramework" Version="1.1.11" />
       </ItemGroup>

    </Project>

> framework etc.

## Expected behavior
> Share the expected output

nothing to be added to the project file.
## Actual behavior
> What is the behavior observed?

This happen for both `mstest` and `xunit` test projects.

    <Project Sdk="Microsoft.NET.Sdk">

        <PropertyGroup>    
            <TargetFramework>netcoreapp1.1</TargetFramework>
        </PropertyGroup>

       <ItemGroup>
           <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
          <PackageReference Include="MSTest.TestAdapter" Version="1.1.11" />
          <PackageReference Include="MSTest.TestFramework" Version="1.1.11" />
       </ItemGroup>

       <ItemGroup>
          <Service Include="{82a7f48d-3b50-4b1e-b82e-3ada8210c358}" />
       </ItemGroup>

    </Project>

## Environment
> Please share additional details about the test environment.
> Operating system, Build version of vstest.console

**Comment by davkean** [comment] 2017-03-30 09:03
@Faizan2304 This is a dupe of https://github.com/Microsoft/vstest/issues/472.

**Comment by Faizan2304** [comment] 2017-03-30 13:10
@davkean : Yes this is a dupe of https://github.com/Microsoft/vstest/issues/472
@rm2k : I am closing this bug as we are tracking it through https://github.com/Microsoft/vstest/issues/472

**Closed by Faizan2304** 2017-03-30 13:10 UTC
Labels: question
