### ISSUE TITLE
Can Newtonsoft.Json get updated to 11.x or 12.x?

### ISSUE THREAD

**Issue by lg2de** [microsoft/vstest#2316] opened 2020-02-03 14:52 UTC
The package `Microsoft.TestPlatform.TestHost` has a dependency on `Newtonsoft.Json`, for target framework `.NETCoreApp 2.1` it refers to version 9.0.1.

Would be possible to update the reference to at least version 11.x.

**Why?**
The package `Newtonsoft.Json` in version 9.0.1 has no target framework for .NETCore >= 2 or .NETStandard >= 2. When restoring packages for the solution, the direct dependency to `Microsoft.NET.Test.Sdk` causes indirect dependencies for several compatibility packages (e.g. `System.Text.Encoding`). This is because the latest target framework of `Newtonsoft.Json` is `.NETStandard 1.0`.
When forcing `Newtonsoft.Json` to version 11.0.2 in the project, the compatibility packages are not required and not restored.

We are using .net core 3.x and we want to limit the list of nuget packages in our internal package feed due to license review process. This is why we don't want to have all the small compatibility packages in our feed.

**Comment by nohwnd** [comment] 2020-02-03 17:28
I think we will try to drop the dependency on Newtonsoft.Json and migrate to System.Text.Json. I did not have a chance to see how difficult that change will be, but hopefully not much. Would that help you with your review process?

**Comment by lg2de** [comment] 2020-02-04 08:11
Yes, for the future this looks like a good solution.

I took a short look into the current usage of Newtonsoft.Json. I think it will take a lot of effort to replace it.

So, maybe it would be easier to upgrade the referenced version.

**Comment by nohwnd** [comment] 2020-02-04 14:43
I quickly tried to replace the library and ran into many issues with projects still using netcoreapp1.0 I think we need to do a a major cleanup either way, because System.Text.Json does not support net451 and so on. 

I need to clear up which versions we should be using and see what the impact is in either case.

**Comment by lg2de** [comment] 2020-02-05 10:21
Updating to Newtonsoft.Json 11.0.2 looks very easy. Could this be added to 16.5.0?
For e.g. 17.0 you may schedule switch to System.Text.Json.

**Comment by nohwnd** [comment] 2020-02-05 10:58
It can't 16.5.0 was released this morning. I am not sure what the release cadence is here, but imho this should be okay for patch release. I can talk with the team about 16.5.1, or at worst getting it into 16.6.0. We already agreed on using milestones here and in testfx so hopefully the process will be more transparent to you and others once we put that into practice.

**Comment by nohwnd** [comment] 2020-02-13 12:35
@lg2de I did not have a chance to look into this yet, would you consider implementing this to see what the actual impact will be, and PRing? Then we can get it to 16.6, but otherwise this will not get in as we are focusing on performance and regressions in this sprint.

**Comment by lg2de** [comment] 2020-02-13 16:48
The PR is created, @nohwnd.
Currently some build steps fail because they are (still) referring to Newtonsoft.Json 9.0.0. So far I could not identify where this expectation is coming from.

**Comment by plioi** [comment] 2020-02-27 16:09
Is this really related to #2279? Why should consumers of a test framework experience VSTest's own internal dependencies in any way?

**Comment by ViktorHofer** [comment] 2020-03-12 09:36
We deliberately didn't update the `Newtonsoft.Json`'s version as that will force test projects to at least target VSTest's version. With AssemblyLoadContext and/or System.Text.Json this issue should go away.

**Comment by plioi** [comment] 2020-03-12 13:47
@ViktorHofer Is there any hope of VsTest running discovery/execution from within the nuget packages folder rather than polluting the build output folder, long term? In the linked issue above, there was evidence that it was only touching the build output folder at discovery time, so fixing the root cause seems plausible.

I fear there's going to be a lot of treating-the-symptoms. This all seems to be downstream side effects from the decision to have the Test SDK work by overwriting the system under test, which is making me consider recommending that folks never use Test Explorer or dotnet test.

**Comment by ViktorHofer** [comment] 2020-03-12 14:33
> to have the Test SDK work by overwriting the system under test

Sorry can't follow, can you please ellaborate?

> Is there any hope of VsTest running discovery/execution from within the nuget packages folder rather than polluting the build output folder, long term?

This sounds like a feature request. If it's feasible and make the product better, sure why not. Can you please create a new issue for that?

**Comment by plioi** [comment] 2020-03-12 14:49
I think #2279 covers both questions.

**Comment by ezgambac** [comment] 2022-04-26 21:54
This is still broken, and it's breaking source generator development when doing tests in azure dev ops in windows.
It's 2022, newtonsoft is already at version 13, and version 9 is from 2016, 6 years old and deprecated, yet this issue persists even with v17 of vstest.

**Comment by nohwnd** [comment] 2022-05-03 10:45
We are keeping an old version to avoid upgrading tested projects to the newest version. Believe me I would like to upgrade it to the latest, but I can't because of back-compat.

**Comment by lg2de** [comment] 2022-05-03 11:14
How about adding new version for next target framework?

If you plan to switch to System.Text.Json, what is the difference in terms of backward compatibility?

**Comment by plioi** [comment] 2022-05-03 13:55
The JSON dependency issue is just a symptom of a much deeper problem ( #2279 ). As long as the discussion is about "what to do about Newtonsoft.Json" then there's absolutely no hope of the real problem being addressed.

There is no defensible reason for vstest to drop half of its own implementation details on top of the test project's own build output folder. It should not matter what version of Newtonsoft VS happens to use internally for internal purposes. It wasn't always like that. It started happening sometime around .net core 3. Newtonsoft is just the most noticable symptom of the problem because so many end users coincidenally need a dll of the same name at runtime, and it's one of the implementation details that vstest accidentally copy/pastes on top of end user build output.

When I type in the VS text editor, the VS text editor's implementation details don't get dumped on top of my build output. When I run under the debugger, the debugger's implementation details don't get dumped on top of my build output. Vstest is the only thing that does so.

There's evidence ( https://github.com/microsoft/vstest/issues/2279#issuecomment-663762099 ) that we're hitting what was *supposed* to be a fallback edge case of looking for dependencies in the build output folder, as seen in that other thread. It was *supposed* to be finding the run-time dependencies over in the nuget cache, and that even appears to be the case during *discovery* but (unintentionally) not *execution*. If it went back to doing things like it did originally, then TestAdapter plugins would have the freedom to interact with the test assembly and its own dependencies the way they see fit, with no need for random dlls and other support files to be copy/pasted from vstest on top of the system being tested.

I'm honestly surprised this hasn't been a big deal-breaker internally at Microsoft. All .NET testing in the presence of vstest is suspect as it bears no resemblence to the dlls that will be shipped after a passing build.

All in all, VSTest should not use the test project's build output folder for its own needs. The test project's build output folder is sacrosanct and does not belong to VSTest.

**Comment by nohwnd** [comment] 2022-05-03 14:37
@plioi What you talk about is also a symptom of a much deeper problem. It does not matter if we load Newtonsoft.Json from nuget cache of your output folder. (Unless your tests count the number of dlls in the bin or something). It will end up being loaded into the same process, and there is currently no isolation for running tests, in neither .NET and .NET Framework testhost. There is isolation into appdomains for Discovery, but not for Run (AFAIK). 

So as far as I can say, it was always like that, at least since json serialization was used for IPC. And it is not a huge deal breaker, because you are free to upgrade to a newer version of the library by referencing it, or by getting it from transitive dependencies. On the other hand if we upgrade our shipped version, we might force your project to be different from what you intended it to be, that is why we are sticking to version 9, and our only other library dependency is nuget.frameworks.

The only solution to this would be adding isolation on the ObjectModel level, cutting out all additional dependencies from ObjectModel and only present that to the isolated test dll. That way test adapters, test frameworks and SUT are able to run the test independently from test platform.

**Comment by plioi** [comment] 2022-05-03 14:41
Test frameworks are free to kick off test running in their own process. Only the TestAdapter needs to be "stuck" with the original process.

**Comment by nohwnd** [comment] 2022-05-03 14:41
One more comment on the resolving of testhost. Resolving from bin is now the primary way, because it is faster, relies less on parsing of deps.json which has a bunch of edge cases. And it also allows test projects that are built with RID to run, without us providing additional deps paths, and additional deps files.

**Comment by nohwnd** [comment] 2022-05-03 14:43
> Test frameworks are free to kick off test running in their own process. Only the TestAdapter needs to be "stuck" with the original process.

Sure, but then then need to somehow communicate the results back, and if they use any serialization or communication library for that, they are back in square 1.

**Comment by plioi** [comment] 2022-05-03 14:46
Agreed. Fixie for example farms out to a separate process and uses the built-in json parser to send messages between the processes over a named pipe. The test assembly is free to load any real dependencies it wants, *except* for those trampled by vstest.

**Comment by nohwnd** [comment] 2022-05-03 14:47
But we (vstest) don't trample any dependencies. If your projects selects higher version, the higher version is used.

**Comment by nohwnd** [comment] 2022-05-03 15:31
How can it trample what is not there? And if it is there, and uses newer version, that is then used. What is the real harm?

**Comment by nohwnd** [comment] 2022-05-04 13:33
FWIW I took some time to upgrade TP to System.Text.Json again, and there are few major issues, most importantly there is no support for *DataMember attributes, which would force us to (1) annotate our models in ObjectModel with attributes from system.text.json. Or duplicate the type (2) definitions, and convert them after deserialization. 

We definitely don't want to do (1). (2) might be feasible with some cs file linking magic, and compiler attributes. Still there would be overhead of creating each object twice. Or maybe inheritance could be used, but it is all pretty brittle. :/

**Comment by nohwnd** [comment] 2022-06-28 14:13
@AArnott trying to do that in #3815

**Closed** 2022-06-30 09:34 UTC
