### ISSUE TITLE
Dependency issue in 17.1 (Microsoft.VisualStudio.CodeCoverage.Shim)

### ISSUE THREAD

**Issue by gthvidsten** [microsoft/vstest#3382] opened 2022-02-17 09:39 UTC
## Description

17.1 breaks dependency on Microsoft.VisualStudio.CodeCoverage.Shim (15.0.0.0)
Tests running just fine in 17.0
Switching to 17.1 makes the tests suddenly throw an exception about the above dependency not being able to load.

## Steps to reproduce

I don't know what is really causing this.
This is how our task in the DevOps pipeline is set up:
```
steps:
- task: VisualStudioTestPlatformInstaller@1
  displayName: 'Visual Studio Test Platform Installer'
  inputs:
    versionSelector: specificVersion
    testPlatformVersion: 17.0
- task: VSTest@2
  displayName: 'Unit test solution'
  inputs:
    testAssemblyVer2: |
     **\*UnitTests.dll
     !**\obj\**
    vsTestVersion: toolsInstaller
    codeCoverageEnabled: true
```

Target framework: .NET Framework 4.8
DevOps Build Agent: Self hosted

## Expected behavior

Expect tests to run just as fine with 17.1 as with 17.0

## Actual behavior

The following exception is thrown in 17.1, not in 17.0:

> ##[error][xUnit.net 00:00:05.93] Our.UnitTests: Catastrophic failure: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.CodeCoverage.Shim, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
##[error]File name: 'Microsoft.VisualStudio.CodeCoverage.Shim, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
##[error]   at Xunit.DiaSessionWrapperHelper..ctor(String assemblyFileName)   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
##[error]   at ExceptionExtensions.RethrowWithNoStackTraceLoss(Exception ex) in C:\Dev\xunit\xunit\src\common\ExceptionExtensions.cs:line 29
##[error]   at Xunit.AppDomainManager_AppDomain.CreateObject[TObject](AssemblyName assemblyName, String typeName, Object[] args) in C:\Dev\xunit\xunit\src\xunit.runner.utility\AppDomain\AppDomainManager_AppDomain.cs:line 85
##[error]   at Xunit.DiaSessionWrapper..ctor(String assemblyFilename) in C:\Dev\xunit\xunit\src\xunit.runner.utility\Utility\DiaSessionWrapper.cs:line 22
##[error]   at Xunit.VisualStudioSourceInformationProvider..ctor(String assemblyFileName) in C:\Dev\xunit\xunit\src\xunit.runner.utility\Frameworks\VisualStudioSourceInformationProvider.cs:line 24
##[error]   at Xunit.XunitFrontController..ctor(AppDomainSupport appDomainSupport, String assemblyFileName, String configFileName, Boolean shadowCopy, String shadowCopyFolder, ISourceInformationProvider sourceInformationProvider, IMessageSink diagnosticMessageSink) in C:\Dev\xunit\xunit\src\xunit.runner.utility\Frameworks\XunitFrontController.cs:line 70
##[error]   at Xunit.Runner.VisualStudio.VsTestRunner.RunTestsInAssembly(IRunContext runContext, IFrameworkHandle frameworkHandle, LoggerHelper logger, TestPlatformContext testPlatformContext, RunSettings runSettings, IMessageSinkWithTypes reporterMessageHandler, AssemblyRunInfo runInfo) in /_/src/xunit.runner.visualstudio/VsTestRunner.cs:line 498

## Diagnostic logs

As this is observed only in our DevOps pipeline, getting these logs is not easily done.

## Environment

Operating System: Windows Server 2019

vstest.console:
```
Microsoft (R) Test Execution Command Line Tool Version 17.1.0
Copyright (c) Microsoft Corporation.  All rights reserved.
vstest.console.exe "C:\VSTSAgent\_work\9\s\Tests\Our.UnitTests\bin\Release\Our.UnitTests.dll"
"C:\VSTSAgent\_work\9\s\Tests\Our.Services.UnitTests\bin\Release\Our.Services.UnitTests.dll"
/Settings:"C:\VSTSAgent\_work\_temp\kxszxmgj3no.tmp.runsettings"
/Logger:"trx"
/TestAdapterPath:"C:\VSTSAgent\_work\9\s"
```

I know the stack trace above points to Xunit, and it may seem the error lies with them, but seeing as this happens when changing the vstest version it's likely not an Xunit issue. Changing vstest from 17.0 to 17.1 should not result in breaking changes.

**Comment by Haplois** [comment] 2022-02-17 10:00
@jakubch1 can you look into this?

**Comment by jakubch1** [comment] 2022-02-17 15:12
@gthvidsten we will investigate this issue. As workaround you can try to add runsettings and with content:

```
<?xml version="1.0" encoding="utf-8"?>
<!-- File name extension must be .runsettings -->
<RunSettings>
  <DataCollectionRunSettings>
    <DataCollectors>
      <DataCollector friendlyName="Code Coverage" uri="datacollector://Microsoft/CodeCoverage/2.0" assemblyQualifiedName="Microsoft.VisualStudio.Coverage.DynamicCoverageDataCollector, Microsoft.VisualStudio.TraceCollector, Version=11.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a">
        <Configuration>
          <CodeCoverage>
            <UseVerifiableInstrumentation>False</UseVerifiableInstrumentation>
          </CodeCoverage>
        </Configuration>
      </DataCollector>
    </DataCollectors>
  </DataCollectionRunSettings>
</RunSettings>
```

**Comment by jakubch1** [comment] 2022-02-17 15:14
Please check: https://github.com/microsoft/vstest/issues/1654

**Comment by rkapoor028** [comment] 2022-02-17 17:31
This seems to be working for us though https://github.com/microsoft/azure-pipelines-tasks/issues/12808#issuecomment-634609977 but probably not the best option

**Comment by MarcoRossignoli** [comment] 2022-02-22 17:31
I can confirm that the @jakubch1 fix is working as expected and for now it's the way to go.

We found the root cause of issue on the agent side that we'll fix soon as possible.

**Comment by Evangelink** [comment] 2022-07-26 13:20
@rkapoor028 Are you still experiencing issue with newer versions?

**Comment by Evangelink** [comment] 2022-08-03 14:03
Closing the issue. Feel free to ping us if you are still having any issue.

**Closed by Evangelink** 2022-08-03 14:03 UTC

**Comment by ibiglari** [comment] 2024-01-11 04:12
I am still facing the very same issue, with VS Professional version 17.8.4

```
========== Starting test run ==========
Testhost process for source(s) 'C:\Users\xxx\IntegrationTests.dll' exited with error: Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.CodeCoverage.Shim, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at Microsoft.VisualStudio.TestPlatform.ObjectModel.EqtTrace.Error(String format, Object[] args)
   at Microsoft.VisualStudio.TestPlatform.TestHost.Program.Main(String[] args) in /_/src/testhost.x86/Program.cs:line 41
. Please check the diagnostic logs for more information.
Testhost process for source(s) 'C:\Users\xxx\IntegrationTests.dll' exited with error: Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.CodeCoverage.Shim, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at Microsoft.VisualStudio.TestPlatform.ObjectModel.EqtTrace.Error(String format, Object[] args)
   at Microsoft.VisualStudio.TestPlatform.TestHost.Program.Main(String[] args) in /_/src/testhost.x86/Program.cs:line 41
. Please check the diagnostic logs for more information.
========== Test run aborted: 0 Tests (0 Passed, 0 Failed, 0 Skipped) run in < 1 ms ==========

```

I am using `Microsoft::VisualStudio::CppUnitTestFramework`. I've tried the above [comment](https://github.com/microsoft/vstest/issues/3382#issuecomment-1043053889) to no avail.
