### ISSUE TITLE
Run CodedUiTests

### ISSUE THREAD

**Issue by hubertusgr** [Microsoft/vstest#1386] opened 2018-01-23 14:21 UTC
## Description
We are using the microsoft vsts build task "VsTest Platform Installer" to install the vstest platform from nuget. We have the issue, that the following task wich uses the commandline to run testst is not recognizing the CodedUi Tests as proper tests.
Actually it would not work at all but we then placed the CodedUiTestFramework.dll beside the console and so it started to work at all. 
After that we still can't execute our tests because i

n the results we get the message:

**Failed to initialize the unit test extension 'urn:CodedUITest': A unit test extension is not registered for the following attribute: Microsoft.VisualStudio.TestTools.UITesting.CodedUITestAttribute.**

## Steps to reproduce
Create a coded ui test project with a "hello world" tests and try to run it with the console provided in the nuget package. Tests Classes must be marked with the [CodedUiTest] Attributed, individual tests with the [TestMethod] attribute.

## Expected behavior
The ui tests can be run in the same way as they are running with vstest.console.exe of the installed version of visual studio

## Actual behavior
Without placing the CodedUiTestFramework somewhere where the Vstest.console.exe can reach it for resolving assemblies the tests are not being discovered properly.

## Diagnostic logs
This is happening if I do not place the Microsoft.VisualStudio.QualityTools.CodedUITestFramework.dll beside the Vstest.console.exe
[DiagWithdll.log](https://github.com/Microsoft/vstest/files/1656378/DiagWithdll.log)

After placing the CodedUITestFramework.dll i get this:
[DiagWithoutdll.log](https://github.com/Microsoft/vstest/files/1656379/DiagWithoutdll.log)

## Environment
Windows 10 Pro

**Comment by smadala** [comment] 2018-01-23 16:34
Dupe of https://github.com/Microsoft/vstest/issues/1353
/cc @acesiddhu @PBoraMSFT @cltshivash

**Closed by smadala** 2018-01-23 16:34 UTC
