### ISSUE TITLE
vstest.console.exe crashes on x64 with code coverage

### ISSUE THREAD

**Issue by overeemm** [Microsoft/vstest#859] opened 2017-06-13 17:26 UTC
## Description
When we run code coverage on a test dll in x64 mode, the process crashes with the following error:
Application: vstest.executionengine.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an internal error in the .NET Runtime at IP 00007FFBDA1474B7 (00007FFBDA120000) with exit code 80131506.

The problem seems to be in an (unrelated) signature in some C# code. Namely a method with as return type `KeyValuePair<string, string[]>?`

## Steps to reproduce
I've created a small repro project: https://github.com/AFASResearch/vstest-codecoverage-x64-crash-repro

Running the following command on the console
`"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" "bin\x64\Debug\UnitTestProject1.dll" /EnableCodeCoverage /Platform:x64 /logger:trx`
results in the error.

## Expected behavior
Not a crash, but a test run with one succeeded test, and code coverage.

## Actual behavior
A crash.

## Environment
This is tested on Visual Studio 2017 enterprise, on both Windows 10 (anniversary update) and Windows 2012 R2 Standard.

**Comment by mayankbansal018** [comment] 2017-06-21 06:58
@overeemm , I tried the steps mentioned above, but could not reproduce this issue.

- Tried with /Platform:x64 on anycpu build
- Tried with /Platform:x64 on x64 build

can you please try it on some other machine, with latest vs installation, & let us know if it still repro's for you?

**Comment by SK-Marten** [comment] 2017-06-21 13:23
@mayankbansal018 . I'm a collegue of @overeemm and I experience the same issue (just like some other colleagues we asked to check), building the project with the latest VS studio 2017 enterprise and then running that commandline. 

In the event viewer I get the error which is already described, and this error event:
Faulting application name: vstest.executionengine.exe, version: 15.0.26228.0, time stamp: 0x58b56155
Faulting module name: clr.dll, version: 4.7.2053.0, time stamp: 0x58fa6d2a
Exception code: 0xc0000005
Fault offset: 0x00000000000274b7
Faulting process ID: 0x36ac
Faulting application start time: 0x01d2ea900566e499
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.executionengine.exe
Faulting module path: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Report ID: 01d19195-a8c2-4494-a732-e39e39203031
Faulting package full name: 
Faulting package-relative application ID:

**Comment by mayankbansal018** [comment] 2017-06-23 06:23
@SK-Marten , can you please provide the crash dump for vstest.executionengine.exe. Since I'm not able to repro this issue locally it might help.
Also can you share your local Unittest dlls. I'll try to use your assemblies to see if I can repro the issue locally.

**Comment by SK-Marten** [comment] 2017-06-26 14:58
@mayankbansal018, you can find the files I used + crashdumps at https://www.dropbox.com/sh/6vg4eatrpryqejd/AADY160FoTUROTipRXfr8PiYa?dl=0

**Comment by mayankbansal018** [comment] 2017-06-27 13:15
@SK-Marten the stack trace points to some thing in IntelliTrace, I've forwarded this issue to the relevant team. 

I still could not reproduce this issue using your sample dlls, hopefully the IntelliTrace team can let us know better.

**Comment by wiktork** [comment] 2017-06-27 17:25
@SK-Marten @overeemm We fixed this bug for Visual Studio 15.3. The preview version should contain the fix (15.3 Preview 3).

**Comment by mayankbansal018** [comment] 2017-06-28 08:10
Closing this issue, since it is fixed in 15.3 preview 3.

**Closed by mayankbansal018** 2017-06-28 08:10 UTC
