### ISSUE TITLE
Visual Studio test explorer does not update test status when InlineData has a specific combination of special characters

### ISSUE THREAD

**Issue by harshvchawla** [microsoft/vstest#3575] opened 2022-04-13 19:46 UTC
## Description
If there is a test containing a specific set of special characters, test explorer parsing fails to update status of that test run within the test explorer

## Steps to reproduce
1) Create & run following unit test
```
[Fact]
public void TestSimilarString()
{
    var stringOne = "'\"\\!@#$";
    var stringTwo = "testString";
    Assert.NotEqual(stringOne, stringTwo);
}
```
Note that this also happens when using InlineData with the special character string

## Expected behavior
> test status should be updated (with pass or fail etc)

## Actual behavior
> Test explorer keeps showing the test status as "Not run"

## Environment
> Please share additional details about the test environment.
> Operating system, Build version of vstest.console
Edition	Windows 10 Pro
Version	21H2
Installed on	‎14-‎Dec-‎2020
OS build	19044.1586
Experience	Windows Feature Experience Pack 120.2212.4170.0

Microsoft Visual Studio Professional 2019
Version 16.11.12
VisualStudio.16.Release/16.11.12+32407.337
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Professional

ASP.NET and Web Tools 2019   16.11.106.23128
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2012   16.11.106.23128
For additional information, visit https://www.asp.net/

ASP.NET Web Frameworks and Tools 2019   16.11.106.23128
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.11.106.23128
Azure App Service Tools v3.0.0

C# Tools   3.11.0-4.22108.8+d9bef045c4362fbcab27ef35daec4e95c8ff47e1
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

JetBrains ReSharper 2021.3.3   Build 213.0.20220125.124455
JetBrains ReSharper package for Microsoft Visual Studio. For more information about ReSharper, visit http://www.jetbrains.com/resharper. Copyright © 2022 JetBrains, Inc.

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.2
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

MySQL for Visual Studio   1.2.10
Data design and management tools for MySQL. Copyright (c) 2007, 2019, Oracle and/or its affiliates. All rights reserved.

Node.js Tools   1.5.30526.3 Commit Hash:c09c81113bcbc86d57943fcdd67e82434263d61d
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   5.11.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Razor (ASP.NET Core)   16.1.0.2122504+13c05c96ea6bdbe550bd88b0bf6cdddf8cde1725
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   16.0.62201.17150
Microsoft SQL Server Data Tools

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

TypeScript Tools   16.0.30526.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.11.0-4.22108.8+d9bef045c4362fbcab27ef35daec4e95c8ff47e1
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.11.0-beta.21514.6+b6c2c4f53ea3a08fa603ea93d6d2f808a62a21d1
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Web Compiler   1.12.394
Compiler for LESS, Sass and CoffeeScript files

**Comment by harshvchawla** [comment] 2022-04-18 23:05
```
[Theory]
[InlineData("testStrign")]
[InlineData("teststrign")]
[InlineData("test-s-t-rign")]
[InlineData("test s t rign")]
[InlineData("tES|}{[]/';.,:\"\\!@#$%^&*()~`T- Stri-- gn")]
public void TestSimilarString1(string stringOne)
{
    var stringTwo = "testString";
    Assert.NotEqual(stringOne, stringTwo);
}
```
        
is a more true positive way to reproduce the bug (adding several such test cases reproduces the bug)

**Comment by nohwnd** [comment] 2022-04-19 14:10
@peterwald Please have a look if you can :)

**Comment by peterwald** [comment] 2022-04-19 14:42
I believe this is a known issue and a consequence of the FullyQualifiedName parsing logic. We have work in progress to remove the internal usage of FQN to track test cases. That work should fix this issue.

**Comment by JakubJanowski** [comment] 2023-09-01 18:33
I think it has been fixed. I can't reproduce the problem anymore (Visual Studio version 17.6.3).

**Comment by Evangelink** [comment] 2023-09-01 18:50
Ping @peterwald

**Comment by peterwald** [comment] 2023-09-01 18:53
Thanks for the update @JakubJanowski

**Comment by Evangelink** [comment] 2023-09-01 18:54
Closed as fixed

**Closed by Evangelink** 2023-09-01 18:54 UTC
