### ISSUE TITLE
vs2017 release 15.2 - Test source code not found and project marked as "external"

### ISSUE THREAD

**Issue by bragma** [Microsoft/vstest#827] opened 2017-05-22 14:58 UTC
Hi,
after installing the latest vs2017 and converting an existing project (ASP NET Core, .NET Framework 4.6) with 1000+ tests, most of them are now marked as "external" in "view by project" and no source code is associated with them (when clicking on the code name). What's strange is that not all tests fail to be recognized, only some and it depends on the code in the test method.
I've not been able to reproduce it on a sample project, but it seems somehow to be related with async (await) operations in the test. Fiddling with the test code (i.e. removing some code using await at the end of the test) I've managed to make the test being recognized.
Is this a known issue? I've found some references to similar problem but for VS2017 RC and were marked as solved.
Thanks

**Comment by rynowak** [comment] 2017-05-23 02:49
I am having this problem as well with 15.2 and dotnet 2.0.0-preview2-006098

**Comment by Faizan2304** [comment] 2017-05-23 06:28
@bragma we have fixed this issue. 
What is the version of Microsoft.NET.Test.Sdk you are using?
If possible can you please provide repro project, it will really help us to root cause and fix the issue faster.

**Comment by rynowak** [comment] 2017-05-23 07:28
You can repro this with https://github.com/aspnet/Mvc or any of the asp.net repos.

**Comment by bragma** [comment] 2017-05-23 10:38
@Faizan2304 I'm using 15.0.0.0. I saw there is a new 15.3 preview, I'll try with that too. Sadly I cannot share the project with the problem, and I've not been able to reproduce it with a simple project.
Consider that in my tests, 200 are correctly recognized, 800 are not. But if I compare the test code, I see little difference between them. The only think I am sure of is that awaits on methods/classes of the project being tested is somehow involved.

Consider this trivial test:
```
		[Fact]
		public async Task CreateBrand()
		{
			Assert.True(await Task.FromResult(true));

			// This line is ok
			var y = new Brand();

			// This line is not, must be commented to make the test being recognized
			var x = await Task.FromResult(new Brand());
		}
```

"Brand" is a class defined in the tested project.

**Comment by Faizan2304** [comment] 2017-05-23 12:14
Its seems issue with xunit. 
I am able to repro it with blank .net core unit test project

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.3.0-preview-20170517-02" />
    <PackageReference Include="xunit" Version="2.3.0-beta2-*" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.3.0-beta2-*" />
  </ItemGroup>

</Project>
```
on changing `xunit` version to `2.2.0` everything start working.

Please open a bug in repo https://github.com/xunit/xunit

**Comment by bragma** [comment] 2017-05-24 10:40
@Faizan2304 there may be multiple problems then, because I am using xunit 2.2.0. Also, I've opened the bug on https://github.com/xunit/xunit/issues/1295 and they told me to ask here. It seems there is a responsibility cycle. :)

**Comment by Faizan2304** [comment] 2017-05-25 06:14
@bragma : If by any chance you are having this issue
https://github.com/Microsoft/vstest/issues/523#issuecomment-287697801 

Can you please do a experiment for me:
Convert the xunit test which is coming in category `External` to MStest and see if it works. This way we will come to know that issue is related to adapter or not.

To convert a test to MStest
1) Add following line in test csproj
```
    <PackageReference Include="MSTest.TestAdapter" Version="1.1.17" />
    <PackageReference Include="MSTest.TestFramework" Version="1.1.17" />
```

2) Add attribute `[TestMethod]` in your test
3) Add attribute `[TestClass]` on the class which has test of step 2
4) Add namespace `using Microsoft.VisualStudio.TestTools.UnitTesting;`

**Comment by bragma** [comment] 2017-05-25 08:08
I sure will!

**Comment by Faizan2304** [comment] 2017-05-29 06:17
@bragma If by any chance did you get time to look into it?

**Comment by bragma** [comment] 2017-05-29 08:34
@Faizan2304 I'm sorry, not yet. I've had some busy days.

**Comment by Faizan2304** [comment] 2017-05-30 05:23
@bragma : Ok.. Please let us know the result once you will try.

**Comment by bragma** [comment] 2017-05-31 07:09
Hi @Faizan2304 , I've converted the test as you asked, and in fact it is now recognized. What's next step?

Here is the sample converted code:


```
...
	[TestClass]
	public class TestVS2017TestsMSTest
	{
		[TestMethod]
		public async Task TestVS2017()
		{
			Microsoft.VisualStudio.TestTools.UnitTesting.Assert.IsTrue(await Task.FromResult(true));

			// This line is ok
			var y = new Brand();

			// This line is not, must be commented to make the test being recognized
			var x = await Task.FromResult(new Brand());
		}
	}

	public class TestVS2017TestsXUnit
	{
		[Fact]
		public async Task TestVS2017()
		{
			Xunit.Assert.True(await Task.FromResult(true));

			// This line is ok
			var y = new Brand();

			// This line is not, must be commented to make the test being recognized
			var x = await Task.FromResult(new Brand());
		}
	}
...
```

**Comment by Faizan2304** [comment] 2017-05-31 12:10
Thanks @bragma..  So after converting test with MSTest, Visual studio is now able to identify its project (that is its not coming as external) and source navigation is working fine. 
So it clearly shows that issue is with Xunit. I have given them repro project (https://github.com/xunit/xunit/issues/1295#issuecomment-303926994), lets see what they say. Issue doesn't seems in vstest.

**Comment by Faizan2304** [comment] 2017-06-06 08:41
Hi @bragma, as it is the issue with xunit and we have already opened issue with xunit, I am closing this issue here. Please revert back if you have any concern.

**Closed by Faizan2304** 2017-06-06 08:41 UTC
