### ISSUE TITLE
Microsoft.NET.Test.Sdk should migrate to System.Text.Json

### ISSUE THREAD

**Issue by AndersMalmgren** [microsoft/vstest#4976] opened 2024-04-10 15:28 UTC
Why is Microsoft.NET.Test.Sdk still on Newtonsoft when rest of the world have moved to System.Text.Json? 
Shouldnt be a too big of a job to migrate it?

Thanks

edit: System.Text.Json work with netstandard 2.0

**Comment by nohwnd** [comment] 2024-04-10 16:49
https://github.com/microsoft/vstest/issues/2488#issuecomment-1154795013

This is a duplicate of this issue. Specifically this comment shows why we don’t want to do it. Moving to system text json doesn’t solve the dependency issue for us because it doesn’t ship with .net framework. 

If you think my reasons are incorrect, please comment on the other issue so we can discuss it.

**Closed by nohwnd** 2024-04-10 16:49 UTC

**Comment by AndersMalmgren** [comment] 2024-04-12 15:20
System.Text.Json supports netstandard which are available for full framework

**Comment by nohwnd** [comment] 2024-04-15 11:34
You are right, but that is how we get newtonsoft.json already, and get complaints that we are changing project dependencies and mixing up test related things. So if we switch to System.Text.Json we are not solving this problem for .NET Framework. In fact if everyone moves to STJ and we stick with Newtonsoft.Json we are in a better position because then we are not changing anyones dependencies.

**Comment by AndersMalmgren** [comment] 2024-04-15 16:50
> You are right, but that is how we get newtonsoft.json already, and get complaints that we are changing project dependencies and mixing up test related things. So if we switch to System.Text.Json we are not solving this problem for .NET Framework. In fact if everyone moves to STJ and we stick with Newtonsoft.Json we are in a better position because then we are not changing anyones dependencies.

The future is .NET Core not full framework. And .NET Core uses System.Text.Json. ANd it can be made to work by importing System.Text.Json only for target full framework rest uses it through core lib. I dont understand why this would be negative for Full framework guys. 

If its so important to keep backward combability it can  be fixed with compiler flags that uses netewton soft when compiling for full framework and uses System.Text.Json for the rest
