### ISSUE TITLE
TestPlatform 17.0.0 causes hanging azure devops pipeline

### ISSUE THREAD

**Issue by rouke-broersma** [microsoft/vstest#3144] opened 2021-10-29 22:04 UTC
## Description
We are updating vstest from 16.10.0 to 17.0.0. We are noticing that running unit tests in our azure devops pipeline causes the pipeline to hang until azure devops cancels the pipeline due to the timeout. This issue is not happening on 16.10.0.

I initially thought perhaps sonarcloud was interfering (they inject msbuild steps to be able to inspect the code) so I disabled sonarcloud in the PR but the issue persists.

I updated the dotnet sdk to the same version as the pipeline uses and could not reproduce the problem locally.

## Steps to reproduce
See: 
https://github.com/stryker-mutator/stryker-net/pull/1732

https://dev.azure.com/stryker-mutator/Stryker/_build/results?buildId=8467&view=results

## Expected behavior
Unit tests run and have a result

## Actual behavior
Unit tests hang for an hour until the pipeline is cancelled

## Diagnostic logs
> Please share test platform diagnostics logs. Instructions to collect logs are [here](https://github.com/Microsoft/vstest-docs/blob/main/docs/diagnose.md#test-platform-diagnostics).  
> The logs may contain test assembly paths, kindly review and mask those before sharing.

I have saved the complete workspace of the pipeline in this pipeline run with diagnostics and system.debug turned on: https://dev.azure.com/stryker-mutator/Stryker/_build/results?buildId=8467&view=results

## Environment
Microsoft Hosted agent sku windows-latest
The hosted agent seems to run vstest 16.11.0

**Comment by rouke-broersma** [comment] 2021-11-26 11:58
This is still happening.

**Comment by blmbyd** [comment] 2021-12-07 16:18
Yes. For us it was also happening. We changed `Test platform version` to `Visual Studio 2019` in task settings - it helped.
@rouke-broersma can You check it?

**Comment by rouke-broersma** [comment] 2021-12-07 16:50
We are not using the vstest task, we are using the dotnet test task. Not sure if the test platform version is relevant in this case. @blmbyd or are you using dotnet test as well?

**Comment by blmbyd** [comment] 2021-12-09 18:20
> We are not using the vstest task, we are using the dotnet test task. Not sure if the test platform version is relevant in this case. @blmbyd or are you using dotnet test as well?

> We are updating vstest from 16.10.0 to 17.0.0.

@rouke-broersma so why You wrote this in issue?

But Yes You are right - We have mix in one pipeline with `dotnet test` and `vstest` - `dotnet test` was hanging, not it is OK
We also using Sonar.

**Comment by rouke-broersma** [comment] 2021-12-09 18:25
> > We are not using the vstest task, we are using the dotnet test task. Not sure if the test platform version is relevant in this case. @blmbyd or are you using dotnet test as well?
> 
> > We are updating vstest from 16.10.0 to 17.0.0.
> 
> @rouke-broersma so why You wrote this in issue?
> 
> But Yes You are right - We have mix in one pipeline with `dotnet test` and `vstest` - `dotnet test` was hanging, not it is OK
> We also using Sonar.

We are updating vstest from 16.10 to 17.0 as nuget packages in our project, not in the pipeline. So I'm not sure if the vstest platform version used by the azdo task matters.

**Comment by Haplois** [comment] 2022-02-17 10:17
@rouke-broersma, thanks for confirming the fix.

@blmbyd, can you test 17.1 version too to see if it fixes your issue as well?

**Comment by nohwnd** [comment] 2022-03-12 05:54
Closing, because OP confirmed the fix and there is no further activity.

**Closed by nohwnd** 2022-03-12 05:54 UTC
