### ISSUE TITLE
Remove depenedency on Newtonsoft.Json - any plans ?

### ISSUE THREAD

**Issue by JiriZidek** [microsoft/vstest#4867] opened 2024-01-31 00:56 UTC
## Description

For .net8 = .NETCOreApp, Version=v3.1 there is still depenedency on Newtonsoft.Json

## Steps to reproduce

See Nuget package dependencies
![image](https://github.com/microsoft/vstest/assets/8578952/15149d8b-5e4f-4c4a-a61f-853271e9afbd)

## Expected behavior

Depenedency only on System.Text.Json 

## Actual behavior

Polluting test projects with Newtonsoft.Json which looks unnecesary.

## Environment

VS2022 17.8.5, Microsoft.TestPlatform.TestHost package version 17.8.0

**Comment by Evangelink** [comment] 2024-01-31 08:12
Closing as duplicate of #2488

**Closed by Evangelink** 2024-01-31 08:12 UTC
