### ISSUE TITLE
Test runner crashes with VSTS Build

### ISSUE THREAD

**Issue by martinfletcher** [Microsoft/vstest#819] opened 2017-05-17 11:26 UTC
## Description
I have a build which runs tests on several projects (9) that fails with the following message:

The active test run was aborted. Reason: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.

## Steps to reproduce
Run build on VSTS with several projects

"C:\Program Files\dotnet\dotnet.exe" test d:\a\1\s\tests\DependencyInjection.Core.UnitTests\DependencyInjection.Core.UnitTests.csproj -l trx;LogFileName=TestResults.trx

NetCoreApp 1.1

## Expected behavior
Tests run and produce report on VSTS build

## Actual behavior
Tests crach and hang with the above message

## Environment
VSTS Build

**Comment by Faizan2304** [comment] 2017-05-17 12:54
@martincostello : Are you able to run this test on your local machine??

What is the version of dotnet you are using? I am interested in output of below two command
```
"C:\Program Files\dotnet\dotnet.exe" --info
"C:\Program Files\dotnet\dotnet.exe"  vstest --help
```

The second command will give a long output. Please provide us first 3 or 4 line of the result which will look similar to
```
Microsoft (R) Test Execution Command Line Tool Version 15.3.0-preview-20170502-03
Copyright (c) Microsoft Corporation.  All rights reserved.
```

**Comment by martincostello** [comment] 2017-05-17 13:01
I think you meant @martinfletcher.

**Comment by Faizan2304** [comment] 2017-05-17 13:04
@martincostello : Yes you are right. Thank you :)

**Comment by martinfletcher** [comment] 2017-05-17 18:55
Yes, these run fine locally. The issue is on the hosted build agent on vsts. I have spoken to a support engineer today via phone and he seems to think that the issue is with performance of the vsts hosted agent.

**Comment by Faizan2304** [comment] 2017-05-18 15:30
@martinfletcher : Ok.. let us know if something come from vsts hosted agent team.

**Comment by martinfletcher** [comment] 2017-05-18 17:38
Ok, so the issue is with the hosted agent.

After a long time on the phone with a support engineer, and after setting up a private agent to test on the problem seems to have been pinpointed.

Currently, the latest version of visual studio 2017 is 15.2. The hosted agents are running 15.1, and any project created with 15.2 does not work with the test agent.

I installed the agent tools on a machine with latest visual studio and setup as a private agent and builds worked fine. Just will not work on hosted agent with vs2017.

Hopefully this will be resolved soon, as we are now limited to just 240 build minutes for private agents if we want to run unit tests in our builds -far from acceptable!

If anyone knows who the right person to contact regarding the hosted agents, please send them my way or let me know so that I can contact them and get some kind of timeframe for when the hosted agents will be upgraded to 15.2.

Hope this puts anyone else having this issue at ease was it's not very obvious at all.

**Comment by Faizan2304** [comment] 2017-05-19 14:41
@nigurr  can help on test agent issue.

@martinfletcher what is the type of project(language, target framework etc) for which you are seeing the issue?

**Comment by martinfletcher** [comment] 2017-05-19 20:39
They are c# net standard 1.4 and 1.6

**Comment by nigurr** [comment] 2017-05-22 03:51
@martinfletcher @Faizan2304 I believe you meant "Running tests under hosted pool is failing"?

**Comment by martinfletcher** [comment] 2017-05-22 04:17
@nigurr Yes hosted 2017

**Comment by Faizan2304** [comment] 2017-05-24 05:29
@nigurr : did you get a chance to look into it?

**Comment by nigurr** [comment] 2017-05-24 05:32
@Faizan2304, This is nothing to do with Test Agent. This is purely vstest.console.exe in Hosted Pools.

If you need more info on Hosted Pool versions, I can share with you. But the issue seems to be vstest.console.exe issue as it's unable to run the tests of newer VS version

**Comment by martinfletcher** [comment] 2017-05-24 11:08
@Faizan2304 @DarqueWarrior Any ideas when vstset.console.exe will support VS2017 (15.2)?

**Comment by Faizan2304** [comment] 2017-05-24 11:08
@martinfletcher : Are u still facing the issue or it has been resolved?
If you are still facing the issue can you please share the repro project which I can use to create a local repro.

**Comment by martinfletcher** [comment] 2017-05-24 11:10
@Faizan2304 Yes. I can not share the project as its not OS.

**Comment by Faizan2304** [comment] 2017-05-24 11:14
@martinfletcher: Ok. 
What is the target framework version of test project and product code for which you are facing the problem.

**Comment by martinfletcher** [comment] 2017-05-24 11:37
target framework is net standard 1.4, vs version is  VS 2017 Enterprise 15.2 (26430.6)

**Comment by Faizan2304** [comment] 2017-05-24 12:14
Test project with net standard as targetframework is not a supported scenario. Test project can have targetframework as netcoreapp (eg: netcoreapp1.0, netcoreapp2.0 etc) and .net framework (eg: net46 etc).

Will it be possible for you to collect log and share with us.
To collect log 
1) run `dotnet test` with argument `--diag vstestLogFile.txt` 
2) Add a `Publish build artifact` task in your build definition.
3) In `Publish build artifact` task publish all file with pattern `**/*vstestLogFile*.txt
4) Share with us all *vstestLogFile*.txt file

**Comment by martinfletcher** [comment] 2017-05-24 12:30
@Faizan2304 Appologies, the test project is targeting netcoreapp1.1. The project being tested is netstandard1.4

**Comment by Faizan2304** [comment] 2017-05-24 12:33
@martinfletcher Thanks for confirming. Please collect the log and share with us. It will help us to root cause the issue. Ideally project created in VS 15.2 should run in VS 15.1

**Comment by martinfletcher** [comment] 2017-05-24 13:21
@Faizan2304 That is the issue, the build never stops, not even after timeout period. Therefore, the logs never get generated.

**Comment by Faizan2304** [comment] 2017-05-24 13:31
@martinfletcher My assumption is that VS 15.1 doesn't have netcoreapp1.1 runtime installed. If you will change your test code to target netcoreapp1.0, I believe everything will work fine.

**Comment by martinfletcher** [comment] 2017-05-24 13:54
@Faizan2304 right OK i will try that. Any idea when 15.2 will be supported?

**Comment by Faizan2304** [comment] 2017-05-26 05:55
> @Faizan2304 That is the issue, the build never stops, not even after timeout period. Therefore, the logs never get generated.

Its seems something wrong with those machine. Doesn't seems issue with vstest.

> @Faizan2304 right OK i will try that. Any idea when 15.2 will be supported?

I don't know when they will update machine to 15.2. I don't know whom to contact for this.

**Comment by Faizan2304** [comment] 2017-06-06 10:10
hey @martinfletcher, as it doesn't seems problem with vstest but with hosted agent. I am closing issue here. Please revert back if u have any concern of query.

**Closed by Faizan2304** 2017-06-06 10:10 UTC
