### ISSUE TITLE
TestAdapterPath not honored  in .NET Core tests.

### ISSUE THREAD

**Issue by smadala** [microsoft/vstest#1648] opened 2018-06-15 08:28 UTC
## Description
> For follow up on https://github.com/Microsoft/vstest/issues/1633

- Honor `--test-adapter-path` for .NET core tests?

**Comment by smadala** [comment] 2018-06-15 08:30
@mayankbansal018 @abhishkk @singhsarab @pvlakshm @codito

**Comment by abhishkk** [comment] 2018-06-15 09:35
> In .NET Core case you can use --test-adapter-path to pass other extensions path but not test-adapter.

@smadala Is this a regression? We should definitely support test adapter via test-adapter-path.

**Comment by smadala** [comment] 2018-06-15 09:36
AFAIK this is not regression.

**Comment by singhsarab** [comment] 2019-09-16 09:14
This is currently BY-DESIGN. We do not have any customer ask for this yet. Closing this for now.

**Closed by singhsarab** 2019-09-16 09:14 UTC
Labels: enhancement

**Comment by dennis-yemelyanov** [comment] 2020-02-10 07:58
I would vote for this feature... Is there any workaround to still pass custom test adapter paths to the underlying vstest.console dll? Maybe not through "dotnet vstest", but using some other entry point?

**Comment by dennis-yemelyanov** [comment] 2020-02-11 18:45
@singhsarab , can you please share where this restriction is implemented in the code? Since TestAdapterpath is recognized when calling vstest.console.exe directly, but is not recognized when calling dotnet commands, I assume there is some code that does this check: if the caller is dotnet command, then don't pass test adapter path?

**Comment by singhsarab** [comment] 2020-02-12 12:45
There are different implementations for running the tests, one is for full framework and other for .NET core.

Following are the implementations
1. https://github.com/microsoft/vstest/blob/master/src/Microsoft.TestPlatform.TestHostProvider/Hosting/DefaultTestHostManager.cs#L187
2. https://github.com/microsoft/vstest/blob/master/src/Microsoft.TestPlatform.TestHostProvider/Hosting/DotnetTestHostManager.cs#L308

**Comment by richard-fine** [comment] 2021-07-10 21:29
Can anyone confirm whether it is still the case that `dotnet test` does not actually implement any way to specify a custom adaptor path for .NET Core / .NET 5?

`--test-adapter-path` is [listed in the documentation](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test), while `dotnet test` itself will print an error message suggesting that `/TestAdapterPath` should be used (and I do see code which [looks like it might actually implement that](https://github.com/microsoft/vstest/blob/main/src/vstest.console/Processors/TestAdapterPathArgumentProcessor.cs)). So the docs say it's implemented one way, the tool says it's implemented another way, and this issue says it isn't implemented at all... :)
