### ISSUE TITLE
Failed to negotiate protocol. Wait for response timeout

### ISSUE THREAD

**Issue by linluxiang** [Microsoft/vstest#1607] opened 2018-05-17 10:33 UTC
I tried to run NUnit test cases in Visual Studio 2017 15.7.1 and I got this exception.

```
[5/17/2018 12:31:26 PM Diagnostic] VirtualReadOnlyTestDataStore.OperationStateChanged State=OperationSetFinished, operationInProgress=False
[5/17/2018 12:31:26 PM Diagnostic] TestDiscoveryStats.OperationStateChanged State=OperationSetFinished, InProgress=False
[5/17/2018 12:31:26 PM Error] Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Failed to negotiate protocol. Wait for response timed out.
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TestRequestSender.CheckVersionWithTestHost()
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyExecutionManager.StartTestRun(TestRunCriteria testRunCriteria, ITestRunEventsHandler eventHandler)
[5/17/2018 12:31:26 PM Error] Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Failed to negotiate protocol. Wait for response timed out.
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TestRequestSender.CheckVersionWithTestHost()
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyExecutionManager.StartTestRun(TestRunCriteria testRunCriteria, ITestRunEventsHandler eventHandler)
[5/17/2018 12:31:26 PM Diagnostic] Cancel requested, actions left in queue 1, exiting...
[5/17/2018 12:31:26 PM Diagnostic] VirtualReadOnlyTestDataStore.OperationStateChanged State=TestExecutionCanceling, operationInProgress=False
[5/17/2018 12:31:26 PM Diagnostic] TestDiscoveryStats.OperationStateChanged State=TestExecutionCanceling, InProgress=False
[5/17/2018 12:31:26 PM Diagnostic] ***    Run finished using 'InMemoryUnitTestWriter' ***
[5/17/2018 12:31:26 PM Informational] ========== Run test finished: 0 run (0:01:00.47631) ==========
[5/17/2018 12:31:26 PM Diagnostic] VirtualReadOnlyTestDataStore.OperationStateChanged State=TestExecutionCancelAndFinished, operationInProgress=False
[5/17/2018 12:31:26 PM Diagnostic] TestDiscoveryStats.OperationStateChanged State=TestExecutionCancelAndFinished, InProgress=False==========
```

Here are the package and versions I'm using in the project
```
    <PackageReference Include="NUnit" Version="$(NUnitVersion)" />
    <PackageReference Include="NUnit3TestAdapter" Version="$(NUnitTestAdapterVersion)" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="$(MicrosoftTestSdkVersion)" />
```
```
    <MicrosoftTestSdkVersion>15.8.0-preview-20180510-03</MicrosoftTestSdkVersion>
    <NUnitVersion>3.10.1</NUnitVersion>
    <NUnitTestAdapterVersion> 3.10.0</NUnitTestAdapterVersion>
```

I've also tried latest release 15.7.2 but still got the same exception

**Comment by linluxiang** [comment] 2018-05-17 13:07
If I run directly `dotnet test`. I still got the same exception.

**Comment by singhsarab** [comment] 2018-05-28 06:41
@linluxiang I was not able to reproduce the issue.

Can you please collect and share logs for vstest.console and testhost*exe 
https://github.com/Microsoft/vstest-docs/blob/master/docs/diagnose.md#collect-trace-using-config-file

Also, if you are running on a slow machine, try increasing the timeout by setting the environment variable VSTEST_CONNECTION_TIMEOUT.

**Comment by roozbehid-ic** [comment] 2018-06-04 22:30
I was having similar issues with my unit test which was netcoreapp2.0. Building it with net461 would be fine but not netcoreapp2.0
I've added following to my project and it fixed it for netcoreapp2.0

    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>

**Comment by linluxiang** [comment] 2018-06-08 17:05
Unfortunately changing the config file doesn't work for me. I have to run `dotnet test --diag:log.txt` to get the log file.

And I can also give some hint as I tried to decompile vstest.console.exe to debug. I got an Exception on the line below.

https://github.com/Microsoft/vstest/blob/c36ef303f9a9a904a3c5ae70e3ea61a3c05f1eb1/src/Microsoft.TestPlatform.CommunicationUtilities/TcpClientExtensions.cs#L28

It's a NullReference exception and RemoteEndpoint is null !!! I set a breakpoint to see its IsConncted value and the value is true. I don't know how could it happen when IsConnected is true why RemoteEndpoint null. 


[log.txt](https://github.com/Microsoft/vstest/files/2085304/log.txt)
[log.host.18-06-08_18-57-03_15512_5.txt](https://github.com/Microsoft/vstest/files/2085305/log.host.18-06-08_18-57-03_15512_5.txt)

**Comment by linluxiang** [comment] 2018-06-08 17:15
OK. I got another log.txt by changing vstest.console.exe.config.


[log.zip](https://github.com/Microsoft/vstest/files/2085361/log.zip)

**Comment by smadala** [comment] 2018-06-11 07:01
@linluxiang Can you share machine details(OS, etc) and sample repro project? 

Can you try downgrading `MicrosoftTestSdkVersion` to `15.7.2`?

**Comment by smadala** [comment] 2018-06-11 07:04
@roozbehid-ic Can you share repro project and details steps how you solved it?

**Comment by linluxiang** [comment] 2018-06-11 09:47
@smadala Hi my system is Windows 10 Pro Version 1709 OS Build 16299.371. And I've tried to downgrade but it didn't help

**Comment by smadala** [comment] 2018-06-11 10:04
@linluxiang Interesting https://github.com/Microsoft/vstest/blob/c36ef303f9a9a904a3c5ae70e3ea61a3c05f1eb1/src/Microsoft.TestPlatform.CommunicationUtilities/TcpClientExtensions.cs#L28 not part of 15.7.2. Can we have quick skype call to investigate this?

Send a email to samadala at microsoft dot com.

**Comment by linluxiang** [comment] 2018-06-12 12:37
@smadala I did a fully windows reinstallation and the problem was gone..

**Comment by smadala** [comment] 2018-06-12 12:39
@linluxiang Thanks for update. I will keep this issue open to fix the NRE.

**Comment by efrainsteinbach** [comment] 2018-07-13 13:20
I get this error message when I try to run my tests on `ubuntu-16.04` with `dotnet core 2.1` and `Microsoft.NET.Test.Sdk 15.7.2`.

The logs look very similar to the one posted before. I could reproduce this on multiple machines (docker containers and physical machines). `<CopyLocalLockFileAssemblies>` doesn't help.

Can you explain more about what's going wrong here? Does anyone understand the root cause?
Are there any workarounds? (e.g. disable tests which do something that cause this issue)

**Comment by smadala** [comment] 2018-07-13 13:48
Can you please try to downgrade Microsoft.NET.Test.SDK to 15.7.0? Let us know if that solved the problem.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by smadala** [comment] 2018-07-16 13:12
@efrainsteinbach Did downgrading `Microsoft.NET.Test.SDK` version helped you? Can you please share `Dockerfile`/docker image to get repro for this issue? So that we can avoid theoretical fix?

**Comment by efrainsteinbach** [comment] 2018-07-31 14:16
I tried up- and downgrading between `15.6.0` and `15.8.0`.. none of them worked.

Here's my dockerfile:

`ARG DOTNET_VERSION=2.1

# prepare build image
FROM ubuntu:16.04 AS build

WORKDIR /tmp
ARG DOTNET_VERSION
ENV DOTNET_CLI_TELEMETRY_OPTOUT 1

RUN apt-get update \
&& apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    apt-transport-https \
    wget \
&& wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb \
&& dpkg -i packages-microsoft-prod.deb \
&& apt-get update \
&& apt-get install -y --no-install-recommends \
    dotnet-sdk-${DOTNET_VERSION} \
&& rm -rf /var/lib/apt/lists/*

# build
WORKDIR /src
COPY . .

# run all test projects
RUN set -x && for filename in $(find tests/ -iname '*.?sproj'); do dotnet test --logger:trx -r ./test-results "$filename"; exit 0; done

`
There's nothing exotic here. There must be something peculiar about my projects which causes this not to work. We have very similar docker images working for testing. I'm investigating, but any pointers would be highly appreciated.

**Comment by smadala** [comment] 2018-08-01 06:12
Looking into this. I will try to get the `diag` logs and see where the failure occurring.

**Comment by smadala** [comment] 2018-08-01 09:09
@efrainsteinbach I have tried above `Dockerfile`, I couldn't repo for simple MSTest test project.

Can you please share your test projects on github?
Pass `--diag log.txt` to `dotnet test` command and share all log.*.txt files?

**Comment by alexsaare** [comment] 2018-08-01 09:13
Same problem here for Multi-target test project.  Only affects netcoreapp1.0 and 1.1.  Works for other frameworks (net452, net46, net472).  Works on others developer machines.  Has happened to 2 developers now.  Upgrade/downgrade/reinstall of test sdk makes no difference.  Tried reinstalling Visual Studio - no difference.  Problem seen in both Visual Studio and command line.

Only identified fix has been to re-install windows.

**Comment by smadala** [comment] 2018-08-01 09:28
@alexsaare Pass --diag log.txt to dotnet test command and share all log.*.txt files?

**Comment by alexsaare** [comment] 2018-08-01 09:29
Log files below 

[log.host.18-08-01_11-25-17_87760_5.txt](https://github.com/Microsoft/vstest/files/2248860/log.host.18-08-01_11-25-17_87760_5.txt)
[log.host.18-08-01_11-26-18_61992_1.txt](https://github.com/Microsoft/vstest/files/2248861/log.host.18-08-01_11-26-18_61992_1.txt)
[log.host.18-08-01_11-26-21_05959_1.txt](https://github.com/Microsoft/vstest/files/2248862/log.host.18-08-01_11-26-21_05959_1.txt)
[log.host.18-08-01_11-26-23_25667_1.txt](https://github.com/Microsoft/vstest/files/2248863/log.host.18-08-01_11-26-23_25667_1.txt)
[log.txt](https://github.com/Microsoft/vstest/files/2248864/log.txt)
[log.host.18-08-01_11-24-13_12184_5.txt](https://github.com/Microsoft/vstest/files/2248865/log.host.18-08-01_11-24-13_12184_5.txt)
[log.host.18-08-01_11-24-15_22427_5.txt](https://github.com/Microsoft/vstest/files/2248866/log.host.18-08-01_11-24-15_22427_5.txt)
[log.host.18-08-01_11-24-17_12463_5.txt](https://github.com/Microsoft/vstest/files/2248867/log.host.18-08-01_11-24-17_12463_5.txt)

**Comment by alexsaare** [comment] 2018-08-01 09:31
source can be found in the repo below (migrate-tests branch)

https://github.com/Insure-Tech/InsuranceHub.Client.Net/tree/feature/migrate-tests

**Comment by smadala** [comment] 2018-08-01 09:37
@alexsaare Above logs are from failed test-run?

**Comment by smadala** [comment] 2018-08-01 09:44
@alexsaare Nevermind, found the required log.

**Comment by alexsaare** [comment] 2018-08-01 09:56
@smadala I'm going to leave this machine in this state for now (mostly because i don't have time to re-install windows).  So, if you need and further info or want me to try any fixes please let me know.

**Comment by smadala** [comment] 2018-08-01 10:13
I'm able to repo the issue.
 From `log.host.18-08-01_11-24-17_12463_5.txt` log messages this looks like RCA is .NET Core 1.0 APIs.
`System.PlatformNotSupportedException: System.Reflection.TypeExtensions is not supported on NET Standard 1.3 or 1.5.` 

```
TpTrace Error: 0 : 15816, 8, 2018/08/01, 11:24:17.783, 6163946165, testhost.dll, LengthPrefixCommunicationChannel: MessageReceived: Exception occurred while calling handler of type Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TestRequestHandler for MessageReceivedEventArgs: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Newtonsoft.Json.JsonSerializationException: Error setting value to 'MessageType' on 'Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.VersionedMessage'. ---> System.PlatformNotSupportedException: System.Reflection.TypeExtensions is not supported on NET Standard 1.3 or 1.5.
   at System.Reflection.TypeExtensions.IsAssignableFrom(Type type, Type c)
   at System.Linq.Expressions.Expression.ValidateLambdaArgs(Type delegateType, Expression& body, ReadOnlyCollection`1 parameters, String paramName)
   at System.Linq.Expressions.Expression.Lambda(Type delegateType, Expression body, String name, Boolean tailCall, IEnumerable`1 parameters)
   at Newtonsoft.Json.Utilities.ExpressionReflectionDelegateFactory.CreateSet[T](PropertyInfo propertyInfo)
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.SetValue(Object target, Object value)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.SetValue(Object target, Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.JsonDataSerializer.DeserializeMessage(String rawMessage)
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TestRequestHandler.OnMessageReceived(Object sender, MessageReceivedEventArgs messageReceivedArgs)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Microsoft.VisualStudio.TestPlatform.Utilities.MulticastDelegateUtilities.SafeInvoke(Delegate delegates, Object sender, EventArgs args, String traceDisplayName)
```

**Comment by alexsaare** [comment] 2018-08-01 10:40
But this works fine on other PCs??

**Comment by smadala** [comment] 2018-08-01 10:44
Yeah, It could be because .NET Core runtimes.

Can you see is there what is difference between two machine of `dotnet --info`? Mine is below.

```PS
.PS C:\Users\samadala\src\vstest> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.400-preview-008975
 Commit:    462479933b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.400-preview-008975\

Host (useful for support):
  Version: 2.1.0
  Commit:  caa7b7e2ba

.NET Core SDKs installed:
  1.0.0-preview2-003131 [C:\Program Files\dotnet\sdk]
  1.0.0-preview4-004107 [C:\Program Files\dotnet\sdk]
  1.0.0-rc3-004512 [C:\Program Files\dotnet\sdk]
  1.0.0-rc3-004517 [C:\Program Files\dotnet\sdk]
  1.0.0-rc4-004755 [C:\Program Files\dotnet\sdk]
  1.0.0-rc4-004771 [C:\Program Files\dotnet\sdk]
  1.0.0-rc4-004788 [C:\Program Files\dotnet\sdk]
  1.0.0-rc4-004842 [C:\Program Files\dotnet\sdk]
  1.0.0 [C:\Program Files\dotnet\sdk]
  1.0.2 [C:\Program Files\dotnet\sdk]
  1.0.4 [C:\Program Files\dotnet\sdk]
  1.1.0-preview1-005089 [C:\Program Files\dotnet\sdk]
  1.1.0-rc4-005029 [C:\Program Files\dotnet\sdk]
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.1.1-preview-007118 [C:\Program Files\dotnet\sdk]
  2.1.2 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.100-preview-007328 [C:\Program Files\dotnet\sdk]
  2.1.103 [C:\Program Files\dotnet\sdk]
  2.1.200-preview-007474 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.400-preview-008975 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1-rtm-30818 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1-rtm-30818 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by alexsaare** [comment] 2018-08-01 10:52
mine...

```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.302
 Commit:    9048955601

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.302\

Host (useful for support):
  Version: 2.1.0
  Commit:  caa7b7e2ba

.NET Core SDKs installed:
  1.0.0-preview1-002702 [C:\Program Files\dotnet\sdk]
  1.0.0-preview2-003121 [C:\Program Files\dotnet\sdk]
  1.0.0-preview2-003131 [C:\Program Files\dotnet\sdk]
  1.0.4 [C:\Program Files\dotnet\sdk]
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.0-rc2-3002702 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

I'll get one from the other guys asap

**Comment by alexsaare** [comment] 2018-08-01 12:15
Still waiting for the others to get back in the office however, in the mean time... the stack trace you posted above got my brain thinking.

We used to have a reference to System.Reflection.TypeExtensions however, this was removed.  In visual studio when I clicked on Manage NuGet Dependencies it was showing under the Installed packages.  Trying to remove it gave an error saying it was not installed.

Looking at the csproj revealed it was still referenced like this...

```
<ItemGroup Condition="'$(TargetFramework)' == 'net46'">
    <PackageReference Include="System.Reflection.TypeExtensions">
      <Version>4.5.0</Version>
    </PackageReference>
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net472'">
    <PackageReference Include="System.Reflection.TypeExtensions">
      <Version>4.5.0</Version>
    </PackageReference>
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'netcoreapp1.0'">
    <PackageReference Include="System.Reflection.TypeExtensions">
      <Version>4.5.0</Version>
    </PackageReference>
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'netcoreapp1.1'">
    <PackageReference Include="System.Reflection.TypeExtensions">
      <Version>4.5.0</Version>
    </PackageReference>
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'netcoreapp2.1'">
    <PackageReference Include="System.Reflection.TypeExtensions">
      <Version>4.5.0</Version>
    </PackageReference>
  </ItemGroup>
```

This removed the NuGet Issue but the tests still wouldn't run even after a Clean & Rebuild.  

So... I ran dotnet nuget locals all -- clear and deleted all everything from C:\Program Files (x86)\Microsoft SDKs\NuGetPackages

I deleted all bin and obj directories then reopened the solution in visual studio.  Clean & Rebuild 

Problem solved.  Unit test run again.  I'm not sure how or why those references got in there like that but that seems to have been the issue for me.  

Hope this helps someone else.

@smadala Thanks for your assistance with this.

**Comment by dferretti-fig** [comment] 2018-08-01 12:52
@alexsaare I have seen the "Failed to negotiate protocol" error when testing something with a reference to System.Reflection.TypeExtensions v4.5.0 and a target framework of netcoreapp1.0 or netcoreapp1.1 (2.0 and 2.1 work fine), but for some reason the problem doesn't happen when I reference System.Reflection.TypeExtensions v4.4.0 or lower - that works on all target frameworks for me.

**Comment by smadala** [comment] 2018-08-02 06:43
Looks like we have multiple reasons for `Failed to negotiate protocol. Wait for response timeout` error. We are seeing this error due to failure of inter process communication in vstest(vstest.console <-> testhost).

Here is summary for solutions/workarounds discussed in this issue. 

- https://github.com/Microsoft/vstest/issues/1607#issuecomment-394521170
 I was having similar issues with my unit test which was netcoreapp2.0. Building it with net461 would be fine but not netcoreapp2.0

I've added following to my project and it fixed it for netcoreapp2.0
**Solution/workaround:** `<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>`

- https://github.com/Microsoft/vstest/issues/1607#issuecomment-395824567
It's a NullReference exception and RemoteEndpoint is null !!! I set a breakpoint to see its IsConncted value and the value is true. I don't know how could it happen when IsConnected is true why RemoteEndpoint null.

**Solution/workaround:** Downgrade `Microsoft.NET.Test.Sdk` version to <= 15.7.0 or upgrade to >=15.9.0-preview-* Fixed: https://github.com/Microsoft/vstest/pull/1713, Yet to release.

- https://github.com/Microsoft/vstest/issues/1607#issuecomment-409236658
I tried up- and downgrading between `15.6.0` and `15.8.0`.. none of them worked.

Here's my dockerfile:

```
ARG DOTNET_VERSION=2.1

# prepare build image
FROM ubuntu:16.04 AS build

WORKDIR /tmp
ARG DOTNET_VERSION
ENV DOTNET_CLI_TELEMETRY_OPTOUT 1

RUN apt-get update \
&& apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    apt-transport-https \
    wget \
&& wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb \
&& dpkg -i packages-microsoft-prod.deb \
&& apt-get update \
&& apt-get install -y --no-install-recommends \
    dotnet-sdk-${DOTNET_VERSION} \
&& rm -rf /var/lib/apt/lists/*

# build
WORKDIR /src
COPY . .

# run all test projects
RUN set -x && for filename in $(find tests/ -iname '*.?sproj'); do dotnet test --logger:trx -r ./test-results "$filename"; exit 0; done
```
There's nothing exotic here. There must be something peculiar about my projects which causes this not to work. We have very similar docker images working for testing. I'm investigating, but any pointers would be highly appreciated.

**Solution/workaround:**  We don't know RCA for this. @efrainsteinbach Can you please create new issue with repo test project?

- https://github.com/Microsoft/vstest/issues/1607#issuecomment-409508532
Same problem here for Multi-target test project.  Only affects netcoreapp1.0 and 1.1.  Works for other frameworks (net452, net46, net472, netcoreapp2.0, netcoreapp2.1).  Works on others developer machines.  Has happened to 2 developers now.  Upgrade/downgrade/reinstall of test sdk makes no difference.  Tried reinstalling Visual Studio - no difference.  Problem seen in both Visual Studio and command line.

Only identified fix has been to re-install windows.
**Solution/workaround:**  https://github.com/Microsoft/vstest/issues/1607#issuecomment-409563971

Because too many comments I have to lock the conversion. Please create new issue with as much details as possible if above solutions/workarounds didn't work for you.

**Closed by smadala** 2018-08-02 06:43 UTC
Labels: bug
