### ISSUE TITLE
Decouple .runsettings from deployment location for in-proc data collectors

### ISSUE THREAD

**Issue by vishavpandhi** [microsoft/vstest#4021] opened 2022-09-21 16:40 UTC
## Description
When you reference an in-proc data collector in a .runsettings file, there is a field called `codebase` that must be set to the full local path to the data collector's assembly:
`<InProcDataCollector uri="datacollector://a/b/c/d/v1" assemblyQualifiedName="A.B.C.DataCollector, A.B.C.CustomDataCollector, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null" friendlyName=Custom Data Collector" enabled="True" codebase="C:\Test\Extensions\A.B.C.DataCollector\lib\net461\A.B.C.DataCollector.dll">`

Having a hard-coded local path in the .runsettings file is a big problem for the following reasons:
- In the context of test run automation, the path where extensions are downloaded to is parameterized. A change to the parameter would require a corresponding change to all .runsettings files.
If we distribute test extensions via NuGet packages, a portion of the full path mirrors the package directory structure, which can change over time. For example, the "net461" directory from the example changes when you target a different framework (e.g. "net472"). This means that any time we change the target framework of the extension, we also have to update all .runsettings files.

## Fix
- Remove the requirement for the codebase and assemblyQualifiedName field and automatically detect the in-proc data collector path. For instance, the way that out-of-proc data collectors do this is by scanning the folders defined in the TestAdaptorPath for files that end in *collector.dll and checking for a DataCollectorTypeUri attribute that matches the one specified in the .runsettings file. Perhaps in-proc data collectors could be updated to do the same.

**Comment by MarcoRossignoli** [comment] 2022-09-22 10:21
I would expect this behavior by design https://github.com/microsoft/vstest/blob/main/src/Microsoft.TestPlatform.CrossPlatEngine/DataCollection/InProcDataCollectionExtensionManager.cs#L244

Can you give it a try?

**Comment by Sher1009** [comment] 2022-09-22 21:35
The InProcDataCollector resides in `C:\Test\Extensions\Microsoft.DevDiv.TestExtensions.OptProfDataCollector\lib\net472\Microsoft.DevDiv.TestExtensions.OptProfDataCollector.dll`

When `assemblyQualifiedName` and `codebase` are removed from InProcDataCollector, I'm not seeing reference to `Microsoft.DevDiv.TestExtensions.OptProfDataCollector` which are present when `assemblyQualifiedName` and `codebase` are defined in InProcDataCollector.

I have attached the diag logs for host:
1. Logs-NoCodeBase.txt => `assemblyQualifiedName` and `codebase` are removed from InProcDataCollector
2. Logs-WithCodeBase.txt` => assemblyQualifiedName` and `codebase` are defined in InProcDataCollector.

[Logs-NoCodeBase.txt](https://github.com/microsoft/vstest/files/9629547/Logs-NoCodeBase.txt)
[Logs-WithCodeBase.txt](https://github.com/microsoft/vstest/files/9629549/Logs-WithCodeBase.txt)

**Comment by MarcoRossignoli** [comment] 2022-09-23 07:07
What I mean is not to remove AQN and codebase but simply set `codebase="Microsoft.DevDiv.TestExtensions.OptProfDataCollector.dll"`

**Comment by vishavpandhi** [comment] 2022-09-23 16:35
I updated the `InProcDataCollector ` to
`<InProcDataCollector uri="datacollector://microsoft/DevDiv/TestExtensions/OptProfDataCollector/v2" assemblyQualifiedName="Microsoft.DevDiv.TestExtensions.OptProfDataCollector, Microsoft.DevDiv.TestExtensions.OptProfDataCollector, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null" friendlyName="OptProf Data Collector" enabled="True" codebase="Microsoft.DevDiv.TestExtensions.OptProfDataCollector.dll">`

I'm getting following error:
`TpTrace Error: 0 : 11420, 3, 2022/09/23, 16:16:14.996, 830719827389, testhost.x86.exe, InProcDataCollectionExtensionManager: Error occurred while loading the InProcDataCollector : Microsoft.DevDiv.TestExtensions.OptProfDataCollector.dll , Exception Details : System.IO.FileNotFoundException: Could not load file or assembly 'file:///C:\Users\TestUser\Microsoft.DevDiv.TestExtensions.OptProfDataCollector.dll' or one of its dependencies. The system cannot find the file specified.
File name: 'file:///C:\Users\TestUser\Microsoft.DevDiv.TestExtensions.OptProfDataCollector.dll'`

In Runsettings file, `TestAdaptersPaths` is set to:
`<TestAdaptersPaths>C:\Test\Containers;C:\Test\Extensions</TestAdaptersPaths>`

**Comment by vishavpandhi** [comment] 2022-09-28 01:37
I have generated binding logs using fusinlogvw. There are a lot of logs. 
Is there a specific file I should look at or what I should be looking for in order to find why TP is loading InProcDataCollector from `C:\Users\TestUser\`

I did saw following line in the test.host log
`TpTrace Information: 0 : 8400, 14, 2022/09/28, 01:15:26.357, 34481367250, testhost.x86.exe, MSTestExecutor: Changed the working directory to C:\Users\TestUser\source\repos`

**Comment by nohwnd** [comment] 2024-07-08 17:27
This is a new feature and won't be implemented, we are focusing on adding new features to Testing.Platform instead. https://aka.ms/testingplatform

**Closed by nohwnd** 2024-07-08 17:27 UTC
Labels: enhancement
