### ISSUE TITLE
Unable to run tests from inside Visual Studio

### ISSUE THREAD

**Issue by JamesNK** [Microsoft/vstest#468] opened 2017-02-11 08:18 UTC
## Description
I want to run xunit tests for netcoreapp1.0 inside Visual Studio. I can run the tests from the command line.

## Steps to reproduce
Source code: https://github.com/JamesNK/Newtonsoft.Json/tree/vs2017

Open `Src\Newtonsoft.Json.Roslyn.sln`
Tests -> Run Tests -> All Tests

## Expected behavior
Unit tests are detected and run inside VS

## Actual behavior
Solution builds:

```
1>------ Build started: Project: Newtonsoft.Json.Roslyn, Configuration: Debug Any CPU ------
1>Newtonsoft.Json.Roslyn -> C:\Development\Source\Newtonsoft.Json\Src\Newtonsoft.Json\bin\Debug\net45\Newtonsoft.Json.dll
1>Newtonsoft.Json.Roslyn -> C:\Development\Source\Newtonsoft.Json\Src\Newtonsoft.Json\bin\Debug\net40\Newtonsoft.Json.dll
1>Newtonsoft.Json.Roslyn -> C:\Development\Source\Newtonsoft.Json\Src\Newtonsoft.Json\bin\Debug\net35\Newtonsoft.Json.dll
1>Newtonsoft.Json.Roslyn -> C:\Development\Source\Newtonsoft.Json\Src\Newtonsoft.Json\bin\Debug\net20\Newtonsoft.Json.dll
1>Newtonsoft.Json.Roslyn -> C:\Development\Source\Newtonsoft.Json\Src\Newtonsoft.Json\bin\Debug\netstandard1.0\Newtonsoft.Json.dll
1>Newtonsoft.Json.Roslyn -> C:\Development\Source\Newtonsoft.Json\Src\Newtonsoft.Json\bin\Debug\portable-net45+win8+wpa81+wp8\Newtonsoft.Json.dll
2>------ Build started: Project: Newtonsoft.Json.Tests.Roslyn, Configuration: Debug Any CPU ------
2>Newtonsoft.Json.Tests.Roslyn -> C:\Development\Source\Newtonsoft.Json\Src\Newtonsoft.Json.Tests\bin\Debug\net45\Newtonsoft.Json.Tests.dll
2>Newtonsoft.Json.Tests.Roslyn -> C:\Development\Source\Newtonsoft.Json\Src\Newtonsoft.Json.Tests\bin\Debug\net40\Newtonsoft.Json.Tests.dll
2>Newtonsoft.Json.Tests.Roslyn -> C:\Development\Source\Newtonsoft.Json\Src\Newtonsoft.Json.Tests\bin\Debug\net35\Newtonsoft.Json.Tests.dll
2>Newtonsoft.Json.Tests.Roslyn -> C:\Development\Source\Newtonsoft.Json\Src\Newtonsoft.Json.Tests\bin\Debug\net20\Newtonsoft.Json.Tests.dll
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1956,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
2>Newtonsoft.Json.Tests.Roslyn -> C:\Development\Source\Newtonsoft.Json\Src\Newtonsoft.Json.Tests\bin\Debug\netcoreapp1.0\Newtonsoft.Json.Tests.dll
2>Done building project "Newtonsoft.Json.Tests.Roslyn.csproj".
========== Build: 2 succeeded or up-to-date, 0 failed, 0 skipped ==========
```

But tests never run. There is no content in the output pane when Tests is chosen in the dropdown.

## Environment
Win10
Latest version of VS2017RC3

**Comment by codito** [comment] 2017-02-13 11:15
There are three major issues:

1. NUnit3TestAdapter needs to be referred in the test csproj to allow test discovery and execution.
2. Once it is fixed, https://github.com/nunit/nunit3-vs-adapter/issues/296 shows up.
3. For Multi TFM test projects, tests from first TFM shows up in test explorer. This is tracked in https://github.com/Microsoft/vstest/issues/298.

Changes for 1 and 2 are https://github.com/JamesNK/Newtonsoft.Json/pull/1213.

**Comment by codito** [comment] 2017-02-14 05:07
Closing this issue since we've identified the root cause and all related issues are tracked separately.

**Closed by codito** 2017-02-14 05:07 UTC
Labels: exp: ide

**Comment by piotrpMSFT** [comment] 2017-02-14 06:53
@codito could we add some diagnostics for this scenario? Can we say `no test adapter was found`?

**Comment by codito** [comment] 2017-02-14 16:11
Yep, it makes sense. https://github.com/Microsoft/vstest/issues/488
