### ISSUE TITLE
Incorrect Project Icon for NetCore UnitTestProject in SolutionExplorer

### ISSUE THREAD

**Issue by jayaranigarg** [Microsoft/vstest#716] opened 2017-04-13 12:38 UTC
## Description
On creating NetCore UnitTestProject, we should get a Test icon for the Project in solution explorer.

## Expected behavior
Project icon should be a test icon(one with beaker)

## Actual behavior
Project icon is that of ClassLibrary.

## Environment
VS 2015 (26403.0 d15rel)

**Comment by codito** [comment] 2017-04-14 00:19
Duplicate of https://github.com/Microsoft/vstest/issues/394?

**Comment by Faizan2304** [comment] 2017-07-09 08:07
Closing as a duplicate of https://github.com/Microsoft/vstest/issues/908

**Closed by Faizan2304** 2017-07-09 08:07 UTC
Labels: exp: ide
