### ISSUE TITLE
`Microsoft.TestPlatform.CoreUtilities` doesn't have a `System.Diagnostics.CodeAnalysis.DoesNotReturnAttribute`

### ISSUE THREAD

**Issue by RyuChigon** [microsoft/vstest#4638] opened 2023-08-03 03:00 UTC
## Description

Hello, I have used `Microsoft.NET.Test.Sdk` for testing my service **(.NET 6.0)**.

In my service, reflection is used for finding specific custom attributes. It is okay until Microsoft.NET.Test.Sdk **17.3.3** version.

However, when using **Microsoft.NET.Test.Sdk v17.4.0**, I faced a problem about getting custom attributes by using `MethodInfo.GetCustomAttributes(Type, bool)`.

The reason is 
- `Microsoft.VisualStudio.TestPlatform.Common.Filtering.Condition::ThrownFormatExceptionForInvalidCondition(string)` has `DoesNotReturnAttribute`
- But, `System.Diagnostics.CodeAnalysis.DoesNotReturnAttribute` could not be loaded from `Microsoft.TestPlatform.CoreUtilities`.

<br />

![assembly_ThrowFormatExceptionForInvalidCondition_17_4_0](https://github.com/microsoft/vstest/assets/60319371/d5e67210-5b5e-4c1e-bc0a-7a9e02a45aaf)

This is the IL of `Void ThrowFormatExceptionForInvalidCondition(string)`. 
It refers to `System.Diagnostics.CodeAnalysis.DoesNotReturnAttribute` of **Microsoft.TestPlatform.CoreUtilities**.

I think `Microsoft.VisualStudio.TestPlatform.Common.dll` has wrong reference about `System.Diagnostics.CodeAnalysis`.

Could you solve this problem? Thank you :)

<br/>

#### IL of Microsoft.TestPlatform.CoreUtilities v17.3.3
![assembly_CoreUtilities_17_3_3](https://github.com/microsoft/vstest/assets/60319371/5a042873-4c50-49af-bd0f-4e0a93fcb120)

It includes `DoesNotReturnAttribute`

<br />

#### IL of Microsoft.TestPlatform.CoreUtilities v17.4.0
![assembly_CoreUtilities_17_4_0](https://github.com/microsoft/vstest/assets/60319371/d1926e52-24ad-4bd0-b0d1-f3754e991c62)

not include `DoesNotReturnAttribute`

<br />

## Sample Code
```
using System.Reflection;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace TestProject1
{
    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void TestMethod1()
        {
            var targetAssemblies = AppDomain.CurrentDomain.GetAssemblies();
            var targetTypes = targetAssemblies.SelectMany(assembly => assembly.GetTypes());

            var targetMethodBindingFlag
                = BindingFlags.Instance | BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.DeclaredOnly;

            var targetMethods = targetTypes.SelectMany(type => type.GetMethods(targetMethodBindingFlag));

            foreach (var method in targetMethods)
            {
                var attributes = method.GetCustomAttributes(); // TypeLoadException !!
            }
        }
    }
}
```
Dependencies
- .NET 6.0
- Microsoft.NET.Test.Sdk (17.4.0)
- MSTest.TestAdapter (2.2.10)
- MSTest.TestFramework (2.2.10)

<br />

## Diagnostic logs

```
  Message: 
Test method TestProject1.UnitTest1.TestMethod1 threw exception: 
System.TypeLoadException: Could not load type 'System.Diagnostics.CodeAnalysis.DoesNotReturnAttribute' from assembly 'Microsoft.TestPlatform.CoreUtilities, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

  Stack Trace: 
ModuleHandle.ResolveType(QCallModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
ModuleHandle.ResolveTypeHandle(Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
CustomAttribute.FilterCustomAttributeRecord(MetadataToken caCtorToken, MetadataImport& scope, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1& derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctorWithParameters, Boolean& isVarArg)
CustomAttribute.AddCustomAttributes(ListBuilder`1& attributes, RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1 derivedAttributes)
CustomAttribute.GetCustomAttributes(RuntimeMethodInfo method, RuntimeType caType, Boolean inherit)
RuntimeMethodInfo.GetCustomAttributes(Type attributeType, Boolean inherit)
Attribute.GetCustomAttributes(MemberInfo element, Boolean inherit)
CustomAttributeExtensions.GetCustomAttributes(MemberInfo element)
UnitTest1.TestMethod1() line 21
```

## Environment

 - Windows 10
 - Visual Studio 2022

**Comment by nohwnd** [comment] 2024-07-08 08:46
Duplicate of https://github.com/microsoft/vstest/issues/4624

**Closed by nohwnd** 2024-07-08 08:46 UTC
Labels: bug
