### ISSUE TITLE
 17.2.0 failing runs after upgrade

### ISSUE THREAD

**Issue by theonlyroboboro** [microsoft/vstest#3636] opened 2022-05-12 12:21 UTC
## Description
After upgrading to dot sdk 17.2.0 the test runs are failing with below message
>
> For a defect reproducable from the vstest command line, describe the issue you've observed.

## Steps to reproduce
> What steps can reproduce the defect?
> Please share the setup, commandline for vstest.console, sample project, target
> framework etc.
upgraded the Test SDK to 17.2.0
## Expected behavior
> Share the expected output

## Actual behavior
> What is the behavior observed?

**************** Starting test execution *********************
##[debug]Generating list of args to pass to vstest.console.exe.
c:\buildagents\_tool\VsTest\17.1.0\x64\tools\net451\Common7\IDE\Extensions\TestPlatform\vstest.console.exe "@c:\buildagents\_temp\urgfi2ninhu.tmp"
Microsoft (R) Test Execution Command Line Tool Version 17.1.0
Copyright (c) Microsoft Corporation.  All rights reserved.
vstest.console.exe "c:\buildagents\3\s\AuthorizationBox.ServiceTest\bin\Release\net472\AuthorizationBox.ServiceTest.dll"
/Settings:"c:\buildagents\_temp\1hgalzum1mo.tmp.runsettings"
/Logger:"trx"
/TestAdapterPath:"c:\buildagents\3\s"
/Diag:"c:\buildagents\_temp\Attempt--1_jbxupa.diag"
Starting test execution, please wait...
Logging Vstest Diagnostics in file: c:\buildagents\_temp\Attempt--1_jbxupa.diag
2.3272
A total of 1 test files matched the specified pattern.
Data collection : Logging DataCollector Diagnostics in file: c:\buildagents\_temp\Attempt--1_jbxupa.datacollector.22-05-12_13-54-25_32093_1.diag
Blame: Attaching crash dump utility to process testhost.net472.x86 (34196).
Logging TestHost Diagnostics in file: c:\buildagents\_temp\Attempt--1_jbxupa.host.22-05-12_13-54-26_65794_1.diag
##[error]An exception occurred while invoking executor 'executor://mstestadapter/v2': Could not load file or assembly 'Microsoft.VisualStudio.TestPlatform.TestFramework, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
##[debug]Processed: ##vso[task.logissue type=error;]An exception occurred while invoking executor 'executor://mstestadapter/v2': Could not load file or assembly 'Microsoft.VisualStudio.TestPlatform.TestFramework, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
##[error]Stack trace:
##[debug]Processed: ##vso[task.logissue type=error;]Stack trace:
##[error]   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.MSTestExecutor.RunTests(IEnumerable`1 sources, IRunContext runContext, IFrameworkHandle frameworkHandle)
##[debug]Processed: ##vso[task.logissue type=error;]   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.MSTestExecutor.RunTests(IEnumerable`1 sources, IRunContext runContext, IFrameworkHandle frameworkHandle)
##[error]   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.RunTestsWithSources.InvokeExecutor(LazyExtension`2 executor, Tuple`2 executorUriExtensionTuple, RunContext runContext, IFrameworkHandle frameworkHandle)
##[debug]Processed: ##vso[task.logissue type=error;]   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.RunTestsWithSources.InvokeExecutor(LazyExtension`2 executor, Tuple`2 executorUriExtensionTuple, RunContext runContext, IFrameworkHandle frameworkHandle)
##[error]   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.<>c__DisplayClass48_0.<RunTestInternalWithExecutors>b__0()
##[debug]Processed: ##vso[task.logissue type=error;]   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.<>c__DisplayClass48_0.<RunTestInternalWithExecutors>b__0()
##[error]   at Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.PlatformThread.<>c__DisplayClass0_0.<Run>b__0()
##[debug]Processed: ##vso[task.logissue type=error;]   at Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.PlatformThread.<>c__DisplayClass0_0.<Run>b__0()
##[error]--- End of stack trace from previous location where exception was thrown ---
##[debug]Processed: ##vso[task.logissue type=error;]--- End of stack trace from previous location where exception was thrown ---
##[error]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
##[debug]Processed: ##vso[task.logissue type=error;]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
##[error]   at Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.PlatformThread.Run(Action action, PlatformApartmentState apartmentState, Boolean waitForCompletion)
##[debug]Processed: ##vso[task.logissue type=error;]   at Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.PlatformThread.Run(Action action, PlatformApartmentState apartmentState, Boolean waitForCompletion)
##[error]   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.TryToRunInSTAThread(Action action, Boolean waitForCompletion)
##[debug]Processed: ##vso[task.logissue type=error;]   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.TryToRunInSTAThread(Action action, Boolean waitForCompletion)
##[error]   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.RunTestInternalWithExecutors(IEnumerable`1 executorUriExtensionMap, Int64 totalTests)
##[debug]Processed: ##vso[task.logissue type=error;]   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.RunTestInternalWithExecutors(IEnumerable`1 executorUriExtensionMap, Int64 totalTests)
[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.5+1caef2f33e (32-bit Desktop .NET 4.0.30319.42000)
Results File: c:\buildagents\_temp\TestResults\ContainerAdministrator_816F05374FD6_2022-05-12_13_54_33.trx
Attachments:
  c:\buildagents\_temp\TestResults\fe9fe35d-bf66-403f-ac5a-242a86f16c7c\ContainerAdministrator_816F05374FD6_2022-05-12.13_54_26.coverage
##[error]Test Run Failed.
##[debug]Processed: ##vso[task.logissue type=error;]Test Run Failed.
##[debug]Exited vstest.console.exe with code 1.
##[debug]PERF: ExecuteVsTestPhase.InvokeVSTest: took 12349.8017 ms
Vstest.console.exe exited with code 1.

## Diagnostic logs
> Please share test platform diagnostics logs. Instructions to collect logs are [here](https://github.com/Microsoft/vstest-docs/blob/main/docs/diagnose.md#test-platform-diagnostics).  
> The logs may contain test assembly paths, kindly review and mask those before sharing.

## Environment
> Please share additional details about the test environment.
> Operating system, Build version of vstest.console

**Comment by dotMorten** [comment] 2022-05-13 23:20
I logged a semi-similar issue here: https://developercommunity.visualstudio.com/t/vstestconsole-fails-to-launch-packaged/10042040?space=8&q=vstest.console&sort=newest
The callstack is the same for the bottom part, and the error is similarly related wrt not being able to load an assembly.

**Comment by Evangelink** [comment] 2022-11-30 10:25
@theonlyroboboro Reading the dev community issue, it seems that the issue is fixed in newer versions of test platform. I would recommend to update to confirm this is also working for you.

**Closed** 2024-07-08 16:44 UTC
Labels: need-additional-info
