### ISSUE TITLE
vstest.console requires /testadapterpath:. when running fullclr tests

### ISSUE THREAD

**Issue by sbaid** [Microsoft/vstest#688] opened 2017-04-04 13:20 UTC
## Description
vstest.console UnitTestProject1.dll `/testadapterpath:.` 
`testadapterpath:.` should be picked by default.

## Steps to reproduce
> What steps can reproduce the defect?
> Please share the setup, commandline for vstest.console, sample project, target
> framework etc.

## Expected behavior
> Share the expected output

## Actual behavior
> What is the behavior observed?

## Environment
> Please share additional details about the test environment.
> Operating system, Build version of vstest.console

**Comment by codito** [comment] 2017-04-04 13:24
Duplicate of https://github.com/Microsoft/vstest/issues/251

**Closed by codito** 2017-04-04 13:24 UTC
