### ISSUE TITLE
Console logger ignores verbosity level when run via dotnet vstest

### ISSUE THREAD

**Issue by DNikitenko** [microsoft/vstest#2090] opened 2019-07-12 07:06 UTC
## Description

I want to see which tests are currently run, so that I increase a default value for the console logger verbosity like described in help:

> Change the verbosity level in log messages for console logger as shown below
      Example: /logger:console;verbosity=<Defaults to "minimal">
      Allowed values for verbosity: quiet, minimal, normal and detailed.

My library contains NUnit tests and uses NUnit3TestAdapter of 3.13.0 version.

## Steps to reproduce

`dotnet vstest Test.dll /logger:console;verbosity=detailed`

## Expected behavior
Detailed log containing all tests' names that were run.

## Actual behavior
The same as for verbosity=quiet:

> Microsoft (R) Test Execution Command Line Tool Version 16.1.1
Copyright (c) Microsoft Corporation.  All rights reserved.
Starting test execution, please wait...
Test Run Successful.
Total tests: 494
     Passed: 494
 Total time: 36.2356 Seconds

## Diagnostic logs
[https://github.com/DNikitenko/dotnet-test-issue/blob/master/log.txt](https://github.com/DNikitenko/dotnet-test-issue/blob/master/log.txt)

## Environment
```
dotnet --version
2.1.701
```

Run in a linux Docker container `mcr.microsoft.com/dotnet/core/sdk:2.1-stretch`.

**Comment by DNikitenko** [comment] 2019-07-23 15:03
However, it does work when using `--logger:"console;verbosity=detailed" `.

**Comment by karanjitsingh** [comment] 2019-07-26 08:20
Reproduces on ubuntu (not windows) when quotes are not given for `/logger:console;verbosity=detailed`

**Comment by singhsarab** [comment] 2019-09-19 10:17
This seems to be the way are args are getting parsed. This is not a blocking issue as there is already a workaround, Closing.
Please let me know if you disagree.

**Closed by singhsarab** 2019-09-19 10:17 UTC
Labels: bug, up-for-grabs
