### ISSUE TITLE
/blame switch cannot detect the source of vstest crash when all tests have run successfully.

### ISSUE THREAD

**Issue by pMaske** [Microsoft/vstest#1777] opened 2018-10-03 20:21 UTC
This is more of a question/puzzle I am trying to solve and looking for some advise. So our unit test are triggered from jenkins . The unit tests are run via vstest comamnd. Occasionally we run into a situation where vstest will crash after all tests are run and are completed. At that point , the jenkins job fails to complete and is aborted after timeout is reached. This results in no trx is generated because jenkins build is marked aborted.
So I started looking at why jenkins jobs are being aborted even though all tests have run successfully. I found that there are situations when vstest process crashes. When I logged on to the computer running the tests I see a vstest dialog box awaiting user input to debug or close vstest. When I clicked close, although the vstest test run got aborted but trx was generated and jenkins job was completed as expected.
I have tried using /blame but I don't find any relevant info in it. What else can I use to find and troubleshoot the cause of crashing vstest in this case.

**Comment by abhishkk** [comment] 2018-10-05 16:19
@pMaske Blame helps only when some test caused the run failure. In your case, it seems like vstest crashed unexpectedly.
We have one more feature in blame which is to create a crash dump in case of failures caused by a test, and few unexpected exceptions like StackOverflow, AccessViolation etc. Can you please try the option? https://github.com/Microsoft/vstest-docs/blob/master/RFCs/0024-Blame-Collector-Options.md

In addition, the you are seeing the `error dialog` as error dialog is enabled in windows error reporting. Can you please disable error dialog to appear in case of errors in Windows error reporting(WER). After this, dialog box will not appear awaiting user input.

**Comment by pMaske** [comment] 2018-10-05 22:13
Actually after some more debugging found out that vstest is not crashing by itself. So what happens is, Jenkins triggers the unit tests, After all tests are run the vstest is still hung and process is not completing. It appears some thread is locking it up. While Jenkins job is waiting for trx report to generate, which is not happening because vstest is hung even though all tests have run and completed, then after 200 minutes of wait when job is not completed, jenkins timeout kicks in and kills the process.
I have also seen the tests may hang at different tests every time. Some times, after all tests are run, sometimes halfway through and sometimes in way beginning, say after 15-20 tests. This is leading to a highly unstable environment. I am looking for some guidance as to how to isolate what is causing the tests to hang.

**Comment by pMaske** [comment] 2018-10-05 22:14
[2198WPFdiagnostics.txt](https://github.com/Microsoft/vstest/files/2452388/2198WPFdiagnostics.txt)

I can't find any useful info in the diagnostics file either. I saw a similar thread. https://github.com/Microsoft/vsts-tasks/issues/5601

**Comment by abhishkk** [comment] 2018-10-08 10:37
Currently we don't have option to create process dump on deadlocks.
We only support the ability to collect dump on test failure and few exceptions (like AccessViolation, StackOverflow).

I have opened an issue https://github.com/Microsoft/vstest/issues/1779 to support process dump creation on session timeout which will help debugging deadlocks in future.

For now, you can do following:
1. Log in the machine where tests are stuck and take process dump manually.
2. Analyze created process dump to check which threads are stuck. Threads will point you to exact code which is causing the issue.
3. Till you figure out the issues from process dump, you can add [session timeout](https://github.com/Microsoft/vstest-docs/blob/master/RFCs/0011-Test-Session-Timeout.md) in your tests. Test will abort on session timeout and trx should get generated.

**Comment by abhishkk** [comment] 2018-10-12 09:44
@pMaske Closing this issue as we are tracking this new support request via https://github.com/Microsoft/vstest/issues/1779

**Closed by abhishkk** 2018-10-12 09:44 UTC
