### ISSUE TITLE
Test discovery leaves too many files locked - causes problems for metaprogramming

### ISSUE THREAD

**Issue by mgravell** [Microsoft/vstest#661] opened 2017-03-25 21:31 UTC
## Description

When using `dotnet test` (and presumably other approaches), the discovery phase locks dll files, which are kept  locked for the duration of the execution phase. This means that if any of the files are actually *outputs* (meta-programming artefacts), they will prevent the second (etc) test runs from executing successfully

## Steps to reproduce

- write a test that emits a dll (meta-programming, `AssemblyBuilder` etc) to the test folder during execution
- run the test (file is generated)
- run the test again (file cannot be regenerated as it is locked by discovery)

A more complete set of repro steps (including command-line and git commit) is [in this report](https://github.com/xunit/xunit/issues/1183#issue-217001302) (I initially filed against `xunit`, and was redirected here)

## Expected behavior

Subsequent test runs succeed, via one of (I have no strong views on which):

- not locking files between discovery and execution
- allowing an inclusion/exclusion filter **from `dotnet` CLI** to prevent unwanted locks from happening
- implementing shadow-copy so that it doesn't matter what is locked (in the transient folder)
- having obvious options (presumably in `dotnet` tooling hooks) to allow the test directory to be cleaned between runs

## Actual behavior

File is locked; subsequent test runs fail

## Environment

Windows 10  x64, `dotnet` 1.0.0, `vstest.console` 15.0.26228.0

**Comment by aelij** [comment] 2017-03-25 22:43
One more option is to use `System.Reflection.Metadata` for discovery instead of `Assembly.Load`, then load only the assemblies that actually have extensions. Here's some [sample code](https://github.com/aelij/FasterReflection) I've used for similar purposes.

**Comment by codito** [comment] 2017-04-02 04:06
@mgravell I could clean the output folder between test runs by adding following `Target` to test project. Hope this will help workaround the issue.

```xml
  <Target Name="CleanGeneratedTestFiles" BeforeTargets="PrepareForBuild" Condition="'$(TargetFramework)' != ''">
    <RemoveDir Directories="$(OutputPath)" />
  </Target>
```

If I've a test project `test.dll` and it generates `a.dll` during test execution. Now `a.dll` is generated during first run, for the second run we observe `a.dll` is getting loaded during `dotnet test` invocation. So when the test actually executes, it cannot generate/overwrite `a.dll` again. Since `a.dll` is generated at runtime, `test.dll` doesn't depend on `a.dll`, so it's weird why `a.dll` should get loaded during second test run (for discovery or execution). Is this understanding correct?

From a conceptual standpoint, the testhost process (which executes the test) and test platform has no knowledge of any test framework, it doesn't load the assemblies (it's a bug if it does). Knowledge of test framework and finding the tests in an assembly is with an adapter. Some adapters can possibly use metadata approach suggested by @aelij, a few frameworks allow code to be executed during discovery (e.g. xunit), they may not be able to use it.

**Comment by aelij** [comment] 2017-04-02 09:00
I think the test host loads assemblies in order to discover extensions (see [here](https://github.com/Microsoft/vstest/blob/85b615b4c7d209e4696100d699725ee42baf8ea2/src/Microsoft.TestPlatform.Common/ExtensionFramework/TestPluginDiscoverer.cs#L168) for example). Couldn't that also be a problem?

**Comment by Mnuzz** [comment] 2017-05-13 06:57
See https://github.com/Mnuzz/AutoHotkey.FSharp/tree/31d34922e1163d1a1fe98fff2e66976df2f9039f for a (possible) self-contained reproduction of this issue from VS Test Runner.

**Comment by llehn** [comment] 2017-08-15 22:22
The dll locking is absolutely annoying. Every build = fail. Need to kill discoveryengine first before build.

**Comment by mayankbansal018** [comment] 2017-11-30 11:58
@mgravell The issue is because the TestMethods are creating some dll on runtime, & are unable to clean them up after they are executed, since the newly created dll's are loaded in the host process. This causes an issue during second run as the dll is already created, hence the Testmethod cannot create it again.
Can you please try the [solution codito proposed.](https://github.com/Microsoft/vstest/issues/661#issuecomment-290963389)

@llehn the discoveryengine has been replaced by our new testplatform in VS2017.5

**Comment by mayankbansal018** [comment] 2017-12-04 12:25
@mgravell , can you please review my above comment, & confirm if it works for you?

**Comment by mayankbansal018** [comment] 2017-12-08 11:02
@mgravell , as per explanation [above](https://github.com/Microsoft/vstest/issues/661#issuecomment-348168281), I'm closing issue. Please reopen it if there is a need to discuss more on it.

**Closed by mayankbansal018** 2017-12-08 11:02 UTC
Labels: exp: cli, question

**Comment by smadala** [comment] 2018-06-13 06:27
@Aaronontheweb Can you please create new issue with detail repro steps?
