### ISSUE TITLE
vstest can't run NUnit tests if project contains any CodedUI test

### ISSUE THREAD

**Issue by vs-odessa** [Microsoft/vstest#1868] opened 2018-12-12 14:47 UTC
## Description
Unable to run NUnit tests from dll by vstest.console.exe if project contains any Coded UI test

## Steps to reproduce
1) Create a new Project of type "Coded UI Test Project" (Supported in VS Enterprise edition)
2) Remove default Coded Ui test that was created
3) Using Nuget, Install NUnit3 framework & NUnit3TestAdapter
4) Add new class with using NUnit.Framework namespace. Add nunit [TestFixture] attribute to class and new test Method with [TestAttribute]
5) Build project and run all dll by vstest.console.exe
6) Add new empty test in another file with CodedUI type.
7) Rebuild project, run tests from dll again 

## Expected behavior
Both test types (NUnit & Coded UI) should be run successfully

## Actual behavior
After adding CodedUI test, nunit tests can't be loaded and run
(failed to load *.dll by NUnit adapter)

## Diagnostic logs

```
vstest.console.exe NUnitCodedUi.dll
Microsoft (R) Test Execution Command Line Tool Version 15.7.2
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
NUnit Adapter 3.11.2.0: Test execution started
Running all tests in C:\GIT_ROOT\CCS_AUTO_NEW\CCS_Auto\NUnitCodedUi\bin\Debug\NUnitCodedUi.dll
   NUnit failed to load C:\GIT_ROOT\CCS_AUTO_NEW\CCS_Auto\NUnitCodedUi\bin\Debug\NUnitCodedUi.dll
```

If I try to run the same dll with nunit3-console.exe, I get:

`Could not load file or assembly 'Microsoft.VisualStudio.QualityTools.UnitTestFramework, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.`

I don't expect to run CodedUI with nunit runner, but expect to run both NUnit & CodedUI with vstest runner.

## Environment
> Operating system - Windows 10x64, Build version of vstest.console -15.7.2
Projects created by VS 2017 Enterprise

**Comment by mayankbansal018** [comment] 2018-12-13 09:16
@vs-odessa when running via CLI can you pass both test dll's as input, & enable diagnostics logs via --diag:<path_to_some_file> & share those log files with us.

@singhsarab from IDE, this could be related to the adapter lookup enhancement, where default adapters are not probed if a particular setting is checked. Can you point us to that option.

**Comment by singhsarab** [comment] 2018-12-13 11:56
@mayankbansal018 The scenario is that the user has both Coded UI and Nunit tests in the same project.

@vs-odessa I can reproduce the issue.
It is the nunit adapter which is not able to load the dependencies like the Microsoft.VisualStudio.QualityTools.UnitTestFramework and others.

When you run the test via vstest.console, nunit adapter gets loaded in the testhost takes over to run the tests. It then creates another appdomain and tries to load and run the tests in this new appdomain.
Since the adapter is not aware of the location of this UnitTestFramework dll, it fails to load the dll.

It is actually not recommended for you to have both these tests in the same dll.
There is something that you can do though, you configure the run using runsettings and set ```DisableAppDomain``` to true. Refer [here](https://github.com/Microsoft/vstest-docs/blob/master/docs/configure.md)

**Comment by nigurr** [comment] 2018-12-17 06:47
@vs-odessa as mentioned, We recommend to use different test adapters for each project. Since CodedUI can't be loaded by Nunit/external adapters, we suggest the above approach.
Closing this issue as we don't have any plans to migrate from this behaviour

**Closed by nigurr** 2018-12-17 06:47 UTC
