### ISSUE TITLE
Project Name Limitation

### ISSUE THREAD

**Issue by alansbraga** [microsoft/vstest#2404] opened 2020-04-16 17:59 UTC
Hi, I've created a project with a big name and the project do not run.
```cmd
md .\SieconWeb.DocumentoAnexos.Testes\ 
cd .\SieconWeb.DocumentoAnexos.Testes\
dotnet new mstest
dotnet test
```
The error is about VSTEST_CONNECTION_TIMEOUT, I won't print the entire message because my windows is in Portuguese and the message is not going to help you, but the steps are pretty simple.

The problem also happens with xunit template.

I've changed the name and It worked it.
I think it would be better if you change the message in this case, I've spent a lot of time trying to figure the real problem out, I thought it was the code inside my test.

Thank you in advance.

**Comment by nohwnd** [comment] 2020-04-17 07:34
Hello, works just fine for me, could you send the error message anyway? I don't understand Portugese but it will still contain interesting information like the version being used: 

```shell

C:\Projects\temp> md .\SieconWeb.DocumentoAnexos.Testes\


    Directory: C:\Projects\temp

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          17/04/2020    09:33                SieconWeb.DocumentoAnexos.Testes

C:\Projects\temp> cd .\SieconWeb.DocumentoAnexos.Testes\
C:\Projects\temp\SieconWeb.DocumentoAnexos.Testes> dotnet new mstest
The template "Unit Test Project" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on C:\Projects\temp\SieconWeb.DocumentoAnexos.Testes\SieconWeb.DocumentoAnexos.Testes.csproj...
  Determining projects to restore...
  Restored C:\Projects\temp\SieconWeb.DocumentoAnexos.Testes\SieconWeb.DocumentoAnexos.Testes.csproj (in 1,59 sec).

Restore succeeded.

C:\Projects\temp\SieconWeb.DocumentoAnexos.Testes> dotnet test
Test run for C:\Projects\temp\SieconWeb.DocumentoAnexos.Testes\bin\Debug\netcoreapp3.1\SieconWeb.DocumentoAnexos.Testes.
dll(.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.6.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.

Test Run Successful.
Total tests: 1
     Passed: 1
 Total time: 2,3861 Seconds
```

**Comment by alansbraga** [comment] 2020-04-17 12:03
That's the message:
```
Execução de teste para C:\tmp\SieconWeb.DocumentoAnexos.Testes\bin\Debug\netcoreapp3.1\SieconWeb.DocumentoAnexos.Testes.dll(.NETCoreApp,Version=v3.1)
Ferramenta de Linha de Comando de Execução de Teste da Microsoft (R) Versão 16.5.0
Copyright (c) Microsoft Corporation. Todos os direitos reservados.

Iniciando execução de teste, espere...

1 arquivos de teste no total corresponderam ao padrão especificado.
O processo vstest.console falha ao se conectar ao processo testhost após 90 segundos. Isso pode ocorrer devido à lentidão do computador. Defina a variável de ambiente VSTEST_CONNECTION_TIMEOUT para aumentar o tempo limite.

Execução de Teste Anulada.
```
Same machine, same folder just changing the name:

```powershell
PS C:\tmp> md .\SieconWeb.DA.Testes\


    Directory: C:\tmp

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          17/04/2020    09:00                SieconWeb.DA.Testes

PS C:\tmp> cd .\SieconWeb.DA.Testes\
PS C:\tmp\SieconWeb.DA.Testes> dotnet new mstest
The template "Unit Test Project" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on C:\tmp\SieconWeb.DA.Testes\SieconWeb.DA.Testes.csproj...
  Restauração concluída em 1,12 sec para C:\tmp\SieconWeb.DA.Testes\SieconWeb.DA.Testes.csproj.

Restore succeeded.

PS C:\tmp\SieconWeb.DA.Testes> dotnet test
Execução de teste para C:\tmp\SieconWeb.DA.Testes\bin\Debug\netcoreapp3.1\SieconWeb.DA.Testes.dll(.NETCoreApp,Version=v3.1)
Ferramenta de Linha de Comando de Execução de Teste da Microsoft (R) Versão 16.5.0
Copyright (c) Microsoft Corporation. Todos os direitos reservados.

Iniciando execução de teste, espere...

1 arquivos de teste no total corresponderam ao padrão especificado.

Execução de Teste Bem-sucedida.
Total de testes: 1
     Aprovados: 1
Tempo total: 3,0685 Segundos
PS C:\tmp\SieconWeb.DA.Testes>
```


Thank you very much!

**Comment by Evangelink** [comment] 2022-02-11 11:30
I have just tested also and I cannot reproduce the issue so I am closing this issue. If you are still experiencing the issue please let us know.

**Closed by Evangelink** 2022-02-11 11:30 UTC
