### ISSUE TITLE
Run Tests from context is not working as expected

### ISSUE THREAD

**Issue by singhsarab** [Microsoft/vstest#537] opened 2017-02-23 13:37 UTC
## Description
> Run Tests from context for a test case ends up running all the tests in the class instead of running only that particular test case for Xunit tests.

**Note :** This does not happen for MSTest based tests.

## Steps to reproduce
> Create a XUnit Test project (.NET Core) 
> Add 2 test methods to the project. Build succeeds. Click “Run All” and run passed.
> Right-click inside one of the tests and click “Run Tests”

## Expected behavior
```
> ------ Run test started ------
[xUnit.net 00:00:01.5624736]   Starting:    XUnitTestProject1
[xUnit.net 00:00:02.0680267]   Finished:    XUnitTestProject1
========== Run test finished: 1 run (0:00:03.516678) 
```

## Actual behavior
```
------ Run test started ------
[xUnit.net 00:00:01.5624736]   Starting:    XUnitTestProject1
[xUnit.net 00:00:02.0680267]   Finished:    XUnitTestProject1
========== Run test finished: 3 run (0:00:03.516678) 
```

**Comment by codito** [comment] 2017-07-17 16:43
@Faizan2304 @singhsarab do we know the root cause of this issue?

**Comment by Faizan2304** [comment] 2017-07-18 05:23
@codito : No, we need to debug it to get root cause?

**Comment by sharwell** [comment] 2017-10-12 13:51
I believe this used to work. It's certainly highly frustrating that it doesn't now.

My test class has positive tests and negative tests. I'm trying to debug a test to find out why an exception is thrown, but when it runs all tests in the class it keeps stopping at exceptions thrown by tests unrelated to the one I right clicked in the editor. The only workaround I've found is locating the test via Test Explorer and running it from the context menu there - a time consuming and distracting process.

**Comment by smadala** [comment] 2017-10-19 11:49
May be related to https://github.com/xunit/xunit/issues/1140#issuecomment-284394096, Update xunit version to 2.3 beta 1. @sharwell Can you please confirm it?

**Comment by sharwell** [comment] 2017-10-19 15:18
@smadala I was using 2.3 Beta 5. I updated to 2.3.0 and the problem appears resolved.

**Comment by smadala** [comment] 2017-10-19 15:33
@sharwell Thanks for confirming, looks like it was broken somewhere between beta1 to beta5. As issue related to xunit, closing this.

**Closed by smadala** 2017-10-19 15:33 UTC
Labels: bug, exp: ide
