### ISSUE TITLE
Test Explorer is not able to navigate to Test Code when test comes from an abstract class in a different assembly

### ISSUE THREAD

**Issue by pshilviu** [microsoft/vstest#4058] opened 2022-10-11 10:46 UTC
## Description
Test Explorer is not able to resolve test source code when sharing a test class from a different project/assembly in the same solution.

## Steps to reproduce
- A sample project has been created here: https://github.com/pshilviu/xunit_abstract_class/tree/main
- Open HelloWorldApi.sln in VS2022, Build and open Test Explorer
- Observe that for test BaseDiffAssembly_ShouldBeDecoratedWithExcludeFromCodeCoverageAttribute "No source information" is displayed and one cannot navigate to it using F12
![image](https://user-images.githubusercontent.com/67609302/195069346-312017fc-fc9b-4d1e-bee3-6d8219a4449a.png)  
- Observe that for test BaseSameAssembly_ShouldBeDecoratedWithExcludeFromCodeCoverageAttribute source information is displayed and one can navigate to it using F12  
![image](https://user-images.githubusercontent.com/67609302/195070131-116f5142-ad97-4d7b-aba2-1bedd9e4f5d2.png)  

- Similar information is explained in the repository [README.md](https://github.com/pshilviu/xunit_abstract_class/blob/main/README.md)

## Expected behavior
Test Explorer to find Source code of the test and ability to navigate to test code

## Actual behavior
Test Explorer not able to find source code of the test and one is not able to easily navigate to the test. Instead it has to search for test by name.

## Environment
Windows 10, Visual Studio 2022 17.3.4, NET 6.0

## Other Notes
- The same behaviour is observed regardless of using xUnit or MsTest
- Using Resharper's Test Window one is able to navigate to the test codes in both scenarios

**Comment by fhnaseer** [comment] 2022-10-12 11:38
Duplicate of https://github.com/microsoft/testfx/issues/1281

https://github.com/microsoft/testfx/issues/1281#issuecomment-1259078135

**Closed by fhnaseer** 2022-10-12 11:38 UTC

**Comment by pshilviu** [comment] 2022-10-13 10:47
While I was so excited for this to have been fixed, I can confirm it's not after testing it in 17.4.0 Preview 3.0. 

![image](https://user-images.githubusercontent.com/67609302/195577108-98ebfd6d-1613-4592-8900-047a29ce6fc4.png)

**Comment by fhnaseer** [comment] 2022-10-13 14:19
@Evangelink do you have info about VS version containing this fix?

**Comment by Evangelink** [comment] 2022-10-13 14:36
Sadly no.
