### ISSUE TITLE
Specifying EnvironmentVariables in .runsettings doesn't work

### ISSUE THREAD

**Issue by danielcor** [microsoft/vstest#2820] opened 2021-03-11 21:34 UTC
Even using the XML specified in a unit test in this project, I get an error parsing the XML in the diagnostics:
 Invalid settings 'RunConfiguration'. Unexpected XmlElement: 'EnvironmentVariables'.

<RunSettings>
     <RunConfiguration>
             <EnvironmentVariables>
                     <RANDOM_PATH>C:\temp</RANDOM_PATH>
             </EnvironmentVariables>
     </RunConfiguration>
 </RunSettings>
 
 I am specifying "dotnet test -d diag.txt -s Tests\Dev.runsettings <directory>"   I have also tried using dotnet vstest with the same results.

Ideas?

**Comment by Haplois** [comment] 2021-03-11 21:36
Duplicate of https://github.com/microsoft/vstest/issues/2819.

**Closed by Haplois** 2021-03-11 21:36 UTC
