### ISSUE TITLE
Do we need Microsoft.NET.Test.Sdk package to run tests?

### ISSUE THREAD

**Issue by srivatsn** [Microsoft/vstest#986] opened 2017-08-07 23:51 UTC
_From @alrz on August 3, 2017 20:27_

This is requested by Rider, I wonder if that is not the case for VS/RS.

_Copied from original issue: dotnet/roslyn#21313_

**Comment by srivatsn** [comment] 2017-08-07 23:51
_From @sharwell on August 3, 2017 20:41_

I'm not sure I understand the question.

The main items added by Microsoft.NET.Test.Sdk are the UnitTestContainer capability and setting the IsTestProject property. The former is supposed to be the trigger for tests, but several older test adapter implementations do not add it. Roslyn [does add it](https://github.com/dotnet/roslyn/blob/39536105ffaa7752d6cbaac258d7daf9f2ea6763/build/Targets/Imports.targets#L148), so the Microsoft.NET.Test.Sdk package should not be needed for an IDE to know which projects are test projects and which ones are not.

**Comment by srivatsn** [comment] 2017-08-07 23:51
_From @alrz on August 3, 2017 20:45_

I've found this https://github.com/Microsoft/vstest/issues/515 I think that's the issue I'm encountering.

**Comment by srivatsn** [comment] 2017-08-07 23:51
_From @Pilchie on August 7, 2017 22:8_

@ManishJayaswal or @srivatsn  - do you know the right home for this?

**Comment by srivatsn** [comment] 2017-08-07 23:51
Yes the test SDK does a few things like generate a Main method to keep the compiler happy and sets a few other things. There was an investigation about what we can do to either remove the requirement or make the Test.Sdk a real MSBuild SDK instead of a package. Moving to Microsoft/vstest

**Comment by Faizan2304** [comment] 2017-08-08 15:15
@alrz 
`Microsoft.NET.Test.Sdk` does lots of things. Most of the things are already covered by @srivatsn. One very important work of Microsoft.NET.Test.Sdk is that it takes the dependency of  nuget package Microsoft.TestPlatform.TestHost which is needed to run the test. Without this test will not run for framework netcoreapp1.x. 
We are creating Microsoft.NET.Test.Sdk this way because we want to bundle all the necessary things which are needed to run test in one place. 

You can take individual nuget reference of  `Microsoft.TestPlatform.TestHost`  and run tests but it will be better if you will take nuget reference of `Microsoft.NET.Test.Sdk`

**Comment by alrz** [comment] 2017-08-08 15:56
so, shouldn't we add it to Roslyn? if not how can I workaround this for now (besides referencing it from all test projects)?

**Comment by sharwell** [comment] 2017-08-08 16:24
@alrz It's still not clear to me what the benefit would be if we add it to Roslyn. Can you describe a developer scenario which currently fails but would work if we referenced that package?

**Comment by alrz** [comment] 2017-08-10 12:46
@sharwell 

![image](https://user-images.githubusercontent.com/3105979/29170789-5c600f56-7def-11e7-9557-0b5b05a29644.png)

I get this in Rider. This was not shown in the past. I didn't check yet if this is required in older commits.

**Comment by sharwell** [comment] 2017-08-10 15:37
@alrz Ah. This was caused by #20569. The solution is #21017, but it's blocked due to some performance concerns that need to be thoroughly tested to make sure we don't break developers working on Roslyn.

**Comment by alrz** [comment] 2017-08-10 18:16
@sharwell 

I merged dotnet/roslyn#21017 locally but the issue remains -- Rider, R# and VS "Run Tests" are unable to discover any tests. I have no idea whether this belongs to either of IDEs or some test config/dependency.

**Comment by sharwell** [comment] 2017-08-10 18:22
@alrz After merging it, you'll need to re-run the restore script and then rebuild the entire solution. After that things should be working again.

**Comment by Faizan2304** [comment] 2017-08-14 12:35
@alrz : Did you get your answer? Can i close this issue?

**Comment by alrz** [comment] 2017-08-14 13:20
I no longer use IDE to run tests so this discussion is moot. Feel free to close the issue.

**Closed** 2017-08-14 19:06 UTC
Labels: Area-External, question
