### ISSUE TITLE
dotnet test (2.0 ) on macos does not discover unit tests (xunit)

### ISSUE THREAD

**Issue by mattcotton-justgiving** [Microsoft/vstest#1058] opened 2017-09-08 16:28 UTC
## Description
dotnet test does not discover tests

## Steps to reproduce
Create a dotnet core 2.0 classlib project
Add xunit package refs. this is my resulting .csproj:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="2.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.3.0" />
    <PackageReference Include="Moq" Version="4.7.99" />
    <PackageReference Include="xunit" Version="2.2.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.2.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..">
      <Project>{XXXXXf95-c9c0-4ef0-b869-0194684e8519}</Project>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <Content Include="application.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
```
from the csproj folder run:
`dotnet test`

**NB. I have tried the `ulimit -n 4096` trick and re-booted. Still failing.**

## Expected behavior
Discover the tests and run them

## Actual behavior
Got the message:
```
No test is available in /Users/your.dll. Make sure test project has a nuget reference of package "Microsoft.NET.Test.Sdk" and framework version settings are appropriate and try again.
```

## Environment
Running on macos 10.12.6
dotnet --info:
```
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

**Comment by mattcotton-justgiving** [comment] 2017-09-08 16:39
Seems like it doesn't like having netstandard2.0 as the TFM.
Noticed that `dotnet new xunit` didn't offer a `-f` param and created csproj as `netcoreapp2.0`.
So I changed the TFM to `netcoreapp2.0` and it started working.

**Comment by harshjain2** [comment] 2017-09-10 11:16
This is by design. For dotnet core projects, TFM should be netcoreapp*.* (netcoreapp1.0, netcoreapp1.1, netcoreapp2.0)

**Comment by codito** [comment] 2017-09-11 14:24
Closing this as by design.

**Closed by codito** 2017-09-11 14:24 UTC
Labels: help wanted, question
