### ISSUE TITLE
Trx logger doesnt support 'Author' attribute for NUnit adapter

### ISSUE THREAD

**Issue by Shyam-Gupta** [Microsoft/vstest#887] opened 2017-06-23 13:05 UTC
## Description
Trx logger doesnt support 'Author' attribute for NUnit adapter## Steps to reproduce

##Steps to reproduce
1. Create some Nunit tests and specify 'Author' attribute against them
2. Run the tests using vstest.console.exe and in command line specify option: /logger:trx
3. Open the generated trx file and note that 'Author' field has not got added in it

## Expected behavior
Author field should be present

## Actual behavior
Author field is not present

**Comment by codito** [comment] 2017-07-07 12:37
Duplicate of https://github.com/Microsoft/vstest/issues/98. Trx logger is not currently extensible.

**Closed by codito** 2017-07-07 12:37 UTC
