### ISSUE TITLE
TFS. Test project has 100 tests. However, final .Trx file contains results of 60 tests (50 passed 10 failed).

### ISSUE THREAD

**Issue by silentnightwalk** [Microsoft/vstest#1979] opened 2019-04-05 15:34 UTC
## Description

I'm running `dotnet vstest` command from TFS. Test project has 100 tests. However, final .Trx file contains results of 60 tests (50 passed 10 failed). They pass when i run some of the missing tests locally.

Also found 2 seemingly similar questions on stackoverflow without satisfying answer:
https://stackoverflow.com/questions/36680473/tfs-not-all-tests-are-run-although-the-build-is-green
https://stackoverflow.com/questions/36133956/vstest-console-exe-randomly-misses-some-tests

## Steps to reproduce

`Exec` is used to run tests:
```
<Target Name="CoreTestConfiguration">
    <PropertyGroup>
      <ImportPath Condition="Exists('$(SolutionRoot)\###########\SolutionDefines.targets')">$(SolutionRoot)\##############\SolutionDefines.targets</ImportPath>
    </PropertyGroup>
  <Exec Command="&quot;C:\Program Files\dotnet\dotnet.exe&quot; vstest /Blame /Diag:&quot;$(SolutionRoot)##########################\bin\Release\diag.txt&quot; &quot;$(SolutionRoot)###########################\#################s.dll&quot;  /logger:trx;LogFileName=&quot;$(SolutionRoot)\#################################Tests\bin\Release\TestOutput.trx&quot; /Settings:&quot;$(SolutionRoot)\############################################ests\bin\Release\#################sts.runsettings&quot;"
  ContinueOnError="true"/>
</Target>
```
- I haven't yet figured out how to find the `Sequence.xml` file even if i specify the results folder as default and even if I look in the default results folder.

The `runsettings` file has the following contents:
```
<RunSettings>
  <RunConfiguration>
    <TestSessionTimeout>4400000</TestSessionTimeout>
    <TestTimeout>342000</TestTimeout>
    <TargetPlatform>X64</TargetPlatform>
    <TargetFrameworkVersion>.NETCoreApp,Version=v2.0</TargetFrameworkVersion>

    <!-- same for net461: but different count of tests in final trx, say 65/100 not 60/100. Still (65 != 100) -->
    <!-- <TargetFrameworkVersion> 
        .NETFramework,Version=v4.6.1
    </TargetFrameworkVersion> -->

    <DesignMode>False</DesignMode>
    <CollectSourceInformation>False</CollectSourceInformation>
  </RunConfiguration>
  <LoggerRunSettings>
    <Loggers>
      <Logger friendlyName="blame" enabled="True" />
      <Logger friendlyName="Console" uri="logger://microsoft/TestPlatform/ConsoleLogger/v1" assemblyQualifiedName="Microsoft.VisualStudio.TestPlatform.CommandLine.Internal.ConsoleLogger, vstest.console, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" codeBase="C:\Program Files\dotnet\sdk\2.1.503\vstest.console.dll" enabled="True" />
    </Loggers>
  </LoggerRunSettings>
  <DataCollectionRunSettings>
    <DataCollectors>
      <DataCollector friendlyName="blame" enabled="True">
        <Configuration>
          <ResultsDirectory>#####################\bin\Release</ResultsDirectory>
          <!-- i've tried different result dirs here but haven't yet managed to find the Sequence.xml file -->
        </Configuration>
      </DataCollector>
    </DataCollectors>
  </DataCollectionRunSettings>
</RunSettings>
```

Here is a part of `.csproj` file of the tests project:
```
<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="$(SolutionDir)SolutionDefines.targets" Condition="exists('$(SolutionDir)SolutionDefines.targets')" />

  <PropertyGroup Condition=" !$(DefineConstants.Contains(';NETCORESOLUTION')) ">
    <TargetFrameworks>net461;</TargetFrameworks>
    <IsCodedUITest>False</IsCodedUITest>
    <AppendTargetFrameworkToOutputPath>true</AppendTargetFrameworkToOutputPath>
    <TestProjectType>UnitTest</TestProjectType>
    <GenerateAssemblyVersionAttribute>false</GenerateAssemblyVersionAttribute>
    <GenerateAssemblyInformationalVersionAttribute>
        false
    </GenerateAssemblyInformationalVersionAttribute>
  </PropertyGroup>

  <PropertyGroup Condition=" $(DefineConstants.Contains(';NETCORESOLUTION')) ">
    <TargetFrameworks>netcoreapp2.0;</TargetFrameworks>
    <OutputType>exe</OutputType>
    <IsCodedUITest>False</IsCodedUITest>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <TestProjectType>UnitTest</TestProjectType>
    <GenerateAssemblyVersionAttribute>false</GenerateAssemblyVersionAttribute>
    <GenerateAssemblyInformationalVersionAttribute>
        false
    </GenerateAssemblyInformationalVersionAttribute>
  </PropertyGroup>

  ...
  <ItemGroup>
    <PackageReference Include="MSTest.TestAdapter" Version="1.1.18" />
    <PackageReference Include="MSTest.TestFramework" Version="1.1.18" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
  </ItemGroup>
  ...

</Project>
``` 

`SolutionDefines.targets` has the following contents:
```
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <PropertyGroup>
        <DefineConstants>$(DefineConstants);NETCORESOLUTION</DefineConstants>
    </PropertyGroup>
</Project>
```

## Expected behavior
Expected is that 100 out of 100 test results are shown in the result .trx file.

## Actual behavior
I don't know why, but only some test results are in the result .trx file. May be not all tests discovered.  May be some test hangs. May be some test crashes the app. I've tried different ways (Result directories) to get the /Blame `Sequence.xml`, but haven't yet managed to obtain it. 

**UPD1:** The time the build takes approximately equals TestSessionTimeout+2minutes = ~77 min.

**UPD2:** When I specify `dotnet vstest /Tests:OnlyOneOfTheMissingTests ...` then finally there is no .trx file at all. However, build is successfull with exitCode = 0. 

**UPD4:** Afrer UPD3, I also specified `dotnet vstest /Tests:ANOTHER_OnlyOneOfTheMissingTests ...`. This time I got the .trx file with this another test results (passed).

## Diagnostic logs
The `diag.txt` doesn't contain the names of the lost tests if searched by keyword == (TestName). However, it contains some info about those in final .trx. I haven't tried to search every single test though. Diag file is too big and contains too many places to erase (swap with -----). If possible, i would ask you how to get useful info from diag.txt for solving this issue, instead of erasing the paths. Thanks.

**UPD2:** Here is a part of `diag.txt` for case when I specify `dotnet vstest /Tests:OnlyOneOfTheMissingTests ...` and finally there is no .trx file at all in this case. Also, search of the `diag.txt` with keyword='OnlyOneOfTheMissingTests' doesn't find anything:
```
TpTrace Verbose: 0 : 8132, 9, 2019/04/05, 19:53:19.360, 5166694824762, vstest.console.dll, TestRequestSender.EndSession: Sending end session.
TpTrace Warning: 0 : 8132, 8, 2019/04/05, 19:53:19.372, 5166694867377, vstest.console.dll, TestHostManagerCallbacks.ErrorReceivedCallback Test host standard error line: 
TpTrace Information: 0 : 8132, 4, 2019/04/05, 19:53:19.383, 5166694904891, vstest.console.dll, TestHostManagerCallbacks.ExitCallBack: Testhost processId: 6820 exited with exitcode: 0 error: ''
TpTrace Information: 0 : 8132, 4, 2019/04/05, 19:53:19.383, 5166694905571, vstest.console.dll, TestRequestSender.OnClientProcessExit: Test host process exited. Standard error: 
TpTrace Information: 0 : 8132, 4, 2019/04/05, 19:53:19.383, 5166694905916, vstest.console.dll, SocketServer.Stop: Stop server endPoint: 127.0.0.1:22222
TpTrace Information: 0 : 8132, 4, 2019/04/05, 19:53:19.383, 5166694906144, vstest.console.dll, SocketServer.Stop: Cancellation requested. Stopping message loop.
TpTrace Warning: 0 : 8132, 9, 2019/04/05, 19:53:19.383, 5166694906491, vstest.console.dll, ProxyOperationManager: Timed out waiting for test host to exit. Will terminate process.
TpTrace Verbose: 0 : 8132, 9, 2019/04/05, 19:53:19.394, 5166694945213, vstest.console.dll, DiscoveryRequest.DiscoveryComplete: Starting. Aborted:False, TotalTests:109
TpTrace Verbose: 0 : 8132, 9, 2019/04/05, 19:53:19.394, 5166694945644, vstest.console.dll, TestRequestSender.EndSession: Sending end session.
TpTrace Error: 0 : 8132, 9, 2019/04/05, 19:53:19.443, 5166695114070, vstest.console.dll, LengthPrefixCommunicationChannel.Send: Error sending data: System.IO.IOException: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.BufferedStream.Flush()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.LengthPrefixCommunicationChannel.Send(String data).
TpTrace Warning: 0 : 8132, 9, 2019/04/05, 19:53:19.446, 5166695125834, vstest.console.dll, ProxyOperationManager: Failed to end session: Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.Interfaces.CommunicationException: Unable to send data over channel. ---> System.IO.IOException: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.BufferedStream.Flush()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.LengthPrefixCommunicationChannel.Send(String data)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.LengthPrefixCommunicationChannel.Send(String data)
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TestRequestSender.EndSession()
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.Close()
TpTrace Warning: 0 : 8132, 9, 2019/04/05, 19:53:19.446, 5166695126315, vstest.console.dll, ProxyOperationManager: Timed out waiting for test host to exit. Will terminate process.
TpTrace Warning: 0 : 8132, 9, 2019/04/05, 19:53:19.447, 5166695127996, vstest.console.dll, TestLoggerManager.HandleDiscoveredTests: Ignoring as the object is disposed.
TpTrace Verbose: 0 : 8132, 9, 2019/04/05, 19:53:19.447, 5166695128467, vstest.console.dll, TestLoggerManager.HandleDiscoveryComplete: Ignoring as the object is disposed.
TpTrace Verbose: 0 : 8132, 9, 2019/04/05, 19:53:19.447, 5166695128752, vstest.console.dll, DiscoveryRequest.DiscoveryComplete: Notified the discovery complete event.
TpTrace Information: 0 : 8132, 9, 2019/04/05, 19:53:19.447, 5166695129219, vstest.console.dll, DiscoveryRequest.DiscoveryComplete: Completed.
TpTrace Verbose: 0 : 8132, 1, 2019/04/05, 19:53:19.447, 5166695129216, vstest.console.dll, DiscoveryRequest.Dispose: Starting.
TpTrace Verbose: 0 : 8132, 9, 2019/04/05, 19:53:19.447, 5166695129499, vstest.console.dll, TestRequestSender.SetOperationComplete: Setting operation complete.
TpTrace Information: 0 : 8132, 1, 2019/04/05, 19:53:19.447, 5166695129968, vstest.console.dll, DiscoveryRequest.Dispose: Completed.
TpTrace Information: 0 : 8132, 9, 2019/04/05, 19:53:19.447, 5166695130185, vstest.console.dll, SocketServer.Stop: Stop server endPoint: 127.0.0.1:22222
TpTrace Information: 0 : 8132, 9, 2019/04/05, 19:53:19.447, 5166695130677, vstest.console.dll, SocketServer.Stop: Cancellation requested. Stopping message loop.
TpTrace Information: 0 : 8132, 1, 2019/04/05, 19:53:19.447, 5166695130478, vstest.console.dll, TestRequestManager.DiscoverTests: Discovery tests completed.
TpTrace Information: 0 : 8132, 9, 2019/04/05, 19:53:19.447, 5166695130955, vstest.console.dll, SocketServer.PrivateStop: Stopp server endPoint: 127.0.0.1:22222 error: 
TpTrace Verbose: 0 : 8132, 1, 2019/04/05, 19:53:19.448, 5166695132534, vstest.console.dll, Executor.Execute: Exiting with exit code of 0
```

**UPD3:** Interestingly, from this piece of logs: **TotalTests:109**. The real number of tests shown in visual studio is 113. The real number of tests finally in .trx file is 50. I randomly took the numbers for the question because I thoght it didn't matter. 100/50/60 is fake. Real numbers are **113**all/**48**passed/**50**in.trx/**2**failed.
```
TpTrace Verbose: 0 : 8132, 9, 2019/04/05, 19:53:19.394, 5166694945213, vstest.console.dll, DiscoveryRequest.DiscoveryComplete: Starting. Aborted:False, TotalTests:109
```

## Environment
As for dotnet.exe, it was the latest version couple of weeks ago.

**Comment by cheng93** [comment] 2019-04-05 22:07
Im getting something similar on my CI build.

Trx shows ~75 test out of 339. Console output shows all test being run

https://circleci.com/gh/cheng93/TripleTriad/29#tests/containers/0
trx https://gist.github.com/cheng93/d0749cac168a0ce92491a09c09b1fb3b
Just focusing on the `Requests` project

Funny enough, running the command locally works perfectly

**Comment by silentnightwalk** [comment] 2019-04-06 13:17
With TextTemplate help, I could generate code to run each test in its own `exec`.
Real numbers are **113**all/**48**passed/**50**in.trx/**2**failed. I randomly took the numbers for the question because I thoght it didn't matter. 100/50/60 is fake.

-------------------

The output of the run of all test execs are 101 deiag.txt files and 100 TestOutput.trx files.
I identified the one test, which missed its TestOutput.trx. In its diag file i found this error again:

```
TpTrace Error: 0 : ####, 9, 2019/04/06, 01:48:30.111, ###########, vstest.console.dll, LengthPrefixCommunicationChannel.Send: Error sending data: System.IO.IOException: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.BufferedStream.Flush()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.LengthPrefixCommunicationChannel.Send(String data).
TpTrace Warning: 0 : 8984, 9, 2019/04/06, 01:48:30.113, 5240987386427, vstest.console.dll, ProxyOperationManager: Failed to end session: Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.Interfaces.CommunicationException: Unable to send data over channel. ---> System.IO.IOException: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.BufferedStream.Flush()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.LengthPrefixCommunicationChannel.Send(String data)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.LengthPrefixCommunicationChannel.Send(String data)
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TestRequestSender.EndSession()
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.Close()
```

**Most probably, `vstest` stops and doesn't run remaining tests as soon as this error happens.**

-----------
I also found 4 tests with [TetsMethod] attribute wrapped in conditional compilation (These don't count):
````
# if DEBUG
[TestsMethod]
# endif
public void TestMethodName()
{
    ...
}
````
--------------

The other 8 tests, got lost for the following reason.
Tried to run them locally from visual studio, but getting something like following (translating by my own):

> Attention! TESTSETTINGS- or RUNSETTINGS- file, with ForcedLegacyMode set to True, is not supported by adapter MSTest version 2.

```
========== Discover test finished: 0 found (0:00:03,4738365) ==========
```

**Comment by silentnightwalk** [comment] 2019-04-08 16:02
Ok, the experiments with `.runsettings` (shown in UPD2 of my previous post) resulted in following:
 - 101 `diag.txt` files
 - 68 `.trx` files 

After that, i first returned back the `TargetFrameworkVersion`. Secondly, removed the `MSTest` section. In both cases, the outcome files are:
 - 101 ` diad.txt` files
 - **0 (zero)** `.trx` files

```
 Failed to launch testhost :System.AggregateException: One or more errors occurred. (The system cannot find the file specified) ---> System.ComponentModel.Win32Exception: The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.ProcessHelper.LaunchProcess(String processPath, String arguments, String workingDirectory, IDictionary`2 envVariables, Action`2 errorCallback, Action`1 exitCallBack)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DefaultTestHostManager.LaunchHost(TestProcessStartInfo testHostStartInfo, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DefaultTestHostManager.<>c__DisplayClass35_0.<LaunchTestHostAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DefaultTestHostManager.LaunchTestHostAsync(TestProcessStartInfo testHostStartInfo, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources)
---> (Inner Exception #0) System.ComponentModel.Win32Exception (2): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.ProcessHelper.LaunchProcess(String processPath, String arguments, String workingDirectory, IDictionary`2 envVariables, Action`2 errorCallback, Action`1 exitCallBack)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DefaultTestHostManager.LaunchHost(TestProcessStartInfo testHostStartInfo, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DefaultTestHostManager.<>c__DisplayClass35_0.<LaunchTestHostAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DefaultTestHostManager.LaunchTestHostAsync(TestProcessStartInfo testHostStartInfo, CancellationToken cancellationToken)
```

**Comment by mayankbansal018** [comment] 2019-04-09 07:42
@silentnightwalk The error in **1)** shows that communication b/w vstest.console, & testhost process broke, & yes you are correct, if this happens we do not run the tests after that.

For **2)** where `TestMethod` attribute was under `Debug` compilation option, we won't such tests in case of release. I tested this out locally. If possible can you please try this on a simple project, & share with us if you are finding it so.

Regarding **3)** Yes you are correct, the MsTest V2 adapters doesn't run test if "ForcedLegacyMode" is set to true.

Can you please tell me what is the issue are you facing currently, & please attach diagnostics file, & trx for the same.

**Comment by silentnightwalk** [comment] 2019-04-09 12:06
Thanks a lot for your answer!

I think it is more appropriate to ask about the issue i'm facing now in a new thread, as it looks to be a separate one.

----------

As for defining constants (2.)

The Property window of the testing project showed the "Define DEBUG const" was checked. However, Unchecking this (Define DEBUG constant) flag resulted in NO changes to the .csproj.
In other words, the DEBUG constant had not been defined before running tests. Even though, the property window of the testing project had showed  as if defined.   

The following is not very related to vstest, but still related to Microsoft:
Couple of misleading moments:
1) as said already, the flag is checked, however, no DEBUG constant defined
2) By default 
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
</Project>
```
means, that DEBUG constatnt is defined.
However, once i add my own constant like this
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <DefineConstants>MYCONST</DefineConstants>
  </PropertyGroup>
</Project>
``` 
makes the constant to be dropped down (disappear). Looks a bit unlogical when defining a constant could undo another constand. Like in my case, a developer might not have such intention relating to DEBUG when defining another constant. Probably, it is best to have such section in .csproj by default:
```
  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <DefineConstants>DEBUG</DefineConstants>
  </PropertyGroup>
```

**Comment by mayankbansal018** [comment] 2019-04-09 13:01
@silentnightwalk I cannot see your last comment here, but it seems you will open a separate issue for this. If that is so, should I go ahead & close this?

**Comment by silentnightwalk** [comment] 2019-04-09 14:22
@mayankbansal018, Thanks a lot for your reply.

It is now hard to figure out, whether, the error in **1)** always happens with one certain test, or this error randomly occurs on one test or another. Actually (Intuitively), it's always the same test, which breakes the connection, because it had been same count of tests previously (before breaking into many execs). As for now, you may close the issue.

Still haven't managed to figure out why `[TestMethod()]` attribute in DEBUG had been picked up.

**Comment by cheng93** [comment] 2019-04-09 17:03
@mayankbansal018 

Don't know if you have seen my comment.

Should I create a new issue for it?

**Comment by mayankbansal018** [comment] 2019-04-10 04:08
@cheng93 I just went through the links you shared, & the trx file shows all 329 tests,
[usertrx.txt](https://github.com/Microsoft/vstest/files/3061951/usertrx.txt)

Also in your CI system, I can see you ran test two times in step 6, & 7. In step 6 I can see 229 tests being ran, whereas in 7 329 tests ran, are you saying this is the difference you were not expecting? If yes, can you please provide some diagnostics logs for the same?

**Comment by cheng93** [comment] 2019-04-10 08:24
@mayankbansal018 

I was just focusing on step 7. The unit tests on `Requests`. Although the issue is also there in step 6.

You are right that the trx does show all the tests in the `Results` and `TestEntry` section, however in `TestDefinition` section, a lot is missing. 

Total lines of the file should be around ~1600

**Comment by cheng93** [comment] 2019-04-11 08:33
Diagnostic file https://gist.github.com/cheng93/cea3878115860b8e85f6b0883ac1203e

**Comment by mayankbansal018** [comment] 2019-04-12 09:31
@cheng93 is it possible for you to create a smaller repro of this issue, & share with us?

One thing I noticed, that the methods which were missing under `TestDefinition` section are data driven, however that is not true for all data driven tests.

A smaller repro would actually help us a lot in figuring this out.

**Comment by cheng93** [comment] 2019-04-12 09:40
Ive made a new issue, will try and get a smaller repro here.

I guess this issue can be closed

**Closed** 2019-04-12 09:49 UTC
Labels: bug, need-repro
