### ISSUE TITLE
MSB4018 Access Denied hitting Ctrl-C

### ISSUE THREAD

**Issue by danmosemsft** [Microsoft/vstest#1828] opened 2018-11-05 01:55 UTC
## Description
Hit Ctrl-C during dotnet test run, got unhandled exception

## Steps to reproduce
I had a test that hung. I was running with `"console;verbosity=detailed"`. After waiting for a bit, I hit Ctrl-C. This happens most times. I have no idea why it says access denied, either it should catch this and ignore it or catch this and log it nicely.

## Expected behavior
Regular error message not a callstack.

## Actual behavior
```
Passed   Microsoft.Collections.Extensions.Tests.MultiValueDictionaryTests.MVD_Constructor8
Attempting to cancel the build...
^C
C:\git\corefxlab>C:\Program Files\dotnet\sdk\3.0.100-alpha1-009697\Microsoft.TestPlatform.targets(33,5): error MSB4018: The "Microsoft.TestPlatform.Build.Tasks.VSTestTask" task failed unexpectedly. [C:\git\corefxlab\tests\Microsoft.Experimental.Collections.Tests\Microsoft.Experimental.Collections.Tests.csproj]
C:\Program Files\dotnet\sdk\3.0.100-alpha1-009697\Microsoft.TestPlatform.targets(33,5): error MSB4018: System.ComponentModel.Win32Exception (5): Access is denied. [C:\git\corefxlab\tests\Microsoft.Experimental.Collections.Tests\Microsoft.Experimental.Collections.Tests.csproj]
C:\Program Files\dotnet\sdk\3.0.100-alpha1-009697\Microsoft.TestPlatform.targets(33,5): error MSB4018:    at System.Diagnostics.Process.Kill() [C:\git\corefxlab\tests\Microsoft.Experimental.Collections.Tests\Microsoft.Experimental.Collections.Tests.csproj]
C:\Program Files\dotnet\sdk\3.0.100-alpha1-009697\Microsoft.TestPlatform.targets(33,5): error MSB4018:    at Microsoft.TestPlatform.Build.Tasks.VSTestForwardingApp.Cancel() [C:\git\corefxlab\tests\Microsoft.Experimental.Collections.Tests\Microsoft.Experimental.Collections.Tests.csproj]
C:\Program Files\dotnet\sdk\3.0.100-alpha1-009697\Microsoft.TestPlatform.targets(33,5): error MSB4018:    at Microsoft.TestPlatform.Build.Tasks.VSTestTask.Cancel() [C:\git\corefxlab\tests\Microsoft.Experimental.Collections.Tests\Microsoft.Experimental.Collections.Tests.csproj]
C:\Program Files\dotnet\sdk\3.0.100-alpha1-009697\Microsoft.TestPlatform.targets(33,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Cancel() [C:\git\corefxlab\tests\Microsoft.Experimental.Collections.Tests\Microsoft.Experimental.Collections.Tests.csproj]
```

## Environment
Windows 10
vstest.console.exe 3.0.100-alpha1-009697  

C:\git\corefxlab>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-alpha1-009697
 Commit:    7365786612

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-alpha1-009697\

Host (useful for support):
  Version: 3.0.0-preview1-27018-05
  Commit:  7a7ca06512

.NET Core SDKs installed:
  1.0.0 [C:\Program Files\dotnet\sdk]
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.0.0 [C:\Program Files\dotnet\sdk]
  2.0.2 [C:\Program Files\dotnet\sdk]
  2.0.3 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.300-preview2-008212 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  3.0.100-alpha1-009697 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-preview2-30106 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 3.0.0-alpha1-10062 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-preview2-30106 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-alpha1-10062 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.DesktopUI.App 3.0.0-alpha-27017-4 [C:\Program Files\dotnet\shared\Microsoft.DesktopUI.App]
  Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-preview2-26131-06 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3-servicing-26724-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview1-27018-05 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by danmosemsft** [comment] 2018-11-05 02:07
This note in Process.Kill doc may be relevant `If the call to the Kill method is made while the process is currently terminating, a Win32Exception is thrown for Access Denied.`

**Comment by karanjitsingh** [comment] 2018-11-06 07:38
@danmosemsft, I tried to repro with a test that's supposed to hang but I'm not able to reproduce this. Could you help me with a consistent repro?

**Comment by karanjitsingh** [comment] 2018-11-13 07:08
@danmosemsft is this still happening for you?

**Comment by danmosemsft** [comment] 2018-11-13 15:15
Yes but it may be a few days before I can try to form a repro.

**Comment by karanjitsingh** [comment] 2018-11-16 18:39
Hey @danmosemsft, I'm closing this issue for now due to lack of information, feel free to comeback with a repro and I will reopen it.

**Closed by karanjitsingh** 2018-11-16 18:39 UTC
Labels: bug, need-repro

**Comment by danmosemsft** [comment] 2018-11-16 19:03
Why not just add a catch for Win32Exception around Kill() inside VSTestForwardingApp.Cancel() ?

**Comment by karanjitsingh** [comment] 2018-11-20 07:44
@danmosemsft, I'll need to reproduce the issue at least once before I go forward with a fix. Is possible to share the test you're running that consistently reproduces this issue? If you can't share here, please share the repro with me internally.
