### ISSUE TITLE
vstest 16.4.0 vstest.console process failed to connect to testhost process after 90 seconds

### ISSUE THREAD

**Issue by Mobrockers** [microsoft/vstest#2253] opened 2019-11-15 16:29 UTC
## Description
Vstest console 16.4.0 started using translationlayer client cannot connect to testhost on macosx or ubuntu

## Steps to reproduce
https://github.com/stryker-mutator/stryker-net/pull/803
https://dev.azure.com/stryker-mutator/Stryker/_build/results?buildId=3194&view=logs&j=8dcd3b11-13fb-50f0-4b7f-731992d2cc40&t=cb30da9f-d093-5976-a5a7-fb4ed5357abf

## Expected behavior
test discovery succeeds and testrun is executed

## Actual behavior
test discovery is canceled and testruns fail

## Diagnostic logs
[vstest-log.txt](https://github.com/microsoft/vstest/files/3852325/vstest-log.txt)

## Environment
```
    <PackageReference Include="Microsoft.TestPlatform" Version="16.4.0" />
    <PackageReference Include="Microsoft.TestPlatform.ObjectModel" Version="16.4.0" />
    <PackageReference Include="Microsoft.TestPlatform.Portable" Version="16.4.0" />
    <PackageReference Include="Microsoft.TestPlatform.TranslationLayer" Version="16.4.0" />
```

vstest.console and testhost are extracted from Microsoft.TestPlatform.Portable and launched through Microsoft.TestPlatform.TranslationLayer. Issue occurs on azure devops hosted pipeline agents ubuntu-latest and macos-latest

See diagnostic logs attached for all trace logging. If neccesary any other required logging can easily be provided.

**Comment by singhsarab** [comment] 2019-12-23 16:20
@Mobrockers You are right. This seems to be a duplicate of the tagged issue. Closing this one.

**Closed by singhsarab** 2019-12-23 16:20 UTC
Labels: bug, duplicate
