### ISSUE TITLE
Failed to initialize client proxy

### ISSUE THREAD

**Issue by DanAtkinson** [Microsoft/vstest#594] opened 2017-03-10 13:28 UTC
## Description
When Visual Studio (2015) builds, I get an exception in the Output window.

    Failed to initialize client proxy: could not connect to test process vstest.discoveryengine.exe.

## Steps to reproduce
1. Build the solution.
2. Error appears.

## Expected behavior
I would expect Visual Studio to find the unit tests.

## Actual behavior
In the end, I installed ReSharper to find execute the unit tests. It captured the full exception and stack trace for me. I have posted this to http://pastebin.com/qg763efF.

## Environment
Microsoft Windows [Version 10.0.10586]
Microsoft (R) Test Execution Command Line Tool Version 14.0.25420.1

## Anything else
I have looked around for help on this for months now with no success. Visual Studio is running as an administrator. I've tried uninstalling and reinstalling it with no joy.

**Comment by Gregfruita** [comment] 2017-06-16 15:08
I have the same issue. Also with VS 2017. 
What I observed is the following: In the event-log, there is a system warning: 
 vstest.discoveryengine.x86.exe with Prozess-ID 13272 konnte sich mit dem  Zielnamen host/229.71.105.236 nicht lokal authentifizieren  .... the process is looking for a strange IP-address. Then, I realized, that the name of the host consist only of numbers. If i do a ping with the host name it pings aktually this strange IP-address.  So, maybe my solution will be to rename the host.

**Comment by Faizan2304** [comment] 2017-07-09 09:50
@Gregfruita @DanAtkinson  can you please share repro project with us?

**Comment by DanAtkinson** [comment] 2017-07-10 14:21
@Faizan2304 This occurs on every project I open that has unit tests. This also occurs in Visual Studio 2017.

**Comment by Gregfruita** [comment] 2017-07-25 14:51
For me, the solution was to rename the host. After renaming everything workes fine.

**Comment by singhsarab** [comment] 2017-11-30 09:52
@DanAtkinson
Apologies for delay. 
We would need some more information to diagnose this one like
- What is the VS version?
- OS information
- Lang/Culture information
- Repro project if possible
All this so that we can reproduce and fix.

With Visual Studio 2017 Update 5, we have moved to new TestPlatform, will it be possible for you to try out the latest build for your scenario ?

**Comment by DanAtkinson** [comment] 2017-11-30 09:56
@singhsarab Sure! My VS version is 15.4.5. My OS is Windows 10 v1511 and my culture is set to British English.

In terms of reproduction cases, every project (new or pre-existing) suffers the same problem. This is after multiple reinstalls of Visual Studio 2015 and 2017.

**Comment by singhsarab** [comment] 2017-11-30 10:33
Lets try fetch some more logs.
Debug->Options->Test->Logging : Set the LoggingLevel to Diagnostic
And then I'd like you to share the logs that you get in the Tests output window.

**Comment by DanAtkinson** [comment] 2017-11-30 10:45
Below is the output:


    [30/11/2017 10:37:55 Diagnostic] Firing BuildCompleted event...
    [30/11/2017 10:37:55 Diagnostic] Container Discoverer 'Microsoft.VisualStudio.TestWindow.Extensions.CPSTestContainerDiscoverer' has container changes
    [30/11/2017 10:37:55 Diagnostic] Firing BuildCompleted event...
    [30/11/2017 10:37:55 Diagnostic] Container Discoverer 'Microsoft.VisualStudio.TestWindow.VsAdapters.VsProjectOutputContainerDiscoverer' has container changes
    [30/11/2017 10:37:55 Diagnostic] VirtualReadOnlyTestDataStore.OperationStateChanged State=OperationSetFinished, operationInProgress=False
    [30/11/2017 10:37:55 Diagnostic] TestDiscoveryStats.OperationStateChanged State=OperationSetFinished, InProgress=False
    [30/11/2017 10:37:55 Diagnostic] test container discoverer executor://cpsprojectoutputtestcontainerdiscoverer/v2, discovered 0 containers
    [30/11/2017 10:37:55 Diagnostic] No containers found from 'Microsoft.VisualStudio.TestWindow.Extensions.CPSTestContainerDiscoverer' :
    [30/11/2017 10:37:55 Diagnostic] Container discoverer 'Microsoft.VisualStudio.TestWindow.Extensions.CPSTestContainerDiscoverer' has no containers
    [30/11/2017 10:37:57 Diagnostic] test container discoverer executor://vsprojectoutputcontainerdiscoverer/v1, discovered 23 containers
    [30/11/2017 10:37:57 Diagnostic] Containers from 'Microsoft.VisualStudio.TestWindow.VsAdapters.VsProjectOutputContainerDiscoverer' :
    [30/11/2017 10:37:57 Diagnostic] 	D:\Work\SVN\Ecom\Reynholm\WebApp.UnitTests\bin\Debug\WebApp.UnitTests.dll:executor://vsprojectoutputcontainerdiscoverer/v1
    [30/11/2017 10:37:57 Diagnostic] 	D:\Work\SVN\Ecom\Reynholm\WebApp\bin\WebApp.dll:executor://vsprojectoutputcontainerdiscoverer/v1
    [30/11/2017 10:37:57 Diagnostic] 	D:\Work\SVN\Ecom\Reynholm\Common.UnitTests\bin\Debug\Common.UnitTests.dll:executor://vsprojectoutputcontainerdiscoverer/v1
    [30/11/2017 10:37:57 Diagnostic] 	D:\Work\SVN\Ecom\Reynholm\Common\bin\Debug\Common.dll:executor://vsprojectoutputcontainerdiscoverer/v1
    [30/11/2017 10:37:57 Diagnostic] 	D:\Work\SVN\Ecom\Reynholm\ServiceBus.UnitTests\bin\Debug\ServiceBus.UnitTests.dll:executor://vsprojectoutputcontainerdiscoverer/v1
    [30/11/2017 10:37:57 Diagnostic] 	D:\Work\SVN\Ecom\Reynholm\ServiceBus\bin\Debug\ServiceBus.dll:executor://vsprojectoutputcontainerdiscoverer/v1
    [30/11/2017 10:37:57 Diagnostic] About to Enqueue operation 'DiscoverSelectedOperation', hashcode:44110795 
    [30/11/2017 10:37:57 Diagnostic] Enqueue operation 'DiscoverSelectedOperation', hashcode:44110795 
    [30/11/2017 10:37:57 Diagnostic] Operation left in the the queue: 1
    [30/11/2017 10:37:57 Diagnostic] 	'DiscoverSelectedOperation', hashcode:44110795
    [30/11/2017 10:37:57 Diagnostic] 
    
    [30/11/2017 10:37:57 Diagnostic] Processing Queue .....
    [30/11/2017 10:37:57 Diagnostic] Operation Dequeue : 'DiscoverSelectedOperation'
    [30/11/2017 10:37:57 Diagnostic] VirtualReadOnlyTestDataStore.OperationStateChanged State=OperationSetStarted, operationInProgress=False
    [30/11/2017 10:37:57 Diagnostic] TestDiscoveryStats.OperationStateChanged State=OperationSetStarted, InProgress=False
    [30/11/2017 10:37:59 Diagnostic] VirtualReadOnlyTestDataStore.OperationStateChanged State=ChangeDetectionStarting, operationInProgress=True
    [30/11/2017 10:37:59 Diagnostic] TestDiscoveryStats.OperationStateChanged State=ChangeDetectionStarting, InProgress=False
    [30/11/2017 10:37:59 Diagnostic] DiscoveryOperation<DiscoverSelectedOperation> FinishedChangedCotainers, changed container count is 23
    [30/11/2017 10:37:59 Diagnostic] VirtualReadOnlyTestDataStore.OperationStateChanged State=ChangeDetectionFinished, operationInProgress=False
    [30/11/2017 10:37:59 Diagnostic] TestDiscoveryStats.OperationStateChanged State=ChangeDetectionFinished, InProgress=False
    [30/11/2017 10:37:59 Diagnostic] Discovering the following containers :
    [30/11/2017 10:37:59 Diagnostic] 	D:\Work\SVN\Ecom\Reynholm\WebApp.UnitTests\bin\Debug\WebApp.UnitTests.dll
    [30/11/2017 10:37:59 Diagnostic] 	D:\Work\SVN\Ecom\Reynholm\WebApp\bin\WebApp.dll
    [30/11/2017 10:37:59 Diagnostic] 	D:\Work\SVN\Ecom\Reynholm\Common.UnitTests\bin\Debug\Common.UnitTests.dll
    [30/11/2017 10:37:59 Diagnostic] 	D:\Work\SVN\Ecom\Reynholm\Common\bin\Debug\Common.dll
    [30/11/2017 10:37:59 Diagnostic] 	D:\Work\SVN\Ecom\Reynholm\ServiceBus.UnitTests\bin\Debug\ServiceBus.UnitTests.dll
    [30/11/2017 10:37:59 Diagnostic] 	D:\Work\SVN\Ecom\Reynholm\ServiceBus\bin\Debug\ServiceBus.dll
    [30/11/2017 10:37:59 Diagnostic] VirtualReadOnlyTestDataStore.OperationStateChanged State=DiscoveryStarting, operationInProgress=False
    [30/11/2017 10:37:59 Diagnostic] TestDiscoveryStats.OperationStateChanged State=DiscoveryStarting, InProgress=True
    [30/11/2017 10:37:59 Informational] ------ Discover test started ------
    [30/11/2017 10:37:59 Diagnostic] ***    Discover TestCase using 'InMemoryUnitTestWriter' ***
    [30/11/2017 10:37:59 Diagnostic] RunSettings Content:
    <RunSettings>
      <RunConfiguration>
        <ResultsDirectory>D:\Work\SVN\Ecom\Reynholm\WebApp\TestResults</ResultsDirectory>
        <SolutionDirectory>D:\Work\SVN\Ecom\Reynholm\WebApp\</SolutionDirectory>
        <TargetPlatform>X86</TargetPlatform>
        <TargetFrameworkVersion>Framework40</TargetFrameworkVersion>
      </RunConfiguration>
    </RunSettings>
    [30/11/2017 10:37:59 Diagnostic] VirtualReadOnlyTestDataStore.OperationStateChanged State=DiscoveryStarted, operationInProgress=False
    [30/11/2017 10:37:59 Diagnostic] TestDiscoveryStats.OperationStateChanged State=DiscoveryStarted, InProgress=True
    [30/11/2017 10:37:59 Error] Failed to initialize client proxy: could not connect to test process vstest.discoveryengine.x86.exe.
    [30/11/2017 10:37:59 Informational] ========== Discover test finished: 0 found (0:00:00.5186759) ==========
    [30/11/2017 10:37:59 Diagnostic] 	Provider 'GroupByStateProvider' found 0 groups.
    [30/11/2017 10:37:59 Diagnostic] VirtualReadOnlyTestDataStore.OperationStateChanged State=DiscoveryFinished, operationInProgress=False
    [30/11/2017 10:37:59 Diagnostic] TestDiscoveryStats.OperationStateChanged State=DiscoveryFinished, InProgress=False
    [30/11/2017 10:38:00 Diagnostic] VirtualReadOnlyTestDataStore.OperationStateChanged State=OperationSetFinished, operationInProgress=False
    [30/11/2017 10:38:00 Diagnostic] TestDiscoveryStats.OperationStateChanged State=OperationSetFinished, InProgress=False

**Comment by cltshivash** [comment] 2017-12-19 15:34
@DanAtkinson We have moved to a new version of the test platform as part of Visual Studio 2017.5 update. Kindly let us know if you are still seeing this issue.

**Comment by DanAtkinson** [comment] 2017-12-19 15:38
@cltshivash When did this change occur? What version was it released in?

For the record, I'm currently running 15.5.2 and still see it.

**Comment by singhsarab** [comment] 2017-12-20 10:28
@DanAtkinson As Shiva mentioned, 15.5.0 onwards new Test platform handles the requests.
Prior to this, discovery request was handled by vstest.discoveryengine*exe but 15.5 onwards the requests are handled by vstest.console.exe (which then invokes testhost*exe to do the discovery)

Error that you are getting seems to be related to vstest.discoveryengine*exe which is unexpected.

**Comment by DanAtkinson** [comment] 2017-12-20 10:45
@singhsarab Are you referring to "2017.5" and implying that this is also 15.5.0? If so then I'm sorry but this is not the version numbering you use on the product. It would be helpful if you communicated using the correct version numbering to avoid any ambiguity.

I took this screengrab yesterday. I'm definitely on the latest version.

![image](https://user-images.githubusercontent.com/23440/34202857-f29c1a12-e570-11e7-9732-4c36b17b846e.png)

The last few lines of the message text reads as follows:

    [19/12/2017 15:38:21 Informational] ------ Discover test started ------
    [19/12/2017 15:38:21 Error] Failed to initialize client proxy: could not connect to test process vstest.discoveryengine.x86.exe.
    [19/12/2017 15:38:21 Informational] ========== Discover test finished: 0 found (0:00:00.1281499) ==========

**Comment by fragmer** [comment] 2017-12-30 00:27
I also started seeing this error recently in my UWP test project. I'm currently using VisualStudio 15.5.2, running on Win 10 Enterprise (x64 build 14393).

My UWP project is referencing MSTestFramework.Universal 15.5.0.0, Newtonsoft.Json 9.0.0.0, TestPlatform.Universal 15.5.0.0, Universal Windows 10.0.16299, and a couple of my projects.

"Test Explorer" does not show any tests. Building the test project prints "Failed to initialize client proxy: could not connect to test process" to Tests output. The diagnostic log is basically same as Dan's:

```
[12/29/2017 4:11:17 PM Informational] ------ Discover test started ------
[12/29/2017 4:11:17 PM Diagnostic] ***    Discover TestCase using 'InMemoryUnitTestWriter' ***
[12/29/2017 4:11:17 PM Diagnostic] RunSettings Content:
<RunSettings>
  <RunConfiguration>
    <ResultsDirectory>R:\mystuff\DotNet\API\src\TestResults</ResultsDirectory>
    <SolutionDirectory>R:\mystuff\DotNet\API\src\</SolutionDirectory>
    <TargetPlatform>X86</TargetPlatform>
    <TargetFrameworkVersion>Framework45</TargetFrameworkVersion>
  </RunConfiguration>
</RunSettings>
[12/29/2017 4:11:17 PM Diagnostic] Source Information Provider feature status: ON
[12/29/2017 4:11:17 PM Diagnostic] Time taken for fetching compilation for project: mystuff.myextras1.universal = 190 milliseconds.
[12/29/2017 4:11:17 PM Diagnostic] Time taken for fetching compilation for project: mystuff.myextras2.universal = 5 milliseconds.
[12/29/2017 4:11:18 PM Diagnostic] Source Information Provider feature status: ON
[12/29/2017 4:11:18 PM Diagnostic] Time taken for fetching compilation for project: mystuff.tests.universal = 39 milliseconds.
[12/29/2017 4:11:18 PM Diagnostic] Queuing a discovery request for R:\mystuff\output\winuwp_x86_debug\bin\MyStuff.Tests\MyStuff.Tests.Universal.build.appxrecipe
[12/29/2017 4:11:18 PM Diagnostic] VirtualReadOnlyTestDataStore.OperationStateChanged State=OperationSetFinished, operationInProgress=False
[12/29/2017 4:11:18 PM Diagnostic] TestDiscoveryStats.OperationStateChanged State=OperationSetFinished, InProgress=False
[12/29/2017 4:11:18 PM Error] Failed to initialize client proxy: could not connect to test process.
[12/29/2017 4:11:18 PM Informational] ========== Discover test finished: 0 found (0:00:00.385982) ==========
[12/29/2017 4:11:18 PM Diagnostic] VirtualReadOnlyTestDataStore.OperationStateChanged State=DiscoveryFinished, operationInProgress=False
[12/29/2017 4:11:18 PM Diagnostic] TestDiscoveryStats.OperationStateChanged State=DiscoveryFinished, InProgress=False
[12/29/2017 4:11:18 PM Diagnostic] 	Provider 'GroupByStateProvider' found 0 groups.
```

Is the fact that "TargetFrameworkVersion" set to "Framework45" relevant at all? I'm not sure where that comes from.

**Comment by singhsarab** [comment] 2018-01-11 09:18
@fragmer 
If I understand correctly, your UWP test project targets version 16299, and looking at the TestPlatform.Universal version, I am assuming your min target version is also 16299.
In 15.5, for such projects due to certain limitations actual launch UWP app is required for discovery as well, which wont happen if your OS is lower version.

For now, you can try setting the min target version to a lower version, lets say 14393.
Let us know if it works for you, please share your concerns.

In 15.6, we are trying to address the discovery part. 
Note, you will be able to discover the tests, but can only run the tests if OS version matches the requirement.

**Comment by mayankbansal018** [comment] 2018-01-17 11:14
@DanAtkinson , Apologies for getting late on this thread, can you run a few diagnostics for us.

- Please create a .netcore UT project, & run tests for it. If it succeeds then it would mean that you have the new Testplatform(Tpv2) on machine/VS successfully installed. The netcore UT projects only run Tpv2
- If above runs, can you please share the file at <VS_Install_Path>\Common7\IDE\Extensions\TestPlatform\testplatform.config. Basically the way we pick the testplatform v1 or v2 is based on this config file. If the values of  "feature.net35" or "feature.net40" is set to false in your config file, please change them to true. Restart VS & try again.

**Comment by DanAtkinson** [comment] 2018-01-17 12:25
Hi @mayankbansal018,

The output from the test window is as follows:


    [17/01/2018 12:21:34 Informational] PowerShellTestContainerDiscoverer Constructor Entering
    [17/01/2018 12:21:38 Informational] ------ Load Playlist started ------
    [17/01/2018 12:21:38 Informational] ========== Load Playlist finished (0:00:00.029014) ==========
    [17/01/2018 12:21:42 Informational] PowerShellTestContainerDiscoverer:OnTestContainersChanged - FindPs1Files
    [17/01/2018 12:21:42 Informational] PowerShellTestContainerDiscoverer:IsTestFile - >7
    [17/01/2018 12:21:42 Informational] PowerShellTestContainerDiscoverer:IsTestFile - nuget
    [17/01/2018 12:21:42 Informational] PowerShellTestContainerDiscoverer:IsTestFile - d:\users\dan.atkinson\documents\visual studio 2017\projects\unittestproject1\unittestproject1\netcoreapp2.0\nugetdependency\.netcoreapp,version=v2.0\microsoft.net.test.sdk\15.5.0
    [17/01/2018 12:21:42 Informational] PowerShellTestContainerDiscoverer:IsTestFile - d:\users\dan.atkinson\documents\visual studio 2017\projects\unittestproject1\unittestproject1\netcoreapp2.0\nugetdependency\.netcoreapp,version=v2.0\mstest.testadapter\1.2.0
    [17/01/2018 12:21:42 Informational] PowerShellTestContainerDiscoverer:IsTestFile - d:\users\dan.atkinson\documents\visual studio 2017\projects\unittestproject1\unittestproject1\netcoreapp2.0\nugetdependency\.netcoreapp,version=v2.0\mstest.testframework\1.2.0
    [17/01/2018 12:21:42 Informational] PowerShellTestContainerDiscoverer:IsTestFile - sdk
    [17/01/2018 12:21:42 Informational] PowerShellTestContainerDiscoverer:IsTestFile - d:\users\dan.atkinson\documents\visual studio 2017\projects\unittestproject1\unittestproject1\netcoreapp2.0\sdkdependency\microsoft.netcore.app
    [17/01/2018 12:21:42 Informational] PowerShellTestContainerDiscoverer:IsTestFile - d:\users\dan.atkinson\documents\visual studio 2017\projects\unittestproject1\unittestproject1\unittest1.vb
    [17/01/2018 12:21:42 Informational] PowerShellTestContainerDiscoverer:OnTestContainersChanged - FindPs1Files
    [17/01/2018 12:22:09 Informational] ------ Discover test started ------
    [17/01/2018 12:22:36 Error] Failed to initialize client proxy: could not connect to test process vstest.discoveryengine.x86.exe.
    [17/01/2018 12:22:36 Informational] ========== Discover test finished: 0 found (0:00:27.3037376) ==========

The contents of my `testplatform.config` file are as follows:

    <?xml version="1.0" encoding="utf-8"?>
    
    <configuration>
      <appSettings>
        
        <add key="feature.net35" value="true" />
        
        <add key="feature.net40" value="true" />
        
        <add key="feature.datacollector" value="true"/>
      </appSettings>
    </configuration>
    
For reference, the version of VS2017 I'm running is 15.5.4 (updated just over an hour ago).

**Comment by mayankbansal018** [comment] 2018-01-17 13:00
@DanAtkinson, the above experiment tells us that somehow Tpv2 is not picked up by your VS, to eliminate that it is a machine specific issue, can you please try this on a colleague's machines, or better yet on a clean VM.
Meanwhile I'm digging in code see what additional logs we can enable for VS IDE to figure out why Tpv2 is not picked up.

**Comment by DanAtkinson** [comment] 2018-01-17 14:05
@mayankbansal018 Thanks. I'm going to create one based on the image provided by Microsoft [here](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines). Once installed, I'll update VS2017 to latest and re-test but I assume that it'll work. I'll update this issue once I've finished testing.

**Comment by mayankbansal018** [comment] 2018-02-05 10:27
@DanAtkinson  , As I mentioned previously, that the issue is because the Tpv2 is not picked up on your machine. I hope it would have worked in your above experiment.

I'm closing this issue for now, please re-open it if you are still facing it

**Closed by mayankbansal018** 2018-02-05 10:27 UTC
Labels: bug

**Comment by DanAtkinson** [comment] 2018-05-10 09:58
Hi. Just to let you know that, despite the problem continuing to occur, the recent update to 15.7.0 resolved the issue completely.

**If anyone else has encountered this problem please ensure you have the latest version (15.7+) of Visual Studio 2017 installed.**

**Comment by mayankbansal018** [comment] 2018-05-10 10:10
@DanAtkinson , thanks for sharing this, & good to know that 15.7 update resolved the issue for you.

**Comment by PokGirard** [comment] 2018-06-23 13:49
I have exactly the same issue, my version is 15.7.4. That's weird

**Comment by borrrden** [comment] 2018-06-23 14:46
Sometimes I still get this but the reason is unrelated. One thing to try out is uninstalling the unit test runner via the windows add and remove programs (the UWP settings one, not the traditional one).

**Comment by PokGirard** [comment] 2018-06-23 17:53
I uninstalled the 2017 version and installed the 2015 one. It took a little while but now everything works fine.

**Comment by kotprav** [comment] 2018-11-29 13:13
Reproduce the issue in 15.9 VS version.

**Comment by DanAtkinson** [comment] 2018-11-29 14:07
In the intervening months since my  [last update](https://github.com/Microsoft/vstest/issues/594#issuecomment-388009608), I have had a new machine built. On this machine, this is no longer a problem for me on 15.9.2. I haven't updated to 15.9.3 yet as I'm in the middle of something and it only appears to have been released in the last couple of days.

@kotprav, if you are indeed seeing this issue please can you update with as much information about your machine, the exact version number of VS, and follow the steps

Thanks, Dan

**Comment by kotprav** [comment] 2018-11-29 15:34
Hi @DanAtkinson ,

I use VS 15.9.3.
