### ISSUE TITLE
.Net Core project fail to run .Net Framework VSTests using TranslationLayer

### ISSUE THREAD

**Issue by SharonTancy** [microsoft/vstest#3582] opened 2022-04-19 07:18 UTC
## Description
> I created a .Net Core project to run vstests with VsTestConsole.TranslationLayer, it can successfully run .Net Core vstests but fails to execute .Net Framework ones, it fails directly at discovering tests. But when I switch the project target framework to .Net Framework, it can run both kind of tests successfully.  There might exist gaps between .Net Core projects to run all kinds of test dlls.

## Steps to reproduce
> Create a .Net Core project to call VsTestConsole.TranslationLayer to run tests.
> Run a .Net Framework test dll.

## Expected behavior
> Successfully run .Net Framework test dlls.

## Actual behavior
> Fail to discover .Net Framework test dlls.

## Diagnostic logs
> Show error message like this: `The active Tests Discovery was aborted.`

> When I check it in debug mode, it shows exception: 
`Exception thrown: 'Microsoft.TestPlatform.VsTestConsole.TranslationLayer.TransationLayerException' in Microsoft.TestPlatform.VsTestConsole.TranslationLayer.dll
Exception thrown: 'Microsoft.TestPlatform.VsTestConsole.TranslationLayer.TransationLayerException' in System.Private.CoreLib.dll`

## Environment
> Windows10+Microsoft.TestPlatform.Portable v16.10.0.
Microsoft.TestPlatform v16.10.0 shows the same behavior.

**Comment by nohwnd** [comment] 2022-04-19 14:09
Are you doing this in some public repository where I can see what exactly you are doing please?

**Comment by SharonTancy** [comment] 2022-04-20 06:14
Hi, I guess I found the root cause. I developed this for an internal functional test tool to run vstest dlls. While the `TestAdapter` under netcore lib dir is not compatible to discover or run .Net Framework test dlls. If we want to run both .Net Core and .Net Framework dlls from a .Net Core project I guess we should be careful with the `TestAdapter` version.

**Comment by nohwnd** [comment] 2022-04-20 09:11
The problem is probably a bit deeper even, vstest.console does not support combinations of target frameworks in a single run yet. This has been a long standing limitation.

**Comment by nohwnd** [comment] 2022-04-20 09:11
Closing because OP found their root cause.

**Closed** 2022-04-20 09:11 UTC
