### ISSUE TITLE
Vstest.console.exe incorrectly throws exception with try/catch block

### ISSUE THREAD

**Issue by NateB2** [Microsoft/vstest#1471] opened 2018-03-12 21:15 UTC
## Description
When running tests, the vstest.console.exe process throws exceptions, even when the "catch" block doesn't contain a "throw" command.  This worked fine until the 15.6 release.  Once we migrated to 15.6, it started throwing this error.  We then rolled back to 15.5 to verify, and sure enough, the error was not thrown.

Example code that throws an exception.  This code is executed during a dispose call in an implementation of an IDisposable class, and is responsible for cleaning up LocalDB files that are used during the test run.  If the files can't be deleted for whatever reason, we still want the test run to finish successfully.

```
private void DeleteDatabase()
        {
            SqlConnection.ClearAllPools();
            try
            {
                Database.Delete(_connectionString);
            }
            catch (Exception e)
            {
                Console.WriteLine("Failed to delete database with connection string [{0}]", _connectionString);
                Console.WriteLine("Error: " + e.Message + "\n" + e.InnerException?.Message + "\n" + e.StackTrace);
                //vstest.console.exe throws an error here
            }
        }
```

## Steps to reproduce
Start a test run that contains code that catches an error but does not throw.  I don't know if this is specific to code that is inside a Dispose() call or if it can be reproduced more generally.

## Expected behavior
The test run continues and finishes successfully

## Actual behavior
The test run doesn't run any more unit tests in that particular assembly and subsequently fails.

## Diagnostic logs
There are seemingly no applicable logs around the failure event - it just throws the error as if there was a "throw" statement inside the catch block. 

## Environment
Windows Server 2016, vstest.console.exe version 15.6, using the VSTS VSTest task on a custom Azure VM  with VS 2017 15.6 installed and the VSTS agent version 2.129.1 installed.

**Comment by singhsarab** [comment] 2018-03-13 09:17
@NateB2 The actually run of the tests is done by the adapter, so possibly adapter is doing something special here.
What is the test framework you are using?
Can you share the /diag logs for vstest.console ?
Also if you could share the output of vstest.console, I am just trying to see the stack trace to confirm your hypothesis.

**Comment by NateB2** [comment] 2018-03-13 18:42
We're using xunit 2.3.1.  It worked with the same version of xunit with 15.5 - the errors started cropping up with 15.6. Here is the Vsts output - I'll have to see if I can recreate the error with the diagnostic logs enabled - switching to a faster VM type and making some tweaks to how the LocalDB databases are created seems to have mostly alleviated the issue by minimizing the number of times the catch block is called.

```
2018-03-08T00:01:56.6104439Z Failed to delete database with connection string [Data Source=(LocalDb)\MSSQLLocalDB;Initial Catalog=939ed0c7-80f8-4a63-a717-e3ea62f41b83;Integrated Security=True;AttachDbFileName=D:\******\1\a\TestingArtifacts\UnitTests\Server\939ed0c7-80f8-4a63-a717-e3ea62f41b83.mdf]
2018-03-08T00:01:56.6117413Z Error: Cannot drop database "939ed0c7-80f8-4a63-a717-e3ea62f41b83" because it is currently in use.
2018-03-08T00:01:56.6117776Z 
2018-03-08T00:01:56.6117961Z    at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
2018-03-08T00:01:56.6118236Z    at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
2018-03-08T00:01:56.6118535Z    at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
2018-03-08T00:01:56.6118933Z    at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
2018-03-08T00:01:56.6119833Z    at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
2018-03-08T00:01:56.6120113Z    at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
2018-03-08T00:01:56.6120382Z    at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
2018-03-08T00:01:56.6120727Z    at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.NonQuery(DbCommand command, DbCommandInterceptionContext interceptionContext)
2018-03-08T00:01:56.6121452Z    at System.Data.Entity.SqlServer.SqlProviderServices.<>c__DisplayClass30.<DropDatabase>b__2e(DbConnection conn)
2018-03-08T00:01:56.6123239Z    at System.Data.Entity.SqlServer.SqlProviderServices.<>c__DisplayClass33.<UsingConnection>b__32()
2018-03-08T00:01:56.6123505Z    at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.<>c__DisplayClass1.<Execute>b__0()
2018-03-08T00:01:56.6125023Z    at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
2018-03-08T00:01:56.6125401Z    at System.Data.Entity.SqlServer.SqlProviderServices.UsingMasterConnection(DbConnection sqlConnection, Action`1 act)
2018-03-08T00:01:56.6125664Z    at System.Data.Entity.SqlServer.SqlProviderServices.DropDatabase(SqlConnection sqlConnection, Nullable`1 commandTimeout, String databaseName)
2018-03-08T00:01:56.6126524Z    at System.Data.Entity.SqlServer.SqlProviderServices.DbDeleteDatabase(DbConnection connection, Nullable`1 commandTimeout, StoreItemCollection storeItemCollection)
2018-03-08T00:01:56.6126979Z    at System.Data.Entity.Database.Delete(String nameOrConnectionString)
2018-03-08T00:01:56.6127233Z    at Ipseity.Server.UnitTests.Common.TestRepositories.RepositoryFactoryForTestBase`2.DeleteDatabase()
2018-03-08T00:02:01.6412862Z ##[warning]Vstest failed with error. Check logs for failures. There might be failed tests.
2018-03-08T00:02:01.7818575Z ##[error]Error: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe failed with return code: 1
2018-03-08T00:02:02.9598493Z ##[error]VsTest task failed.
```

**Comment by NateB2** [comment] 2018-03-15 08:26
Here's the last entries in the associated diagnostic log.  Looks like it might be a socket connection issue.
```
TpTrace Information: 0 : 9408, 16, 2018/03/15, 07:40:12.014, 67094605965, testhost.x86.exe, Sending test run statistics
TpTrace Verbose: 0 : 9408, 16, 2018/03/15, 07:40:12.015, 67094613664, testhost.x86.exe, TestRunCache: OnNewTestResult: Notified the onCacheHit callback.
TpTrace Warning: 0 : 9408, 16, 2018/03/15, 07:40:12.017, 67094631908, testhost.x86.exe, InProgressTests is null
TpTrace Warning: 0 : 9408, 16, 2018/03/15, 07:40:12.017, 67094633103, testhost.x86.exe, TestRunCache: No test found corresponding to testResult 'Ipseity.Server.MessageProcessing.CommandHandlers.IdentityPrograms.ConfirmDeleteIdentityProgramCommandHandlerTests.ConfirmDeleteIdentityProgramCommandHandler_Ctor_NullMessageSubmitterFactoryThrows  Passed' in inProgress list.
TpTrace Warning: 0 : 9408, 16, 2018/03/15, 07:40:12.018, 67094639230, testhost.x86.exe, InProgressTests is null
TpTrace Warning: 0 : 9408, 16, 2018/03/15, 07:40:12.024, 67094701598, testhost.x86.exe, InProgressTests is null
TpTrace Warning: 0 : 9408, 16, 2018/03/15, 07:40:12.952, 67103988639, testhost.x86.exe, TestRunCache: No test found corresponding to testResult 'Ipseity.Server.MessageProcessing.EventHandlers.IdentityProgramRepositoryProjectionsApplicationsTests.IdentityProgramRepositoryProjections_FbiDORegistrationCreatedEvent_Success  Passed' in inProgress list.
TpTrace Information: 0 : 9408, 20, 2018/03/15, 07:40:13.021, 67104675154, testhost.x86.exe, DefaultEngineInvoker: ParentProcess '5908' Exited.
TpTrace Error: 0 : 9408, 8, 2018/03/15, 07:40:13.097, 67105438152, testhost.x86.exe, Socket: Message loop: failed to receive message due to socket error System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.Stream.ReadByte()
   at System.IO.BinaryReader.ReadByte()
   at System.IO.BinaryReader.Read7BitEncodedInt()
   at System.IO.BinaryReader.ReadString()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.LengthPrefixCommunicationChannel.NotifyDataAvailable()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TcpClientExtensions.MessageLoopAsync(TcpClient client, ICommunicationChannel channel, Action`1 errorHandler, CancellationToken cancellationToken)
```

**Comment by singhsarab** [comment] 2018-03-15 08:38
Interesting. Are these logs from the same run ?

**Comment by NateB2** [comment] 2018-03-15 09:10
Different runs, but same type of error in the VSTS console logs and in the diagnostic log.  For completeness sake, here's the corresponding error in the VSTS console log.  Note the log entry timecodes:
```
2018-03-15T07:40:09.3477828Z Test execution time: 8.7362 Minutes
2018-03-15T07:40:12.9563271Z Results File: D:\SidBuildAgent1_Test_1_work\1\s\TestResults\SidDevOps_SidBuildAgent1_2018-03-15_07_31_48.trx
2018-03-15T07:40:33.4420866Z Failed to delete database with connection string [Data Source=(LocalDb)\MSSQLLocalDB1;Initial Catalog=1_3dfad876-c104-4c93-aae0-6e2d90399ec6;Integrated Security=True;AttachDbFileName=D:\SidBuildAgent1_Test_1_work\1\a\TestingArtifacts\UnitTests\Server\1_3dfad876-c104-4c93-aae0-6e2d90399ec6.mdf]
2018-03-15T07:40:33.4431387Z Error: Cannot drop database "1_3dfad876-c104-4c93-aae0-6e2d90399ec6" because it is currently in use.
2018-03-15T07:40:33.4433148Z 
2018-03-15T07:40:33.4433442Z    at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
2018-03-15T07:40:33.4433667Z    at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
2018-03-15T07:40:33.4433958Z    at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
2018-03-15T07:40:33.4434226Z    at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
2018-03-15T07:40:33.4434649Z    at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
2018-03-15T07:40:33.4434882Z    at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
2018-03-15T07:40:33.4435050Z    at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
2018-03-15T07:40:33.4435228Z    at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.<NonQuery>b__0(DbCommand t, DbCommandInterceptionContext`1 c)
2018-03-15T07:40:33.4435425Z    at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
2018-03-15T07:40:33.4435640Z    at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.NonQuery(DbCommand command, DbCommandInterceptionContext interceptionContext)
2018-03-15T07:40:33.4436089Z    at System.Data.Entity.SqlServer.SqlProviderServices.<>c__DisplayClass30.<DropDatabase>b__2e(DbConnection conn)
2018-03-15T07:40:33.4438289Z    at System.Data.Entity.SqlServer.SqlProviderServices.<>c__DisplayClass33.<UsingConnection>b__32()
2018-03-15T07:40:33.4438542Z    at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.<>c__DisplayClass1.<Execute>b__0()
2018-03-15T07:40:33.4438783Z    at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
2018-03-15T07:40:33.4439054Z    at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute(Action operation)
2018-03-15T07:40:33.4439232Z    at System.Data.Entity.SqlServer.SqlProviderServices.UsingConnection(DbConnection sqlConnection, Action`1 act)
2018-03-15T07:40:33.4439402Z    at System.Data.Entity.SqlServer.SqlProviderServices.UsingMasterConnection(DbConnection sqlConnection, Action`1 act)
2018-03-15T07:40:33.4439585Z    at System.Data.Entity.SqlServer.SqlProviderServices.DropDatabase(SqlConnection sqlConnection, Nullable`1 commandTimeout, String databaseName)
2018-03-15T07:40:33.4440864Z    at System.Data.Entity.SqlServer.SqlProviderServices.DbDeleteDatabase(DbConnection connection, Nullable`1 commandTimeout, StoreItemCollection storeItemCollection)
2018-03-15T07:40:33.4441117Z    at System.Data.Entity.Core.Common.DbProviderServices.DeleteDatabase(DbConnection connection, Nullable`1 commandTimeout, StoreItemCollection storeItemCollection)
2018-03-15T07:40:33.4441479Z    at System.Data.Entity.Core.Objects.ObjectContext.DeleteDatabase()
2018-03-15T07:40:33.4441651Z    at System.Data.Entity.Internal.DatabaseOperations.Delete(ObjectContext objectContext)
2018-03-15T07:40:33.4441835Z    at System.Data.Entity.Database.Delete(String nameOrConnectionString)
2018-03-15T07:40:33.4442028Z    at Ipseity.Server.UnitTests.Common.TestRepositories.RepositoryFactoryForTestBase`2.DeleteDatabase()
```

**Comment by cltshivash** [comment] 2018-03-16 04:53
@NateB2 The socket issue is tracked #1472 . The other failure is adapter specific. Can we get a sample repro for this ?

**Comment by NateB2** [comment] 2018-03-16 18:56
Creating a sample repro would be tricky because it doesn't happen 100% of the time anyway, and the code that's executed during the problematic test run contains a significant amount of information we wouldn't want to share, so I'd need to see about creating a repro virtually from scratch.  Since it appears it might be linked to the socket issue, I'm more than happy to wait to see if the fix for the socket issue also fixes this problem.  If it does not, I'll see about creating a sample repro.

**Comment by kaadhina** [comment] 2018-03-22 06:42
@NateB2 Do you have any datacollector such as codecoverage turned on? If so, can you try turning it off and retry?

**Comment by kaadhina** [comment] 2018-03-22 06:50
@NateB2 Also, do you have "run in parallel" selected, or have a runsettings with maxcpucount tag to run in parallel? If so, can you try turning that off as well while retying?

**Comment by NateB2** [comment] 2018-03-22 23:04
@kaadhina - yes, I was running the tests with code coverage in parallel.  It tended to happen more frequently when there was more concurrency.  If I have some time, I will try turning it off and running it again.  Once I was able to devote enough compute resources to the unit tests, I haven't received this particular error.

**Comment by cltshivash** [comment] 2018-04-01 03:16
@NateB2 Though there are two errors, the cause for the failure is #1472. if you are using VSTS you can use the Test Tools Installer task to get the fix. VS 15.6.5 update will also have the fix.

**Comment by kaadhina** [comment] 2018-04-05 09:56
Closing this since #1472 is tracked

**Closed by kaadhina** 2018-04-05 09:56 UTC
Labels: question
