### ISSUE TITLE
Error Connecting to VSTest Console

### ISSUE THREAD

**Issue by anshii03** [microsoft/vstest#2220] opened 2019-10-10 10:32 UTC
In AzDevops, while using the VSTest task to run the tests, the tests run seems to fail indicating connection timeout while trying to establish a connection with vstest.console on slower machines sometimes with the following error.

```  process failed to connect to vstest.console process after 90 seconds. This may occur due to machine slowness, please set environment variable VSTEST_CONNECTION_TIMEOUT to increase timeout. ```

**Comment by mayankbansal018** [comment] 2019-10-14 09:42
@Anshi92 can you please provide diagnostics information via https://github.com/Microsoft/vstest-docs/blob/master/docs/diagnose.md

Also can you please elaborate on your scenario a bit more

**Comment by singhsarab** [comment] 2019-12-10 15:21
Root cause for this issue seems to be static initialization of the extensions in the vstest.console which takes long and supposedly happens before it tries to connect back to the client (translation layer).

**Comment by nohwnd** [comment] 2019-12-16 13:04
@singhsarab What led you to think that the initialization is the problem? I am executing test console in a very slowed down process and still can't see it take anywhere near 90 seconds. 

Notice that on the slowed down process it takes 13 seconds just to start the host process, that is how slow it is. So I don't think there is any significant initialization that could be the cause. The "host starts" message is printed as the first thing in the `Main` method in `testhost`, and I could not find any static constructors, so it should be very close to the actual start of the process.

```
Normal process, on all cores with Normal CPU and IO priority <1s: 
01.25.49.978846 - starting host from console
01.25.50.018920 - await connection with timeout 90000ms
01.25.50.333706 - host starts
01.25.50.414794 - host initialized
01.25.50.494788 - connected to console
01.25.50.509815 - connection success in awaiter

Process running on single core with Idle CPU and I/O priority, 
and hammering the core with multiple other processes <60s: 
01.39.57.429337 - starting host from console
01.39.58.736948 - await connection with timeout 90000ms
01.40.10.217853 - host starts
01.40.20.279653 - host initialized
01.40.25.008786 - connected to console
01.40.25.205894 - connection success in awaiter
```

@anshii03 Are you still able to replicate this problem? Could you provide the diagnostic log please?  https://github.com/Microsoft/vstest-docs/blob/master/docs/diagnose.md

**Comment by nohwnd** [comment] 2020-01-06 16:05
I did some more testing on this, this time on invoking the `vstest.console` from the console wrapper, to see if the initialization is the culprit there. And it was not either. The longest time was spent setting up the connection and processing the first request. So it seems that the computer is simply too slow / busy to finish the connection within the timeout. 

As discussed, moving the connection before initialization would be a one way to approach this, but due to the internal architecture where everything is invoked as an abstraction of parameter processor, it would require either a hacky solution, or bigger changes in the approach to do the connection sooner.

**Comment by ManishJayaswal** [comment] 2020-02-10 06:57
@nohwnd - should we try adding some runsettings parameters using which users can indicate retries ( if they hit this often) since it seems like it is slow/busy  machine issue?

**Comment by Evangelink** [comment] 2022-07-25 14:15
Ping @anshii03

**Comment by Evangelink** [comment] 2022-08-03 07:55
I am closing this issue, if you are still having issues, please let us know.

**Closed by Evangelink** 2022-08-03 07:55 UTC
Labels: need-additional-info
