### ISSUE TITLE
Unable to run/debug XUnit tests targeting Desktop from Visual Studio on latest Windows 10 machine

### ISSUE THREAD

**Issue by jeremymeng** [Microsoft/vstest#811] opened 2017-05-15 21:24 UTC
## Description

After the Windows 10 Creators update, I can no longer run or debug xunit tests
targeting Desktop .NET Framework in Visual Studio.

## Steps to reproduce

1. On a machine with .NET 4.7 and VS 2017 15.2. I think .NET 4.7 comes with
   Windows Creators update. After I installed .NET 4.7 on another machine that had .NET 4.6, I
   don't see `System.Runtime, Version=4.1.0.0` in GAC. The version
   4.0.0.0 is in GAC.

2. Create an xunit test project with `dotnet new xunit`.

3. In the generated .csproj file, change the target framework to `net46`. Also change the package reference versions.

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net46</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
    <PackageReference Include="xunit" Version="2.2.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.2.0" />
  </ItemGroup>

</Project>
```

4. Open the project in Visual Studio, rebuild the project, then look at the Test output pane

**Expected**:

No warnings or errors

**Actual**:

there's a warning

```
[xUnit.net 00:00:00.0226725] Skipping: test4 (could not find dependent assembly 'Microsoft.Extensions.DependencyModel, Version=1.1.0')
```

5. Right click the test in Test Explorer then select Run Selected Tests

**Expected**:

Test runs and passes.

**Actual**:

```
------ Run test started ------
[xUnit.net 00:00:00.0296561] test4: Catastrophic failure: System.TypeInitializationException: The type initializer for 'Xunit.DiaSession' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Reflection.TypeExtensions, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at Xunit.DiaSession..cctor()
   --- End of inner exception stack trace ---
   at Xunit.DiaSession..ctor(String assemblyFileName)
   at Xunit.DiaSessionWrapper..ctor(String assemblyFilename)
   at Xunit.XunitFrontController..ctor(AppDomainSupport appDomainSupport, String assemblyFileName, String configFileName, Boolean shadowCopy, String shadowCopyFolder, ISourceInformationProvider sourceInformationProvider, IMessageSink diagnosticMessageSink)
   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.RunTestsInAssembly(IRunContext runContext, IFrameworkHandle frameworkHandle, LoggerHelper logger, IMessageSinkWithTypes reporterMessageHandler, AssemblyRunInfo runInfo)
========== Run test finished: 0 run (0:00:00.427418) ==========
```

## Environment

Operating system: Windows 10: a Microsoft internal selfhost version)

vstest.executionengine.x86.exe:	15.00.26228.0

## My findings

- I am using the SDK-style .csproj to target net46. According to the doc,
  [Desktop, UWP & Native unit testing continues to use the test platform (TPv1) located @ "%programfiles(x86)%\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow".](https://github.com/Microsoft/vstest-docs/blob/master/docs/contribute.md#building-with-visual-studio).
  (I have briefly tried the method of putting a `testplatform.config` mentioned
  at the same link but it didn't work for me.)

- I have .NET 4.7 on my repro machine. I suspect that 
  `System.Runtime, Version=4.1.0.0` is in the GAC for latest windows builds.

- When discovering/executing unit tests, VS tries to get additional test
  extensions from both xunit assemblies in the following order
    
    - `%TEMP%\VisualStudioTestExplorerExtensions\2.2.0\build\netcoreapp1.0\xunit.runner.visualstudio.dotnetcore.testadapter.dll`    
    - `%Temp%\VisualStudioTestExplorerExtensions\2.2.0\build\_common\xunit.runner.visualstudio.testadapter.dll`
    
- Because of the GAC version of `System.Runtime.dll, Version=4.1.0.0`, xunit
  test extension from the first assembly (.NET Core version) is successfully
  added.

- The test extension from the second assembly (Desktop version) is also added.

- Now VS test platform has two test adapters for `executor://xunit/VsTestRunner2`

- When I rebuild the solution, the VS Test discovery engine uses the first one
  (.NET Core version) and failed to load its dependency
  `Microsoft.Extensions.DependencyModel, Version=1.1.0.0` because my test is
  targeting net46.
  **Note**, I am not clear why this dependency didn't cause problem when VS tries to
  get types via reflection from assembly
  `xunit.runner.visualstudio.dotnetcore.testadapter.dll`.
  It seems still able to find the test (using the second xunit test adapter?)
  
```
------ Discover test started ------
[xUnit.net 00:00:00.0042451] Skipping: test4 (could not find dependent assembly 'Microsoft.Extensions.DependencyModel, Version=1.1.0')
[xUnit.net 00:00:00.2620017]   Discovering: test4
[xUnit.net 00:00:00.3980642]   Discovered:  test4
========== Discover test finished: 1 found (0:00:00.6219404) ==========
```

- When I run a test from VS Test Explorer, it failed.

- On my non-reproing machine that have .NET 4.6. VS also tries to get test
  extensions from the same two xunit assemblies. But getting types via
  reflection fails for the .NET Core version because of the missing dependency
  on `System.Runtime, Version=4.1.0.0`. The `ReflectionTypeLoadException` is
  handled. Thus only the Desktop version of xunit test adapter is added to the
  list of test discoverers.

**Comment by jeremymeng** [comment] 2017-05-15 22:11
> I have briefly tried the method of putting a testplatform.config mentioned
> at the same link but it didn't work for me

I  can see that tpv2 is enabled, and `vstest.console.exe` is started. But at the same time, `vstest.discoveryengine.x86.exe` is also started
```
"C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\ENTERPRISE\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\TESTWINDOW\vstest.discoveryengine.x86.exe" /parentProcessId 17480                                                                                                                                                                                                                                                                                                                  
"C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\ENTERPRISE\COMMON7\IDE\EXTENSIONS\TESTPLATFORM\vstest.console.exe" /parentprocessid:17480 /port:60551   
```
Is there any other workarounds?

**Comment by codito** [comment] 2017-05-16 03:00
@jeremymeng thanks for detailed investigation. Looks like reflection on OM.DiaSession is failing in adapter, need to debug to find what's going on.

**Comment by Faizan2304** [comment] 2017-05-17 13:59
@jeremymeng : I tried to create local repro but no luck. I have windows 10 with Creator update (OS build 15063.296). I installed .NET framework 4.7. I too don't see `System.Runtime, Version=4.1.0.0` in GAC. The version
`4.0.0.0` is in GAC.

Do you have repro machine where I can debug the issue? If not can you please try to provide us crash dump.

To get the dump, attach vstest.executionengine.x86.exe (or vstest.console.exe if you are using TPv2 by enabling it through testplatform.config) and enable first chance exception. When it throws above mentioned exception save the dump.

**Comment by jeremymeng** [comment] 2017-05-17 17:24
@Faizan2304 When I attach to vstest.console.exe and run my test from Visual Studio, the only first-chance exception I got is the following one

```
0:015> !pe
Exception object: 000001638031a1b0
Exception type:   System.ArgumentException
Message:          FrameworkName cannot have less than two components or more than three components.
InnerException:   <none>
StackTrace (generated):
<none>
StackTraceString: <none>
HResult: 80070057
0:015> !clrstack
OS Thread Id: 0x2cb0 (15)
        Child SP               IP Call Site
00000002e9b3e998 00007ffa612000a8 [HelperMethodFrame: 00000002e9b3e998] 
00000002e9b3ea80 00007ffa4d3a502f System.Runtime.Versioning.FrameworkName..ctor(System.String) [f:\dd\NDP\fx\src\sys\system\runtime\versioning\FrameworkName.cs @ 141]
00000002e9b3eaf0 00007ff9f267b161 Microsoft.VisualStudio.TestPlatform.ObjectModel.Framework.FromString(System.String)
00000002e9b3eb40 00007ff9f2814d0f Microsoft.VisualStudio.TestPlatform.ObjectModel.RunConfiguration.FromXml(System.Xml.XmlReader)
00000002e9b3ec10 00007ff9f267a9c2 Microsoft.VisualStudio.TestPlatform.ObjectModel.Utilities.XmlRunSettingsUtilities.GetNodeValue[[System.__Canon, mscorlib]](System.String, System.String, System.Func`2)
00000002e9b3ec80 00007ff9f267a895 Microsoft.VisualStudio.TestPlatform.ObjectModel.Utilities.XmlRunSettingsUtilities.GetRunConfigurationNode(System.String)
00000002e9b3ecc0 00007ff9f2816cf3 Microsoft.VisualStudio.TestPlatform.Common.Utilities.RunSettingsUtilities.GetMaxCpuCount(System.String)
00000002e9b3ed10 00007ff9f2816aed Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.TestEngine.VerifyParallelSettingAndCalculateParallelLevel(Int32, System.String)
00000002e9b3ed90 00007ff9f2825c42 Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.TestEngine.GetExecutionManager(Microsoft.VisualStudio.TestPlatform.ObjectModel.Engine.ITestHostManager, Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.TestRunCriteria)
00000002e9b3ede0 00007ff9f282573e Microsoft.VisualStudio.TestPlatform.Client.TestPlatform.CreateTestRunRequest(Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.TestRunCriteria)
00000002e9b3ee20 00007ff9f28253d8 Microsoft.VisualStudio.TestPlatform.CommandLine.TestPlatformHelpers.TestRequestManager.RunTests(Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.TestRunCriteria, Microsoft.VisualStudio.TestPlatform.Common.Interfaces.ITestRunEventsRegistrar)
00000002e9b3ee90 00007ff9f2824cff Microsoft.VisualStudio.TestPlatform.CommandLine.TestPlatformHelpers.TestRequestManager.RunTests(Microsoft.VisualStudio.TestPlatform.Client.RequestHelper.TestRunRequestPayload, Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.Interfaces.ITestHostLauncher, Microsoft.VisualStudio.TestPlatform.Common.Interfaces.ITestRunEventsRegistrar)
00000002e9b3ef30 00007ff9f2824a72 Microsoft.VisualStudio.TestPlatform.Client.DesignMode.DesignModeClient+c__DisplayClass17_0.b__0()
00000002e9b3efa0 00007ffa4f4cf3f6 System.Threading.Tasks.Task.Execute() [f:\dd\ndp\clr\src\BCL\system\threading\Tasks\Task.cs @ 2498]
00000002e9b3efe0 00007ffa4f4a08de System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) [f:\dd\ndp\clr\src\BCL\system\threading\executioncontext.cs @ 954]
00000002e9b3f0b0 00007ffa4f4a0774 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) [f:\dd\ndp\clr\src\BCL\system\threading\executioncontext.cs @ 902]
00000002e9b3f0e0 00007ffa4f4cf698 System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef) [f:\dd\ndp\clr\src\BCL\system\threading\Tasks\Task.cs @ 2827]
00000002e9b3f190 00007ffa4f4cedd3 System.Threading.Tasks.Task.ExecuteEntry(Boolean) [f:\dd\ndp\clr\src\BCL\system\threading\Tasks\Task.cs @ 2767]
00000002e9b3f1d0 00007ffa4f4748ce System.Threading.ThreadPoolWorkQueue.Dispatch() [f:\dd\ndp\clr\src\BCL\system\threading\threadpool.cs @ 820]
00000002e9b3f668 00007ffa51c461d3 [DebuggerU2MCatchHandlerFrame: 00000002e9b3f668] 
```

This is the run settings on the stack

```
  <RunConfiguration>
    <ResultsDirectory>E:\temp\test4\TestResults</ResultsDirectory>
    <SolutionDirectory>E:\temp\test4\</SolutionDirectory>
    <TargetPlatform>X86</TargetPlatform>
    <TargetFrameworkVersion>Framework45</TargetFrameworkVersion>
    <DesignMode>True</DesignMode>
  </RunConfiguration>
</RunSettings>
```

I didn't get the `System.TypeInitializationException` shown in Visual Studio Output window.

**Comment by codito** [comment] 2017-06-22 04:34
Workaround:
1. Rename "C:\Users\<user>\.nuget\packages\xunit.runner.visualstudio\2.2.0\build\netcoreapp1.0\xunit.runner.visualstudio.dotnetcore.testadapter.dll" to "C:\Users\<user>\.nuget\packages\xunit.runner.visualstudio\2.2.0\build\netcoreapp1.0\xunit.runner.visualstudio.dotnetcore.testadapter.dll.1"
2. Delete everything inside %temp%\VisualStudioTestExplorerExtensions
3. Restart VS, run tests

**Comment by JoeBrockhaus** [comment] 2017-06-23 01:20
I'm getting this today as well. @codito 's workaround didn't work for me :(

Actually, most of my development environment suffered from this latest Preview build (16226.rs_prerelease.170616-2021)

**Comment by craigktreasure** [comment] 2017-06-23 03:19
Not sure if it's the same for 2.2.0, but for 2.3.0-beta3-build3705 i also commented out this section of `C:\Users\<user>\AppData\Local\Temp\VisualStudioTestExplorerExtensions\2.3.0-beta3-build3705\build\netcoreapp1.0\xunit.runner.visualstudio.props` to get it to build:
```xml
    <!-- <None Include="$(MSBuildThisFileDirectory)xunit.runner.visualstudio.dotnetcore.testadapter.dll"> -->
      <!-- <Link>xunit.runner.visualstudio.dotnetcore.testadapter.dll</Link> -->
      <!-- <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory> -->
      <!-- <Visible>False</Visible> -->
    <!-- </None> -->
```

**Comment by BradBarnich** [comment] 2017-06-30 17:12
Seeing this on non-SDK csproj too. The workaround works, but to packages folder in the source tree.

**Comment by codito** [comment] 2017-07-06 11:12
Created https://github.com/xunit/xunit/issues/1348 and PR https://github.com/xunit/xunit/pull/1349 in an attempt to fix this. This allows users on older versions of VS to be unblocked.

We need to fix the adapter lookup logic in vstest too. Please see [this RFC](https://github.com/Microsoft/vstest-docs/pull/60/files#diff-d10c4dd7b8ad8dfbf6132ecb62262f4f) for details on vstest changes. It will likely get implemented post 15.3 release.

**Comment by codito** [comment] 2017-07-07 13:10
Moved to 15.5 to track closure for this issue.

**Comment by bradwilson** [comment] 2017-07-10 21:05
We have merged the change, though it's currently untested (I don't have a machine with .NET 4.7 on it at the moment).

A merged version that can be verified is available as of version `2.3.0-beta4-build3722`, available through [MyGet](https://myget.org/gallery/xunit).

**Comment by JoeBrockhaus** [comment] 2017-07-10 21:32
@bradwilson this worked for me after updating and restarting VS(17).

**Comment by jeremymeng** [comment] 2017-07-10 22:04
`2.3.0-beta4-build3722` works for me too.

**Comment by codito** [comment] 2017-07-11 06:11
Closing the issue since we have confirmation that the fix works :)

**Closed by codito** 2017-07-11 06:11 UTC
Labels: bug, exp: cli, exp: ide

**Comment by DustinCampbell** [comment] 2017-07-18 17:51
FYI, that this fixed OmniSharp's tests in VS 2017 as well.

**Comment by stankovski** [comment] 2017-10-16 15:51
@codito please re-open this as the issue is still reproing in 15.4

**Comment by faesel** [comment] 2017-10-23 10:53
I could like to add that in addition to the steps @codito mentioned above I also had to delete my packages folder in my solution and rebuild.

**Comment by Bogatinov** [comment] 2017-10-26 15:28
Seems like this bug shows in v15.4.1 of Visual Studio for xUnit v2.2.0 with .NET 4.6.2 on Windows 10 Creators October 2017.

Workaround by @codito works, update to xUnit v2.3.0 also seems to work. Unfortunately update to xUnit v.2.3.0 changes the behavior of the following code and breaks many tests
```
[assembly: CollectionBehavior(MaxParallelThreads = 1, DisableTestParallelization = true)]
```

**Comment by Porges** [comment] 2017-11-10 04:14
I'm able to run my tests normally, but when attempting to _profile_ them I'm encountering the "unable to load `System.Reflection.TypeExtensions`" error.

I have:
* xunit 2.3.1
* VS 15.4.3

My test project targets `netcoreapp2.0` (it has a dependency on other .exe projects). The tests run *without profiling* under Test Explorer and R# just fine. I've tried clearing the 'VSTEEE' folder.

**Comment by jamesrcounts** [comment] 2017-11-28 00:31
After trying all of the above workarounds and still encountering problems, I deleted leftover app.config files (which had binding redirects in them).  Problem solved.

**Comment by hyalkaf** [comment] 2018-01-17 20:56
I tried some of the solutions above as well and no luck

**Comment by ninjaboy** [comment] 2018-01-25 12:26
@jamesrcounts, is there any way you could indicate which was that leftover app.config that was causing the issue?

**Comment by ninjaboy** [comment] 2018-01-25 14:42
Consolidating xUnit related nuget depdendencies and upconverting xUnit.analyzers did the trick for me.

**Comment by apryiomka** [comment] 2018-01-26 23:52
Why this is closed, the issue still persists

**Comment by AlokArora** [comment] 2018-02-15 09:27
Still facing the issue, none of your solutions above are actually solutions, they are just workarounds!

**Comment by ninjaboy** [comment] 2018-02-19 17:53
Gentlemen, make sure to update your unit tests runner tools dependencies
and such dependencies alike. In my case updating all xunit dependencies and
consolidating their versions did the trick.

**Comment by AlokArora** [comment] 2018-02-20 05:52
For me when i upgraded to 4.7 framework, updating the dependencies to target net47 worked instead of net45.

**Comment by dprothero** [comment] 2018-03-02 17:02
> Gentlemen, make sure to update your unit tests runner tools dependencies and such dependencies alike. In my case updating all xunit dependencies and consolidating their versions did the trick.

@ninjaboy could you be more specific on what this means and how to do it?

**Comment by ninjaboy** [comment] 2018-03-02 18:17
https://stackoverflow.com/questions/43065518/how-to-consolidate-all-applicable-projects-and-nuget-packages-from-the-command-l

https://www.google.co.uk/amp/s/artczernecki.wordpress.com/2015/09/08/consolidating-package-versions-with-visual-studio-2015-nuget-package-manager/amp/

**Comment by bjorn-ali-goransson** [comment] 2018-04-12 13:53
Try deleting your `AppData\Local\Temp\VisualStudioTestExplorerExtensions` folder and restarting visual studio.

I also updated my XUnit packages first, but it did not want to work until I did this as well.

**Comment by NateZimmer** [comment] 2018-05-24 21:16
Restarting Visual Studio after deleting `AppData\Local\Temp\VisualStudioTestExplorerExtensions` did the trick for me.

**Comment by memosk1000** [comment] 2018-05-25 08:44
This problem is not platform dependent . It appears also for other kinds tester nugets. Also for Microsoft's
