### ISSUE TITLE
UWP Deploy failing when TestApp is already deployed with different Configuration

### ISSUE THREAD

**Issue by DerGary** [Microsoft/vstest#1520] opened 2018-03-29 09:18 UTC
## Description
vstest.console.exe fails because it can not deploy the app. This only happens if the test app is already installed but build with another configuration. If the test app is not installed everything works. If the test app with the same configuration is installed everything works as well.

## Steps to reproduce
Unfortunately I can not reproduce this on my developer machine only on our build server. Although they both have the same Versions of Windows/VS/VSTest. But I will be happy to provide any log file or information that I can to help solve this issue.

1. run the tests from the Debug version of the test app (everything works)
2. run the tests from the Release version of the test app (fails deploying the app)
3. uninstall debug test app
4. run the tests from the Release version of the test app (everything works)

Sample Project:
[UnitTestApp.zip](https://github.com/Microsoft/vstest/files/1859377/UnitTestApp.zip)

## Expected behavior
Deploying works and tests do run correctly

## Actual behavior
Running the tests for the installed configuration works. Running the tests for another configuration fails because the deployment of the app fails.

## Diagnostic logs
Command Line with error:
```
PS C:\Tools\agent\_work\71\s\UnitTestApp\bin\x86\Release> vstest.console.exe .\UnitTestApp.build.appxrecipe /Framework:FrameworkUap10
Microsoft (R) Test Execution Command Line Tool Version 15.6.1
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
DEP0600: Deployment failed. InvalidOperationException - Operation is not valid due to the current state of the object. [0x80131509]

Deployment operation failed.
Failed to deploy to target 'Local Machine', the operation cannot continue.
Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Failed to initialize client proxy: could not connect to test process.
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyExecutionManager.StartTestRun(TestRunCriteria testRunCriteria, ITestRunEventsHandler eventHandler)

Test Run Aborted.
```

Diagnostics Log of vstest.console.exe:
[log.txt](https://github.com/Microsoft/vstest/files/1859244/log.txt)

Event Viewer Reports the following error for AppxDeployment:
```
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
	<System>
		<Provider Name="Microsoft-Windows-AppXDeployment" Guid="{8127F6D4-59F9-4ABF-8952-3E3A02073D5F}" /> 
		<EventID>302</EventID> 
		<Version>0</Version> 
		<Level>2</Level> 
		<Task>4</Task> 
		<Opcode>0</Opcode> 
		<Keywords>0x4000400000010000</Keywords> 
		<TimeCreated SystemTime="2017-09-26T07:45:02.822679900Z" /> 
		<EventRecordID>12</EventRecordID> 
		<Correlation /> 
		<Execution ProcessID="904" ThreadID="1228" /> 
		<Channel>Microsoft-Windows-AppXDeployment/Operational</Channel> 
		<Computer>****</Computer> 
		<Security UserID="S-1-5-18" /> 
	</System>
	<EventData>
		<Data Name="ServiceName">appxsvc</Data> 
		<Data Name="ErrorCode">0x8007045b</Data> 
	</EventData>
</Event>
```

## Environment
Operating system: Windows 10 Enterprise 1703 (build 15063.483)
Visual Studio: 15.6.4
VSTest Platform: 15.6.1

**Comment by DerGary** [comment] 2018-04-17 08:58
someone please?

**Comment by mayankbansal018** [comment] 2018-05-05 04:58
@DerGary , sorry for the delay, we are aware of this issue, & I'll sync-up with UWP team to understand how to mitigate this.

**Comment by DerGary** [comment] 2018-05-07 06:02
@mayankbansal018 As a workaround I'm currently using a Powershell Script in my build definition to remove the TestApp before it gets installed, may be handy if someone else has this problem:

```
$package = Get-AppxPackage -Name TestAppName
if($package){
    Remove-AppxPackage -Package $package.PackageFullName
}
```

**Comment by mayankbansal018** [comment] 2018-05-07 06:12
@DerGary , thanks for providing a workaround, I'm still working with UWP team to see how we can mitigate this issue.

**Comment by mayankbansal018** [comment] 2018-05-14 09:01
@DerGary this is indeed a behavior change, however as a possible workaround we suggest you use ".appxrecipe"(present in bin\debug folder) as input to CLI. 
Further we would like to know if there is any particular reason as to why you want to use ".appx" as input to CLI.

Also I've created an internal issue to track this behavior change, we expect to close on the exp soon.

**Comment by DerGary** [comment] 2018-05-14 09:15
@mayankbansal018 I don't really know what you are talking about, I'm using ".appxrecipe" as input to CLI as can be seen in the Diagnostic Log I added in the original post. Using ".appx" as input for CLI did not work with VS v15.6.x. (Did not test it with 15.7 yet)

**Comment by mayankbansal018** [comment] 2018-05-14 09:19
@DerGary , my apologies, I missed the command line, & assumed that this issue was due to ".appx" as we have seen it internally, however never seen it with ".appxrecipe". I'll investigate it more.

**Comment by mayankbansal018** [comment] 2018-05-14 09:26
@DerGary I tried this locally on win10 client machine, & could not reproduce this. I'll try it on a win10 server machine, to see if it is specific to it. Will get back to you once I've some analysis.

**Comment by mayankbansal018** [comment] 2018-05-15 12:37
@DerGary , I tried to repro this issue with your sample project on win10 server machine(10.0.14393), & I could not repro the issue.

To investigate this further can you please run this on machines where you facing this, & also enable "--diag:<path_to_log>" flag for vstest.console.

e.g. vstest.console.exe .\UnitTestApp.build.appxrecipe /Framework:FrameworkUap10 --diag:"C:\logs\log.txt"

you should see two logs path printed on console,for each run, please share them.

**Comment by mayankbansal018** [comment] 2018-05-22 06:32
Sure, I'll close this issue for now, please ping back on it, if you face it again

**Closed by mayankbansal018** 2018-05-22 06:32 UTC
Labels: bug

**Comment by DerGary** [comment] 2018-05-23 11:51
@mayankbansal018 I just encountered the Problem again and here is the diagnostic log. 
For me it does not seem to contain any further information.
[log.txt](https://github.com/Microsoft/vstest/files/2030856/log.txt)
